// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/markets/price_feeds/types"
)

// NewPriceFeedsStore creates a new instance of PriceFeedsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceFeedsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceFeedsStore {
	mock := &PriceFeedsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PriceFeedsStore is an autogenerated mock type for the PriceFeedsStore type
type PriceFeedsStore struct {
	mock.Mock
}

type PriceFeedsStore_Expecter struct {
	mock *mock.Mock
}

func (_m *PriceFeedsStore) EXPECT() *PriceFeedsStore_Expecter {
	return &PriceFeedsStore_Expecter{mock: &_m.Mock}
}

// GetLastUpdated provides a mock function for the type PriceFeedsStore
func (_mock *PriceFeedsStore) GetLastUpdated() map[types.PriceFeedID]time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastUpdated")
	}

	var r0 map[types.PriceFeedID]time.Time
	if returnFunc, ok := ret.Get(0).(func() map[types.PriceFeedID]time.Time); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.PriceFeedID]time.Time)
		}
	}
	return r0
}

// PriceFeedsStore_GetLastUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastUpdated'
type PriceFeedsStore_GetLastUpdated_Call struct {
	*mock.Call
}

// GetLastUpdated is a helper method to define mock.On call
func (_e *PriceFeedsStore_Expecter) GetLastUpdated() *PriceFeedsStore_GetLastUpdated_Call {
	return &PriceFeedsStore_GetLastUpdated_Call{Call: _e.mock.On("GetLastUpdated")}
}

func (_c *PriceFeedsStore_GetLastUpdated_Call) Run(run func()) *PriceFeedsStore_GetLastUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PriceFeedsStore_GetLastUpdated_Call) Return(priceFeedIDToTime map[types.PriceFeedID]time.Time) *PriceFeedsStore_GetLastUpdated_Call {
	_c.Call.Return(priceFeedIDToTime)
	return _c
}

func (_c *PriceFeedsStore_GetLastUpdated_Call) RunAndReturn(run func() map[types.PriceFeedID]time.Time) *PriceFeedsStore_GetLastUpdated_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestPrice provides a mock function for the type PriceFeedsStore
func (_mock *PriceFeedsStore) GetLatestPrice(feedID types.PriceFeedID) (types.PriceSnapshot, error) {
	ret := _mock.Called(feedID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestPrice")
	}

	var r0 types.PriceSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(types.PriceFeedID) (types.PriceSnapshot, error)); ok {
		return returnFunc(feedID)
	}
	if returnFunc, ok := ret.Get(0).(func(types.PriceFeedID) types.PriceSnapshot); ok {
		r0 = returnFunc(feedID)
	} else {
		r0 = ret.Get(0).(types.PriceSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(types.PriceFeedID) error); ok {
		r1 = returnFunc(feedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PriceFeedsStore_GetLatestPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestPrice'
type PriceFeedsStore_GetLatestPrice_Call struct {
	*mock.Call
}

// GetLatestPrice is a helper method to define mock.On call
//   - feedID types.PriceFeedID
func (_e *PriceFeedsStore_Expecter) GetLatestPrice(feedID interface{}) *PriceFeedsStore_GetLatestPrice_Call {
	return &PriceFeedsStore_GetLatestPrice_Call{Call: _e.mock.On("GetLatestPrice", feedID)}
}

func (_c *PriceFeedsStore_GetLatestPrice_Call) Run(run func(feedID types.PriceFeedID)) *PriceFeedsStore_GetLatestPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.PriceFeedID
		if args[0] != nil {
			arg0 = args[0].(types.PriceFeedID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PriceFeedsStore_GetLatestPrice_Call) Return(priceSnapshot types.PriceSnapshot, err error) *PriceFeedsStore_GetLatestPrice_Call {
	_c.Call.Return(priceSnapshot, err)
	return _c
}

func (_c *PriceFeedsStore_GetLatestPrice_Call) RunAndReturn(run func(feedID types.PriceFeedID) (types.PriceSnapshot, error)) *PriceFeedsStore_GetLatestPrice_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriceAtTime provides a mock function for the type PriceFeedsStore
func (_mock *PriceFeedsStore) GetPriceAtTime(feedID types.PriceFeedID, t time.Time) (types.PriceSnapshot, error) {
	ret := _mock.Called(feedID, t)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceAtTime")
	}

	var r0 types.PriceSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(types.PriceFeedID, time.Time) (types.PriceSnapshot, error)); ok {
		return returnFunc(feedID, t)
	}
	if returnFunc, ok := ret.Get(0).(func(types.PriceFeedID, time.Time) types.PriceSnapshot); ok {
		r0 = returnFunc(feedID, t)
	} else {
		r0 = ret.Get(0).(types.PriceSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(types.PriceFeedID, time.Time) error); ok {
		r1 = returnFunc(feedID, t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PriceFeedsStore_GetPriceAtTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceAtTime'
type PriceFeedsStore_GetPriceAtTime_Call struct {
	*mock.Call
}

// GetPriceAtTime is a helper method to define mock.On call
//   - feedID types.PriceFeedID
//   - t time.Time
func (_e *PriceFeedsStore_Expecter) GetPriceAtTime(feedID interface{}, t interface{}) *PriceFeedsStore_GetPriceAtTime_Call {
	return &PriceFeedsStore_GetPriceAtTime_Call{Call: _e.mock.On("GetPriceAtTime", feedID, t)}
}

func (_c *PriceFeedsStore_GetPriceAtTime_Call) Run(run func(feedID types.PriceFeedID, t time.Time)) *PriceFeedsStore_GetPriceAtTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.PriceFeedID
		if args[0] != nil {
			arg0 = args[0].(types.PriceFeedID)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PriceFeedsStore_GetPriceAtTime_Call) Return(priceSnapshot types.PriceSnapshot, err error) *PriceFeedsStore_GetPriceAtTime_Call {
	_c.Call.Return(priceSnapshot, err)
	return _c
}

func (_c *PriceFeedsStore_GetPriceAtTime_Call) RunAndReturn(run func(feedID types.PriceFeedID, t time.Time) (types.PriceSnapshot, error)) *PriceFeedsStore_GetPriceAtTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriceRange provides a mock function for the type PriceFeedsStore
func (_mock *PriceFeedsStore) GetPriceRange(feedID types.PriceFeedID, start time.Time, end time.Time) ([]types.PriceSnapshot, error) {
	ret := _mock.Called(feedID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceRange")
	}

	var r0 []types.PriceSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(types.PriceFeedID, time.Time, time.Time) ([]types.PriceSnapshot, error)); ok {
		return returnFunc(feedID, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(types.PriceFeedID, time.Time, time.Time) []types.PriceSnapshot); ok {
		r0 = returnFunc(feedID, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.PriceSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(types.PriceFeedID, time.Time, time.Time) error); ok {
		r1 = returnFunc(feedID, start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PriceFeedsStore_GetPriceRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceRange'
type PriceFeedsStore_GetPriceRange_Call struct {
	*mock.Call
}

// GetPriceRange is a helper method to define mock.On call
//   - feedID types.PriceFeedID
//   - start time.Time
//   - end time.Time
func (_e *PriceFeedsStore_Expecter) GetPriceRange(feedID interface{}, start interface{}, end interface{}) *PriceFeedsStore_GetPriceRange_Call {
	return &PriceFeedsStore_GetPriceRange_Call{Call: _e.mock.On("GetPriceRange", feedID, start, end)}
}

func (_c *PriceFeedsStore_GetPriceRange_Call) Run(run func(feedID types.PriceFeedID, start time.Time, end time.Time)) *PriceFeedsStore_GetPriceRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.PriceFeedID
		if args[0] != nil {
			arg0 = args[0].(types.PriceFeedID)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PriceFeedsStore_GetPriceRange_Call) Return(priceSnapshots []types.PriceSnapshot, err error) *PriceFeedsStore_GetPriceRange_Call {
	_c.Call.Return(priceSnapshots, err)
	return _c
}

func (_c *PriceFeedsStore_GetPriceRange_Call) RunAndReturn(run func(feedID types.PriceFeedID, start time.Time, end time.Time) ([]types.PriceSnapshot, error)) *PriceFeedsStore_GetPriceRange_Call {
	_c.Call.Return(run)
	return _c
}

// PruneOldData provides a mock function for the type PriceFeedsStore
func (_mock *PriceFeedsStore) PruneOldData(olderThan time.Time) error {
	ret := _mock.Called(olderThan)

	if len(ret) == 0 {
		panic("no return value specified for PruneOldData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = returnFunc(olderThan)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PriceFeedsStore_PruneOldData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneOldData'
type PriceFeedsStore_PruneOldData_Call struct {
	*mock.Call
}

// PruneOldData is a helper method to define mock.On call
//   - olderThan time.Time
func (_e *PriceFeedsStore_Expecter) PruneOldData(olderThan interface{}) *PriceFeedsStore_PruneOldData_Call {
	return &PriceFeedsStore_PruneOldData_Call{Call: _e.mock.On("PruneOldData", olderThan)}
}

func (_c *PriceFeedsStore_PruneOldData_Call) Run(run func(olderThan time.Time)) *PriceFeedsStore_PruneOldData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PriceFeedsStore_PruneOldData_Call) Return(err error) *PriceFeedsStore_PruneOldData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PriceFeedsStore_PruneOldData_Call) RunAndReturn(run func(olderThan time.Time) error) *PriceFeedsStore_PruneOldData_Call {
	_c.Call.Return(run)
	return _c
}

// RecordPrice provides a mock function for the type PriceFeedsStore
func (_mock *PriceFeedsStore) RecordPrice(snap types.PriceSnapshot) error {
	ret := _mock.Called(snap)

	if len(ret) == 0 {
		panic("no return value specified for RecordPrice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(types.PriceSnapshot) error); ok {
		r0 = returnFunc(snap)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PriceFeedsStore_RecordPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordPrice'
type PriceFeedsStore_RecordPrice_Call struct {
	*mock.Call
}

// RecordPrice is a helper method to define mock.On call
//   - snap types.PriceSnapshot
func (_e *PriceFeedsStore_Expecter) RecordPrice(snap interface{}) *PriceFeedsStore_RecordPrice_Call {
	return &PriceFeedsStore_RecordPrice_Call{Call: _e.mock.On("RecordPrice", snap)}
}

func (_c *PriceFeedsStore_RecordPrice_Call) Run(run func(snap types.PriceSnapshot)) *PriceFeedsStore_RecordPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.PriceSnapshot
		if args[0] != nil {
			arg0 = args[0].(types.PriceSnapshot)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PriceFeedsStore_RecordPrice_Call) Return(err error) *PriceFeedsStore_RecordPrice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PriceFeedsStore_RecordPrice_Call) RunAndReturn(run func(snap types.PriceSnapshot) error) *PriceFeedsStore_RecordPrice_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastUpdated provides a mock function for the type PriceFeedsStore
func (_mock *PriceFeedsStore) UpdateLastUpdated(feedID types.PriceFeedID) {
	_mock.Called(feedID)
	return
}

// PriceFeedsStore_UpdateLastUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastUpdated'
type PriceFeedsStore_UpdateLastUpdated_Call struct {
	*mock.Call
}

// UpdateLastUpdated is a helper method to define mock.On call
//   - feedID types.PriceFeedID
func (_e *PriceFeedsStore_Expecter) UpdateLastUpdated(feedID interface{}) *PriceFeedsStore_UpdateLastUpdated_Call {
	return &PriceFeedsStore_UpdateLastUpdated_Call{Call: _e.mock.On("UpdateLastUpdated", feedID)}
}

func (_c *PriceFeedsStore_UpdateLastUpdated_Call) Run(run func(feedID types.PriceFeedID)) *PriceFeedsStore_UpdateLastUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.PriceFeedID
		if args[0] != nil {
			arg0 = args[0].(types.PriceFeedID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PriceFeedsStore_UpdateLastUpdated_Call) Return() *PriceFeedsStore_UpdateLastUpdated_Call {
	_c.Call.Return()
	return _c
}

func (_c *PriceFeedsStore_UpdateLastUpdated_Call) RunAndReturn(run func(feedID types.PriceFeedID)) *PriceFeedsStore_UpdateLastUpdated_Call {
	_c.Run(run)
	return _c
}
