// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/types/config"
)

// NewMockAssetLoader creates a new instance of MockAssetLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssetLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssetLoader {
	mock := &MockAssetLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAssetLoader is an autogenerated mock type for the AssetLoader type
type MockAssetLoader struct {
	mock.Mock
}

type MockAssetLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssetLoader) EXPECT() *MockAssetLoader_Expecter {
	return &MockAssetLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockAssetLoader
func (_mock *MockAssetLoader) Load(cfg *config.StartupConfig) error {
	ret := _mock.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*config.StartupConfig) error); ok {
		r0 = returnFunc(cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAssetLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockAssetLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - cfg *config.StartupConfig
func (_e *MockAssetLoader_Expecter) Load(cfg interface{}) *MockAssetLoader_Load_Call {
	return &MockAssetLoader_Load_Call{Call: _e.mock.On("Load", cfg)}
}

func (_c *MockAssetLoader_Load_Call) Run(run func(cfg *config.StartupConfig)) *MockAssetLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *config.StartupConfig
		if args[0] != nil {
			arg0 = args[0].(*config.StartupConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAssetLoader_Load_Call) Return(err error) *MockAssetLoader_Load_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAssetLoader_Load_Call) RunAndReturn(run func(cfg *config.StartupConfig) error) *MockAssetLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}
