// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/markets/spot/types"
	"github.com/wisp-trading/sdk/pkg/types/connector"
	"github.com/wisp-trading/sdk/pkg/types/execution"
)

// NewSignalExecutor creates a new instance of SignalExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignalExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignalExecutor {
	mock := &SignalExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SignalExecutor is an autogenerated mock type for the SignalExecutor type
type SignalExecutor struct {
	mock.Mock
}

type SignalExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *SignalExecutor) EXPECT() *SignalExecutor_Expecter {
	return &SignalExecutor_Expecter{mock: &_m.Mock}
}

// ExecuteSpotSignal provides a mock function for the type SignalExecutor
func (_mock *SignalExecutor) ExecuteSpotSignal(signal types.SpotSignal, ctx *execution.ExecutionContext, result *execution.ExecutionResult) error {
	ret := _mock.Called(signal, ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteSpotSignal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(types.SpotSignal, *execution.ExecutionContext, *execution.ExecutionResult) error); ok {
		r0 = returnFunc(signal, ctx, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SignalExecutor_ExecuteSpotSignal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteSpotSignal'
type SignalExecutor_ExecuteSpotSignal_Call struct {
	*mock.Call
}

// ExecuteSpotSignal is a helper method to define mock.On call
//   - signal types.SpotSignal
//   - ctx *execution.ExecutionContext
//   - result *execution.ExecutionResult
func (_e *SignalExecutor_Expecter) ExecuteSpotSignal(signal interface{}, ctx interface{}, result interface{}) *SignalExecutor_ExecuteSpotSignal_Call {
	return &SignalExecutor_ExecuteSpotSignal_Call{Call: _e.mock.On("ExecuteSpotSignal", signal, ctx, result)}
}

func (_c *SignalExecutor_ExecuteSpotSignal_Call) Run(run func(signal types.SpotSignal, ctx *execution.ExecutionContext, result *execution.ExecutionResult)) *SignalExecutor_ExecuteSpotSignal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.SpotSignal
		if args[0] != nil {
			arg0 = args[0].(types.SpotSignal)
		}
		var arg1 *execution.ExecutionContext
		if args[1] != nil {
			arg1 = args[1].(*execution.ExecutionContext)
		}
		var arg2 *execution.ExecutionResult
		if args[2] != nil {
			arg2 = args[2].(*execution.ExecutionResult)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SignalExecutor_ExecuteSpotSignal_Call) Return(err error) *SignalExecutor_ExecuteSpotSignal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SignalExecutor_ExecuteSpotSignal_Call) RunAndReturn(run func(signal types.SpotSignal, ctx *execution.ExecutionContext, result *execution.ExecutionResult) error) *SignalExecutor_ExecuteSpotSignal_Call {
	_c.Call.Return(run)
	return _c
}

// HandleTrade provides a mock function for the type SignalExecutor
func (_mock *SignalExecutor) HandleTrade(trade connector.Trade) error {
	ret := _mock.Called(trade)

	if len(ret) == 0 {
		panic("no return value specified for HandleTrade")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(connector.Trade) error); ok {
		r0 = returnFunc(trade)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SignalExecutor_HandleTrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleTrade'
type SignalExecutor_HandleTrade_Call struct {
	*mock.Call
}

// HandleTrade is a helper method to define mock.On call
//   - trade connector.Trade
func (_e *SignalExecutor_Expecter) HandleTrade(trade interface{}) *SignalExecutor_HandleTrade_Call {
	return &SignalExecutor_HandleTrade_Call{Call: _e.mock.On("HandleTrade", trade)}
}

func (_c *SignalExecutor_HandleTrade_Call) Run(run func(trade connector.Trade)) *SignalExecutor_HandleTrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.Trade
		if args[0] != nil {
			arg0 = args[0].(connector.Trade)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SignalExecutor_HandleTrade_Call) Return(err error) *SignalExecutor_HandleTrade_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SignalExecutor_HandleTrade_Call) RunAndReturn(run func(trade connector.Trade) error) *SignalExecutor_HandleTrade_Call {
	_c.Call.Return(run)
	return _c
}
