// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/types/connector"
	"github.com/wisp-trading/sdk/pkg/types/portfolio"
	"github.com/wisp-trading/sdk/pkg/types/wisp/analytics"
	"github.com/wisp-trading/sdk/pkg/types/wisp/numerical"
)

// NewMockSpotMarket creates a new instance of MockSpotMarket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpotMarket(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpotMarket {
	mock := &MockSpotMarket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSpotMarket is an autogenerated mock type for the SpotMarket type
type MockSpotMarket struct {
	mock.Mock
}

type MockSpotMarket_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpotMarket) EXPECT() *MockSpotMarket_Expecter {
	return &MockSpotMarket_Expecter{mock: &_m.Mock}
}

// GetKlines provides a mock function for the type MockSpotMarket
func (_mock *MockSpotMarket) GetKlines(asset portfolio.Pair, exchange connector.ExchangeName, interval string, limit int) []connector.Kline {
	ret := _mock.Called(asset, exchange, interval, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetKlines")
	}

	var r0 []connector.Kline
	if returnFunc, ok := ret.Get(0).(func(portfolio.Pair, connector.ExchangeName, string, int) []connector.Kline); ok {
		r0 = returnFunc(asset, exchange, interval, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Kline)
		}
	}
	return r0
}

// MockSpotMarket_GetKlines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKlines'
type MockSpotMarket_GetKlines_Call struct {
	*mock.Call
}

// GetKlines is a helper method to define mock.On call
//   - asset portfolio.Pair
//   - exchange connector.ExchangeName
//   - interval string
//   - limit int
func (_e *MockSpotMarket_Expecter) GetKlines(asset interface{}, exchange interface{}, interval interface{}, limit interface{}) *MockSpotMarket_GetKlines_Call {
	return &MockSpotMarket_GetKlines_Call{Call: _e.mock.On("GetKlines", asset, exchange, interval, limit)}
}

func (_c *MockSpotMarket_GetKlines_Call) Run(run func(asset portfolio.Pair, exchange connector.ExchangeName, interval string, limit int)) *MockSpotMarket_GetKlines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 portfolio.Pair
		if args[0] != nil {
			arg0 = args[0].(portfolio.Pair)
		}
		var arg1 connector.ExchangeName
		if args[1] != nil {
			arg1 = args[1].(connector.ExchangeName)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSpotMarket_GetKlines_Call) Return(klines []connector.Kline) *MockSpotMarket_GetKlines_Call {
	_c.Call.Return(klines)
	return _c
}

func (_c *MockSpotMarket_GetKlines_Call) RunAndReturn(run func(asset portfolio.Pair, exchange connector.ExchangeName, interval string, limit int) []connector.Kline) *MockSpotMarket_GetKlines_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradableQuantity provides a mock function for the type MockSpotMarket
func (_mock *MockSpotMarket) GetTradableQuantity(ctx context.Context, asset portfolio.Pair, opts ...analytics.LiquidityOptions) numerical.Decimal {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, asset, opts)
	} else {
		tmpRet = _mock.Called(ctx, asset)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetTradableQuantity")
	}

	var r0 numerical.Decimal
	if returnFunc, ok := ret.Get(0).(func(context.Context, portfolio.Pair, ...analytics.LiquidityOptions) numerical.Decimal); ok {
		r0 = returnFunc(ctx, asset, opts...)
	} else {
		r0 = ret.Get(0).(numerical.Decimal)
	}
	return r0
}

// MockSpotMarket_GetTradableQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradableQuantity'
type MockSpotMarket_GetTradableQuantity_Call struct {
	*mock.Call
}

// GetTradableQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - asset portfolio.Pair
//   - opts ...analytics.LiquidityOptions
func (_e *MockSpotMarket_Expecter) GetTradableQuantity(ctx interface{}, asset interface{}, opts ...interface{}) *MockSpotMarket_GetTradableQuantity_Call {
	return &MockSpotMarket_GetTradableQuantity_Call{Call: _e.mock.On("GetTradableQuantity",
		append([]interface{}{ctx, asset}, opts...)...)}
}

func (_c *MockSpotMarket_GetTradableQuantity_Call) Run(run func(ctx context.Context, asset portfolio.Pair, opts ...analytics.LiquidityOptions)) *MockSpotMarket_GetTradableQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 portfolio.Pair
		if args[1] != nil {
			arg1 = args[1].(portfolio.Pair)
		}
		var arg2 []analytics.LiquidityOptions
		var variadicArgs []analytics.LiquidityOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]analytics.LiquidityOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSpotMarket_GetTradableQuantity_Call) Return(decimal numerical.Decimal) *MockSpotMarket_GetTradableQuantity_Call {
	_c.Call.Return(decimal)
	return _c
}

func (_c *MockSpotMarket_GetTradableQuantity_Call) RunAndReturn(run func(ctx context.Context, asset portfolio.Pair, opts ...analytics.LiquidityOptions) numerical.Decimal) *MockSpotMarket_GetTradableQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// OrderBook provides a mock function for the type MockSpotMarket
func (_mock *MockSpotMarket) OrderBook(ctx context.Context, asset portfolio.Pair, exchange connector.ExchangeName) (*connector.OrderBook, error) {
	ret := _mock.Called(ctx, asset, exchange)

	if len(ret) == 0 {
		panic("no return value specified for OrderBook")
	}

	var r0 *connector.OrderBook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, portfolio.Pair, connector.ExchangeName) (*connector.OrderBook, error)); ok {
		return returnFunc(ctx, asset, exchange)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, portfolio.Pair, connector.ExchangeName) *connector.OrderBook); ok {
		r0 = returnFunc(ctx, asset, exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.OrderBook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, portfolio.Pair, connector.ExchangeName) error); ok {
		r1 = returnFunc(ctx, asset, exchange)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSpotMarket_OrderBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderBook'
type MockSpotMarket_OrderBook_Call struct {
	*mock.Call
}

// OrderBook is a helper method to define mock.On call
//   - ctx context.Context
//   - asset portfolio.Pair
//   - exchange connector.ExchangeName
func (_e *MockSpotMarket_Expecter) OrderBook(ctx interface{}, asset interface{}, exchange interface{}) *MockSpotMarket_OrderBook_Call {
	return &MockSpotMarket_OrderBook_Call{Call: _e.mock.On("OrderBook", ctx, asset, exchange)}
}

func (_c *MockSpotMarket_OrderBook_Call) Run(run func(ctx context.Context, asset portfolio.Pair, exchange connector.ExchangeName)) *MockSpotMarket_OrderBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 portfolio.Pair
		if args[1] != nil {
			arg1 = args[1].(portfolio.Pair)
		}
		var arg2 connector.ExchangeName
		if args[2] != nil {
			arg2 = args[2].(connector.ExchangeName)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSpotMarket_OrderBook_Call) Return(orderBook *connector.OrderBook, err error) *MockSpotMarket_OrderBook_Call {
	_c.Call.Return(orderBook, err)
	return _c
}

func (_c *MockSpotMarket_OrderBook_Call) RunAndReturn(run func(ctx context.Context, asset portfolio.Pair, exchange connector.ExchangeName) (*connector.OrderBook, error)) *MockSpotMarket_OrderBook_Call {
	_c.Call.Return(run)
	return _c
}

// Price provides a mock function for the type MockSpotMarket
func (_mock *MockSpotMarket) Price(ctx context.Context, asset portfolio.Pair, exchange ...connector.ExchangeName) (numerical.Decimal, error) {
	var tmpRet mock.Arguments
	if len(exchange) > 0 {
		tmpRet = _mock.Called(ctx, asset, exchange)
	} else {
		tmpRet = _mock.Called(ctx, asset)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Price")
	}

	var r0 numerical.Decimal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, portfolio.Pair, ...connector.ExchangeName) (numerical.Decimal, error)); ok {
		return returnFunc(ctx, asset, exchange...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, portfolio.Pair, ...connector.ExchangeName) numerical.Decimal); ok {
		r0 = returnFunc(ctx, asset, exchange...)
	} else {
		r0 = ret.Get(0).(numerical.Decimal)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, portfolio.Pair, ...connector.ExchangeName) error); ok {
		r1 = returnFunc(ctx, asset, exchange...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSpotMarket_Price_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Price'
type MockSpotMarket_Price_Call struct {
	*mock.Call
}

// Price is a helper method to define mock.On call
//   - ctx context.Context
//   - asset portfolio.Pair
//   - exchange ...connector.ExchangeName
func (_e *MockSpotMarket_Expecter) Price(ctx interface{}, asset interface{}, exchange ...interface{}) *MockSpotMarket_Price_Call {
	return &MockSpotMarket_Price_Call{Call: _e.mock.On("Price",
		append([]interface{}{ctx, asset}, exchange...)...)}
}

func (_c *MockSpotMarket_Price_Call) Run(run func(ctx context.Context, asset portfolio.Pair, exchange ...connector.ExchangeName)) *MockSpotMarket_Price_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 portfolio.Pair
		if args[1] != nil {
			arg1 = args[1].(portfolio.Pair)
		}
		var arg2 []connector.ExchangeName
		var variadicArgs []connector.ExchangeName
		if len(args) > 2 {
			variadicArgs = args[2].([]connector.ExchangeName)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSpotMarket_Price_Call) Return(decimal numerical.Decimal, err error) *MockSpotMarket_Price_Call {
	_c.Call.Return(decimal, err)
	return _c
}

func (_c *MockSpotMarket_Price_Call) RunAndReturn(run func(ctx context.Context, asset portfolio.Pair, exchange ...connector.ExchangeName) (numerical.Decimal, error)) *MockSpotMarket_Price_Call {
	_c.Call.Return(run)
	return _c
}

// Prices provides a mock function for the type MockSpotMarket
func (_mock *MockSpotMarket) Prices(ctx context.Context, asset portfolio.Pair) map[connector.ExchangeName]numerical.Decimal {
	ret := _mock.Called(ctx, asset)

	if len(ret) == 0 {
		panic("no return value specified for Prices")
	}

	var r0 map[connector.ExchangeName]numerical.Decimal
	if returnFunc, ok := ret.Get(0).(func(context.Context, portfolio.Pair) map[connector.ExchangeName]numerical.Decimal); ok {
		r0 = returnFunc(ctx, asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[connector.ExchangeName]numerical.Decimal)
		}
	}
	return r0
}

// MockSpotMarket_Prices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prices'
type MockSpotMarket_Prices_Call struct {
	*mock.Call
}

// Prices is a helper method to define mock.On call
//   - ctx context.Context
//   - asset portfolio.Pair
func (_e *MockSpotMarket_Expecter) Prices(ctx interface{}, asset interface{}) *MockSpotMarket_Prices_Call {
	return &MockSpotMarket_Prices_Call{Call: _e.mock.On("Prices", ctx, asset)}
}

func (_c *MockSpotMarket_Prices_Call) Run(run func(ctx context.Context, asset portfolio.Pair)) *MockSpotMarket_Prices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 portfolio.Pair
		if args[1] != nil {
			arg1 = args[1].(portfolio.Pair)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSpotMarket_Prices_Call) Return(exchangeNameToDecimal map[connector.ExchangeName]numerical.Decimal) *MockSpotMarket_Prices_Call {
	_c.Call.Return(exchangeNameToDecimal)
	return _c
}

func (_c *MockSpotMarket_Prices_Call) RunAndReturn(run func(ctx context.Context, asset portfolio.Pair) map[connector.ExchangeName]numerical.Decimal) *MockSpotMarket_Prices_Call {
	_c.Call.Return(run)
	return _c
}
