// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/markets/base/types/ingestors/batch"
)

// NewSpotBatchIngestorFactory creates a new instance of SpotBatchIngestorFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpotBatchIngestorFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpotBatchIngestorFactory {
	mock := &SpotBatchIngestorFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SpotBatchIngestorFactory is an autogenerated mock type for the SpotBatchIngestorFactory type
type SpotBatchIngestorFactory struct {
	mock.Mock
}

type SpotBatchIngestorFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *SpotBatchIngestorFactory) EXPECT() *SpotBatchIngestorFactory_Expecter {
	return &SpotBatchIngestorFactory_Expecter{mock: &_m.Mock}
}

// CreateIngestors provides a mock function for the type SpotBatchIngestorFactory
func (_mock *SpotBatchIngestorFactory) CreateIngestors() []batch.BatchIngestor {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateIngestors")
	}

	var r0 []batch.BatchIngestor
	if returnFunc, ok := ret.Get(0).(func() []batch.BatchIngestor); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]batch.BatchIngestor)
		}
	}
	return r0
}

// SpotBatchIngestorFactory_CreateIngestors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngestors'
type SpotBatchIngestorFactory_CreateIngestors_Call struct {
	*mock.Call
}

// CreateIngestors is a helper method to define mock.On call
func (_e *SpotBatchIngestorFactory_Expecter) CreateIngestors() *SpotBatchIngestorFactory_CreateIngestors_Call {
	return &SpotBatchIngestorFactory_CreateIngestors_Call{Call: _e.mock.On("CreateIngestors")}
}

func (_c *SpotBatchIngestorFactory_CreateIngestors_Call) Run(run func()) *SpotBatchIngestorFactory_CreateIngestors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SpotBatchIngestorFactory_CreateIngestors_Call) Return(batchIngestors []batch.BatchIngestor) *SpotBatchIngestorFactory_CreateIngestors_Call {
	_c.Call.Return(batchIngestors)
	return _c
}

func (_c *SpotBatchIngestorFactory_CreateIngestors_Call) RunAndReturn(run func() []batch.BatchIngestor) *SpotBatchIngestorFactory_CreateIngestors_Call {
	_c.Call.Return(run)
	return _c
}
