// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/markets/base/types"
	"github.com/wisp-trading/sdk/pkg/types/connector"
	"github.com/wisp-trading/sdk/pkg/types/portfolio"
)

// NewMockSpotWatchlist creates a new instance of MockSpotWatchlist. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpotWatchlist(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpotWatchlist {
	mock := &MockSpotWatchlist{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSpotWatchlist is an autogenerated mock type for the SpotWatchlist type
type MockSpotWatchlist struct {
	mock.Mock
}

type MockSpotWatchlist_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpotWatchlist) EXPECT() *MockSpotWatchlist_Expecter {
	return &MockSpotWatchlist_Expecter{mock: &_m.Mock}
}

// GetRequiredPairs provides a mock function for the type MockSpotWatchlist
func (_mock *MockSpotWatchlist) GetRequiredPairs(exchange connector.ExchangeName) []portfolio.Pair {
	ret := _mock.Called(exchange)

	if len(ret) == 0 {
		panic("no return value specified for GetRequiredPairs")
	}

	var r0 []portfolio.Pair
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName) []portfolio.Pair); ok {
		r0 = returnFunc(exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]portfolio.Pair)
		}
	}
	return r0
}

// MockSpotWatchlist_GetRequiredPairs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequiredPairs'
type MockSpotWatchlist_GetRequiredPairs_Call struct {
	*mock.Call
}

// GetRequiredPairs is a helper method to define mock.On call
//   - exchange connector.ExchangeName
func (_e *MockSpotWatchlist_Expecter) GetRequiredPairs(exchange interface{}) *MockSpotWatchlist_GetRequiredPairs_Call {
	return &MockSpotWatchlist_GetRequiredPairs_Call{Call: _e.mock.On("GetRequiredPairs", exchange)}
}

func (_c *MockSpotWatchlist_GetRequiredPairs_Call) Run(run func(exchange connector.ExchangeName)) *MockSpotWatchlist_GetRequiredPairs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSpotWatchlist_GetRequiredPairs_Call) Return(pairs []portfolio.Pair) *MockSpotWatchlist_GetRequiredPairs_Call {
	_c.Call.Return(pairs)
	return _c
}

func (_c *MockSpotWatchlist_GetRequiredPairs_Call) RunAndReturn(run func(exchange connector.ExchangeName) []portfolio.Pair) *MockSpotWatchlist_GetRequiredPairs_Call {
	_c.Call.Return(run)
	return _c
}

// ReleasePair provides a mock function for the type MockSpotWatchlist
func (_mock *MockSpotWatchlist) ReleasePair(exchange connector.ExchangeName, pair portfolio.Pair) {
	_mock.Called(exchange, pair)
	return
}

// MockSpotWatchlist_ReleasePair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleasePair'
type MockSpotWatchlist_ReleasePair_Call struct {
	*mock.Call
}

// ReleasePair is a helper method to define mock.On call
//   - exchange connector.ExchangeName
//   - pair portfolio.Pair
func (_e *MockSpotWatchlist_Expecter) ReleasePair(exchange interface{}, pair interface{}) *MockSpotWatchlist_ReleasePair_Call {
	return &MockSpotWatchlist_ReleasePair_Call{Call: _e.mock.On("ReleasePair", exchange, pair)}
}

func (_c *MockSpotWatchlist_ReleasePair_Call) Run(run func(exchange connector.ExchangeName, pair portfolio.Pair)) *MockSpotWatchlist_ReleasePair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 portfolio.Pair
		if args[1] != nil {
			arg1 = args[1].(portfolio.Pair)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSpotWatchlist_ReleasePair_Call) Return() *MockSpotWatchlist_ReleasePair_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSpotWatchlist_ReleasePair_Call) RunAndReturn(run func(exchange connector.ExchangeName, pair portfolio.Pair)) *MockSpotWatchlist_ReleasePair_Call {
	_c.Run(run)
	return _c
}

// RequirePair provides a mock function for the type MockSpotWatchlist
func (_mock *MockSpotWatchlist) RequirePair(exchange connector.ExchangeName, pair portfolio.Pair) {
	_mock.Called(exchange, pair)
	return
}

// MockSpotWatchlist_RequirePair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequirePair'
type MockSpotWatchlist_RequirePair_Call struct {
	*mock.Call
}

// RequirePair is a helper method to define mock.On call
//   - exchange connector.ExchangeName
//   - pair portfolio.Pair
func (_e *MockSpotWatchlist_Expecter) RequirePair(exchange interface{}, pair interface{}) *MockSpotWatchlist_RequirePair_Call {
	return &MockSpotWatchlist_RequirePair_Call{Call: _e.mock.On("RequirePair", exchange, pair)}
}

func (_c *MockSpotWatchlist_RequirePair_Call) Run(run func(exchange connector.ExchangeName, pair portfolio.Pair)) *MockSpotWatchlist_RequirePair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 portfolio.Pair
		if args[1] != nil {
			arg1 = args[1].(portfolio.Pair)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSpotWatchlist_RequirePair_Call) Return() *MockSpotWatchlist_RequirePair_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSpotWatchlist_RequirePair_Call) RunAndReturn(run func(exchange connector.ExchangeName, pair portfolio.Pair)) *MockSpotWatchlist_RequirePair_Call {
	_c.Run(run)
	return _c
}

// Subscribe provides a mock function for the type MockSpotWatchlist
func (_mock *MockSpotWatchlist) Subscribe(exchange connector.ExchangeName) chan types.MarketWatchEvent {
	ret := _mock.Called(exchange)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 chan types.MarketWatchEvent
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName) chan types.MarketWatchEvent); ok {
		r0 = returnFunc(exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan types.MarketWatchEvent)
		}
	}
	return r0
}

// MockSpotWatchlist_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockSpotWatchlist_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - exchange connector.ExchangeName
func (_e *MockSpotWatchlist_Expecter) Subscribe(exchange interface{}) *MockSpotWatchlist_Subscribe_Call {
	return &MockSpotWatchlist_Subscribe_Call{Call: _e.mock.On("Subscribe", exchange)}
}

func (_c *MockSpotWatchlist_Subscribe_Call) Run(run func(exchange connector.ExchangeName)) *MockSpotWatchlist_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSpotWatchlist_Subscribe_Call) Return(marketWatchEventCh chan types.MarketWatchEvent) *MockSpotWatchlist_Subscribe_Call {
	_c.Call.Return(marketWatchEventCh)
	return _c
}

func (_c *MockSpotWatchlist_Subscribe_Call) RunAndReturn(run func(exchange connector.ExchangeName) chan types.MarketWatchEvent) *MockSpotWatchlist_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type MockSpotWatchlist
func (_mock *MockSpotWatchlist) Unsubscribe(exchange connector.ExchangeName) {
	_mock.Called(exchange)
	return
}

// MockSpotWatchlist_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockSpotWatchlist_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - exchange connector.ExchangeName
func (_e *MockSpotWatchlist_Expecter) Unsubscribe(exchange interface{}) *MockSpotWatchlist_Unsubscribe_Call {
	return &MockSpotWatchlist_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", exchange)}
}

func (_c *MockSpotWatchlist_Unsubscribe_Call) Run(run func(exchange connector.ExchangeName)) *MockSpotWatchlist_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSpotWatchlist_Unsubscribe_Call) Return() *MockSpotWatchlist_Unsubscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSpotWatchlist_Unsubscribe_Call) RunAndReturn(run func(exchange connector.ExchangeName)) *MockSpotWatchlist_Unsubscribe_Call {
	_c.Run(run)
	return _c
}
