// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package temporal

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/types/temporal"
)

// NewTimeProvider creates a new instance of TimeProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimeProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimeProvider {
	mock := &TimeProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TimeProvider is an autogenerated mock type for the TimeProvider type
type TimeProvider struct {
	mock.Mock
}

type TimeProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *TimeProvider) EXPECT() *TimeProvider_Expecter {
	return &TimeProvider_Expecter{mock: &_m.Mock}
}

// After provides a mock function for the type TimeProvider
func (_mock *TimeProvider) After(d time.Duration) <-chan time.Time {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for After")
	}

	var r0 <-chan time.Time
	if returnFunc, ok := ret.Get(0).(func(time.Duration) <-chan time.Time); ok {
		r0 = returnFunc(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan time.Time)
		}
	}
	return r0
}

// TimeProvider_After_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'After'
type TimeProvider_After_Call struct {
	*mock.Call
}

// After is a helper method to define mock.On call
//   - d time.Duration
func (_e *TimeProvider_Expecter) After(d interface{}) *TimeProvider_After_Call {
	return &TimeProvider_After_Call{Call: _e.mock.On("After", d)}
}

func (_c *TimeProvider_After_Call) Run(run func(d time.Duration)) *TimeProvider_After_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TimeProvider_After_Call) Return(timeCh <-chan time.Time) *TimeProvider_After_Call {
	_c.Call.Return(timeCh)
	return _c
}

func (_c *TimeProvider_After_Call) RunAndReturn(run func(d time.Duration) <-chan time.Time) *TimeProvider_After_Call {
	_c.Call.Return(run)
	return _c
}

// NewTicker provides a mock function for the type TimeProvider
func (_mock *TimeProvider) NewTicker(d time.Duration) temporal.Ticker {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for NewTicker")
	}

	var r0 temporal.Ticker
	if returnFunc, ok := ret.Get(0).(func(time.Duration) temporal.Ticker); ok {
		r0 = returnFunc(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(temporal.Ticker)
		}
	}
	return r0
}

// TimeProvider_NewTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTicker'
type TimeProvider_NewTicker_Call struct {
	*mock.Call
}

// NewTicker is a helper method to define mock.On call
//   - d time.Duration
func (_e *TimeProvider_Expecter) NewTicker(d interface{}) *TimeProvider_NewTicker_Call {
	return &TimeProvider_NewTicker_Call{Call: _e.mock.On("NewTicker", d)}
}

func (_c *TimeProvider_NewTicker_Call) Run(run func(d time.Duration)) *TimeProvider_NewTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TimeProvider_NewTicker_Call) Return(ticker temporal.Ticker) *TimeProvider_NewTicker_Call {
	_c.Call.Return(ticker)
	return _c
}

func (_c *TimeProvider_NewTicker_Call) RunAndReturn(run func(d time.Duration) temporal.Ticker) *TimeProvider_NewTicker_Call {
	_c.Call.Return(run)
	return _c
}

// NewTimer provides a mock function for the type TimeProvider
func (_mock *TimeProvider) NewTimer(d time.Duration) temporal.Timer {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for NewTimer")
	}

	var r0 temporal.Timer
	if returnFunc, ok := ret.Get(0).(func(time.Duration) temporal.Timer); ok {
		r0 = returnFunc(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(temporal.Timer)
		}
	}
	return r0
}

// TimeProvider_NewTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTimer'
type TimeProvider_NewTimer_Call struct {
	*mock.Call
}

// NewTimer is a helper method to define mock.On call
//   - d time.Duration
func (_e *TimeProvider_Expecter) NewTimer(d interface{}) *TimeProvider_NewTimer_Call {
	return &TimeProvider_NewTimer_Call{Call: _e.mock.On("NewTimer", d)}
}

func (_c *TimeProvider_NewTimer_Call) Run(run func(d time.Duration)) *TimeProvider_NewTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TimeProvider_NewTimer_Call) Return(timer temporal.Timer) *TimeProvider_NewTimer_Call {
	_c.Call.Return(timer)
	return _c
}

func (_c *TimeProvider_NewTimer_Call) RunAndReturn(run func(d time.Duration) temporal.Timer) *TimeProvider_NewTimer_Call {
	_c.Call.Return(run)
	return _c
}

// Now provides a mock function for the type TimeProvider
func (_mock *TimeProvider) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// TimeProvider_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type TimeProvider_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *TimeProvider_Expecter) Now() *TimeProvider_Now_Call {
	return &TimeProvider_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *TimeProvider_Now_Call) Run(run func()) *TimeProvider_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TimeProvider_Now_Call) Return(time1 time.Time) *TimeProvider_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *TimeProvider_Now_Call) RunAndReturn(run func() time.Time) *TimeProvider_Now_Call {
	_c.Call.Return(run)
	return _c
}

// Since provides a mock function for the type TimeProvider
func (_mock *TimeProvider) Since(t time.Time) time.Duration {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Since")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(time.Time) time.Duration); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// TimeProvider_Since_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Since'
type TimeProvider_Since_Call struct {
	*mock.Call
}

// Since is a helper method to define mock.On call
//   - t time.Time
func (_e *TimeProvider_Expecter) Since(t interface{}) *TimeProvider_Since_Call {
	return &TimeProvider_Since_Call{Call: _e.mock.On("Since", t)}
}

func (_c *TimeProvider_Since_Call) Run(run func(t time.Time)) *TimeProvider_Since_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TimeProvider_Since_Call) Return(duration time.Duration) *TimeProvider_Since_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *TimeProvider_Since_Call) RunAndReturn(run func(t time.Time) time.Duration) *TimeProvider_Since_Call {
	_c.Call.Return(run)
	return _c
}

// Sleep provides a mock function for the type TimeProvider
func (_mock *TimeProvider) Sleep(d time.Duration) {
	_mock.Called(d)
	return
}

// TimeProvider_Sleep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sleep'
type TimeProvider_Sleep_Call struct {
	*mock.Call
}

// Sleep is a helper method to define mock.On call
//   - d time.Duration
func (_e *TimeProvider_Expecter) Sleep(d interface{}) *TimeProvider_Sleep_Call {
	return &TimeProvider_Sleep_Call{Call: _e.mock.On("Sleep", d)}
}

func (_c *TimeProvider_Sleep_Call) Run(run func(d time.Duration)) *TimeProvider_Sleep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TimeProvider_Sleep_Call) Return() *TimeProvider_Sleep_Call {
	_c.Call.Return()
	return _c
}

func (_c *TimeProvider_Sleep_Call) RunAndReturn(run func(d time.Duration)) *TimeProvider_Sleep_Call {
	_c.Run(run)
	return _c
}
