// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package market

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/markets/base/types/stores/market"
	"github.com/wisp-trading/sdk/pkg/types/connector"
	"github.com/wisp-trading/sdk/pkg/types/portfolio"
)

// NewMarketStore creates a new instance of MarketStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketStore {
	mock := &MarketStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MarketStore is an autogenerated mock type for the MarketStore type
type MarketStore struct {
	mock.Mock
}

type MarketStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MarketStore) EXPECT() *MarketStore_Expecter {
	return &MarketStore_Expecter{mock: &_m.Mock}
}

// GetLastUpdated provides a mock function for the type MarketStore
func (_mock *MarketStore) GetLastUpdated() market.LastUpdatedMap {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastUpdated")
	}

	var r0 market.LastUpdatedMap
	if returnFunc, ok := ret.Get(0).(func() market.LastUpdatedMap); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(market.LastUpdatedMap)
		}
	}
	return r0
}

// MarketStore_GetLastUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastUpdated'
type MarketStore_GetLastUpdated_Call struct {
	*mock.Call
}

// GetLastUpdated is a helper method to define mock.On call
func (_e *MarketStore_Expecter) GetLastUpdated() *MarketStore_GetLastUpdated_Call {
	return &MarketStore_GetLastUpdated_Call{Call: _e.mock.On("GetLastUpdated")}
}

func (_c *MarketStore_GetLastUpdated_Call) Run(run func()) *MarketStore_GetLastUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketStore_GetLastUpdated_Call) Return(lastUpdatedMap market.LastUpdatedMap) *MarketStore_GetLastUpdated_Call {
	_c.Call.Return(lastUpdatedMap)
	return _c
}

func (_c *MarketStore_GetLastUpdated_Call) RunAndReturn(run func() market.LastUpdatedMap) *MarketStore_GetLastUpdated_Call {
	_c.Call.Return(run)
	return _c
}

// GetPairPrice provides a mock function for the type MarketStore
func (_mock *MarketStore) GetPairPrice(pair portfolio.Pair, exchange connector.ExchangeName) *connector.Price {
	ret := _mock.Called(pair, exchange)

	if len(ret) == 0 {
		panic("no return value specified for GetPairPrice")
	}

	var r0 *connector.Price
	if returnFunc, ok := ret.Get(0).(func(portfolio.Pair, connector.ExchangeName) *connector.Price); ok {
		r0 = returnFunc(pair, exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.Price)
		}
	}
	return r0
}

// MarketStore_GetPairPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPairPrice'
type MarketStore_GetPairPrice_Call struct {
	*mock.Call
}

// GetPairPrice is a helper method to define mock.On call
//   - pair portfolio.Pair
//   - exchange connector.ExchangeName
func (_e *MarketStore_Expecter) GetPairPrice(pair interface{}, exchange interface{}) *MarketStore_GetPairPrice_Call {
	return &MarketStore_GetPairPrice_Call{Call: _e.mock.On("GetPairPrice", pair, exchange)}
}

func (_c *MarketStore_GetPairPrice_Call) Run(run func(pair portfolio.Pair, exchange connector.ExchangeName)) *MarketStore_GetPairPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 portfolio.Pair
		if args[0] != nil {
			arg0 = args[0].(portfolio.Pair)
		}
		var arg1 connector.ExchangeName
		if args[1] != nil {
			arg1 = args[1].(connector.ExchangeName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MarketStore_GetPairPrice_Call) Return(price *connector.Price) *MarketStore_GetPairPrice_Call {
	_c.Call.Return(price)
	return _c
}

func (_c *MarketStore_GetPairPrice_Call) RunAndReturn(run func(pair portfolio.Pair, exchange connector.ExchangeName) *connector.Price) *MarketStore_GetPairPrice_Call {
	_c.Call.Return(run)
	return _c
}

// GetPairPrices provides a mock function for the type MarketStore
func (_mock *MarketStore) GetPairPrices(pair portfolio.Pair) market.PriceMap {
	ret := _mock.Called(pair)

	if len(ret) == 0 {
		panic("no return value specified for GetPairPrices")
	}

	var r0 market.PriceMap
	if returnFunc, ok := ret.Get(0).(func(portfolio.Pair) market.PriceMap); ok {
		r0 = returnFunc(pair)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(market.PriceMap)
		}
	}
	return r0
}

// MarketStore_GetPairPrices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPairPrices'
type MarketStore_GetPairPrices_Call struct {
	*mock.Call
}

// GetPairPrices is a helper method to define mock.On call
//   - pair portfolio.Pair
func (_e *MarketStore_Expecter) GetPairPrices(pair interface{}) *MarketStore_GetPairPrices_Call {
	return &MarketStore_GetPairPrices_Call{Call: _e.mock.On("GetPairPrices", pair)}
}

func (_c *MarketStore_GetPairPrices_Call) Run(run func(pair portfolio.Pair)) *MarketStore_GetPairPrices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 portfolio.Pair
		if args[0] != nil {
			arg0 = args[0].(portfolio.Pair)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MarketStore_GetPairPrices_Call) Return(priceMap market.PriceMap) *MarketStore_GetPairPrices_Call {
	_c.Call.Return(priceMap)
	return _c
}

func (_c *MarketStore_GetPairPrices_Call) RunAndReturn(run func(pair portfolio.Pair) market.PriceMap) *MarketStore_GetPairPrices_Call {
	_c.Call.Return(run)
	return _c
}

// MarketType provides a mock function for the type MarketStore
func (_mock *MarketStore) MarketType() connector.MarketType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MarketType")
	}

	var r0 connector.MarketType
	if returnFunc, ok := ret.Get(0).(func() connector.MarketType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(connector.MarketType)
	}
	return r0
}

// MarketStore_MarketType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarketType'
type MarketStore_MarketType_Call struct {
	*mock.Call
}

// MarketType is a helper method to define mock.On call
func (_e *MarketStore_Expecter) MarketType() *MarketStore_MarketType_Call {
	return &MarketStore_MarketType_Call{Call: _e.mock.On("MarketType")}
}

func (_c *MarketStore_MarketType_Call) Run(run func()) *MarketStore_MarketType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketStore_MarketType_Call) Return(marketType connector.MarketType) *MarketStore_MarketType_Call {
	_c.Call.Return(marketType)
	return _c
}

func (_c *MarketStore_MarketType_Call) RunAndReturn(run func() connector.MarketType) *MarketStore_MarketType_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastUpdated provides a mock function for the type MarketStore
func (_mock *MarketStore) UpdateLastUpdated(key market.UpdateKey) {
	_mock.Called(key)
	return
}

// MarketStore_UpdateLastUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastUpdated'
type MarketStore_UpdateLastUpdated_Call struct {
	*mock.Call
}

// UpdateLastUpdated is a helper method to define mock.On call
//   - key market.UpdateKey
func (_e *MarketStore_Expecter) UpdateLastUpdated(key interface{}) *MarketStore_UpdateLastUpdated_Call {
	return &MarketStore_UpdateLastUpdated_Call{Call: _e.mock.On("UpdateLastUpdated", key)}
}

func (_c *MarketStore_UpdateLastUpdated_Call) Run(run func(key market.UpdateKey)) *MarketStore_UpdateLastUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 market.UpdateKey
		if args[0] != nil {
			arg0 = args[0].(market.UpdateKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MarketStore_UpdateLastUpdated_Call) Return() *MarketStore_UpdateLastUpdated_Call {
	_c.Call.Return()
	return _c
}

func (_c *MarketStore_UpdateLastUpdated_Call) RunAndReturn(run func(key market.UpdateKey)) *MarketStore_UpdateLastUpdated_Call {
	_c.Run(run)
	return _c
}

// UpdatePairPrice provides a mock function for the type MarketStore
func (_mock *MarketStore) UpdatePairPrice(pair portfolio.Pair, exchange connector.ExchangeName, price connector.Price) {
	_mock.Called(pair, exchange, price)
	return
}

// MarketStore_UpdatePairPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePairPrice'
type MarketStore_UpdatePairPrice_Call struct {
	*mock.Call
}

// UpdatePairPrice is a helper method to define mock.On call
//   - pair portfolio.Pair
//   - exchange connector.ExchangeName
//   - price connector.Price
func (_e *MarketStore_Expecter) UpdatePairPrice(pair interface{}, exchange interface{}, price interface{}) *MarketStore_UpdatePairPrice_Call {
	return &MarketStore_UpdatePairPrice_Call{Call: _e.mock.On("UpdatePairPrice", pair, exchange, price)}
}

func (_c *MarketStore_UpdatePairPrice_Call) Run(run func(pair portfolio.Pair, exchange connector.ExchangeName, price connector.Price)) *MarketStore_UpdatePairPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 portfolio.Pair
		if args[0] != nil {
			arg0 = args[0].(portfolio.Pair)
		}
		var arg1 connector.ExchangeName
		if args[1] != nil {
			arg1 = args[1].(connector.ExchangeName)
		}
		var arg2 connector.Price
		if args[2] != nil {
			arg2 = args[2].(connector.Price)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MarketStore_UpdatePairPrice_Call) Return() *MarketStore_UpdatePairPrice_Call {
	_c.Call.Return()
	return _c
}

func (_c *MarketStore_UpdatePairPrice_Call) RunAndReturn(run func(pair portfolio.Pair, exchange connector.ExchangeName, price connector.Price)) *MarketStore_UpdatePairPrice_Call {
	_c.Run(run)
	return _c
}

// UpdatePairPrices provides a mock function for the type MarketStore
func (_mock *MarketStore) UpdatePairPrices(pair portfolio.Pair, prices market.PriceMap) {
	_mock.Called(pair, prices)
	return
}

// MarketStore_UpdatePairPrices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePairPrices'
type MarketStore_UpdatePairPrices_Call struct {
	*mock.Call
}

// UpdatePairPrices is a helper method to define mock.On call
//   - pair portfolio.Pair
//   - prices market.PriceMap
func (_e *MarketStore_Expecter) UpdatePairPrices(pair interface{}, prices interface{}) *MarketStore_UpdatePairPrices_Call {
	return &MarketStore_UpdatePairPrices_Call{Call: _e.mock.On("UpdatePairPrices", pair, prices)}
}

func (_c *MarketStore_UpdatePairPrices_Call) Run(run func(pair portfolio.Pair, prices market.PriceMap)) *MarketStore_UpdatePairPrices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 portfolio.Pair
		if args[0] != nil {
			arg0 = args[0].(portfolio.Pair)
		}
		var arg1 market.PriceMap
		if args[1] != nil {
			arg1 = args[1].(market.PriceMap)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MarketStore_UpdatePairPrices_Call) Return() *MarketStore_UpdatePairPrices_Call {
	_c.Call.Return()
	return _c
}

func (_c *MarketStore_UpdatePairPrices_Call) RunAndReturn(run func(pair portfolio.Pair, prices market.PriceMap)) *MarketStore_UpdatePairPrices_Call {
	_c.Run(run)
	return _c
}
