// Code generated by mockery v2.53.5. DO NOT EDIT.

package market

import (
	connector "github.com/wisp-trading/sdk/pkg/types/connector"

	mock "github.com/stretchr/testify/mock"

	portfolio "github.com/wisp-trading/sdk/pkg/types/portfolio"
)

// OrderBookWriter is an autogenerated mock type for the OrderBookWriter type
type OrderBookWriter struct {
	mock.Mock
}

type OrderBookWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderBookWriter) EXPECT() *OrderBookWriter_Expecter {
	return &OrderBookWriter_Expecter{mock: &_m.Mock}
}

// UpdateOrderBook provides a mock function with given fields: pair, exchange, orderBook
func (_m *OrderBookWriter) UpdateOrderBook(pair portfolio.Pair, exchange connector.ExchangeName, orderBook connector.OrderBook) {
	_m.Called(pair, exchange, orderBook)
}

// OrderBookWriter_UpdateOrderBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderBook'
type OrderBookWriter_UpdateOrderBook_Call struct {
	*mock.Call
}

// UpdateOrderBook is a helper method to define mock.On call
//   - pair portfolio.Pair
//   - exchange connector.ExchangeName
//   - orderBook connector.OrderBook
func (_e *OrderBookWriter_Expecter) UpdateOrderBook(pair interface{}, exchange interface{}, orderBook interface{}) *OrderBookWriter_UpdateOrderBook_Call {
	return &OrderBookWriter_UpdateOrderBook_Call{Call: _e.mock.On("UpdateOrderBook", pair, exchange, orderBook)}
}

func (_c *OrderBookWriter_UpdateOrderBook_Call) Run(run func(pair portfolio.Pair, exchange connector.ExchangeName, orderBook connector.OrderBook)) *OrderBookWriter_UpdateOrderBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Pair), args[1].(connector.ExchangeName), args[2].(connector.OrderBook))
	})
	return _c
}

func (_c *OrderBookWriter_UpdateOrderBook_Call) Return() *OrderBookWriter_UpdateOrderBook_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderBookWriter_UpdateOrderBook_Call) RunAndReturn(run func(portfolio.Pair, connector.ExchangeName, connector.OrderBook)) *OrderBookWriter_UpdateOrderBook_Call {
	_c.Run(run)
	return _c
}

// NewOrderBookWriter creates a new instance of OrderBookWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderBookWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderBookWriter {
	mock := &OrderBookWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
