// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package market

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/markets/base/types/stores/market"
	"github.com/wisp-trading/sdk/pkg/types/connector"
	"github.com/wisp-trading/sdk/pkg/types/portfolio"
	"github.com/wisp-trading/sdk/pkg/types/wisp/numerical"
)

// NewTradesStoreExtension creates a new instance of TradesStoreExtension. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTradesStoreExtension(t interface {
	mock.TestingT
	Cleanup(func())
}) *TradesStoreExtension {
	mock := &TradesStoreExtension{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TradesStoreExtension is an autogenerated mock type for the TradesStoreExtension type
type TradesStoreExtension struct {
	mock.Mock
}

type TradesStoreExtension_Expecter struct {
	mock *mock.Mock
}

func (_m *TradesStoreExtension) EXPECT() *TradesStoreExtension_Expecter {
	return &TradesStoreExtension_Expecter{mock: &_m.Mock}
}

// AddTrade provides a mock function for the type TradesStoreExtension
func (_mock *TradesStoreExtension) AddTrade(trade connector.Trade) {
	_mock.Called(trade)
	return
}

// TradesStoreExtension_AddTrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTrade'
type TradesStoreExtension_AddTrade_Call struct {
	*mock.Call
}

// AddTrade is a helper method to define mock.On call
//   - trade connector.Trade
func (_e *TradesStoreExtension_Expecter) AddTrade(trade interface{}) *TradesStoreExtension_AddTrade_Call {
	return &TradesStoreExtension_AddTrade_Call{Call: _e.mock.On("AddTrade", trade)}
}

func (_c *TradesStoreExtension_AddTrade_Call) Run(run func(trade connector.Trade)) *TradesStoreExtension_AddTrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.Trade
		if args[0] != nil {
			arg0 = args[0].(connector.Trade)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TradesStoreExtension_AddTrade_Call) Return() *TradesStoreExtension_AddTrade_Call {
	_c.Call.Return()
	return _c
}

func (_c *TradesStoreExtension_AddTrade_Call) RunAndReturn(run func(trade connector.Trade)) *TradesStoreExtension_AddTrade_Call {
	_c.Run(run)
	return _c
}

// AddTrades provides a mock function for the type TradesStoreExtension
func (_mock *TradesStoreExtension) AddTrades(trades []connector.Trade) {
	_mock.Called(trades)
	return
}

// TradesStoreExtension_AddTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTrades'
type TradesStoreExtension_AddTrades_Call struct {
	*mock.Call
}

// AddTrades is a helper method to define mock.On call
//   - trades []connector.Trade
func (_e *TradesStoreExtension_Expecter) AddTrades(trades interface{}) *TradesStoreExtension_AddTrades_Call {
	return &TradesStoreExtension_AddTrades_Call{Call: _e.mock.On("AddTrades", trades)}
}

func (_c *TradesStoreExtension_AddTrades_Call) Run(run func(trades []connector.Trade)) *TradesStoreExtension_AddTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []connector.Trade
		if args[0] != nil {
			arg0 = args[0].([]connector.Trade)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TradesStoreExtension_AddTrades_Call) Return() *TradesStoreExtension_AddTrades_Call {
	_c.Call.Return()
	return _c
}

func (_c *TradesStoreExtension_AddTrades_Call) RunAndReturn(run func(trades []connector.Trade)) *TradesStoreExtension_AddTrades_Call {
	_c.Run(run)
	return _c
}

// GetAllTrades provides a mock function for the type TradesStoreExtension
func (_mock *TradesStoreExtension) GetAllTrades() []connector.Trade {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllTrades")
	}

	var r0 []connector.Trade
	if returnFunc, ok := ret.Get(0).(func() []connector.Trade); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}
	return r0
}

// TradesStoreExtension_GetAllTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTrades'
type TradesStoreExtension_GetAllTrades_Call struct {
	*mock.Call
}

// GetAllTrades is a helper method to define mock.On call
func (_e *TradesStoreExtension_Expecter) GetAllTrades() *TradesStoreExtension_GetAllTrades_Call {
	return &TradesStoreExtension_GetAllTrades_Call{Call: _e.mock.On("GetAllTrades")}
}

func (_c *TradesStoreExtension_GetAllTrades_Call) Run(run func()) *TradesStoreExtension_GetAllTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TradesStoreExtension_GetAllTrades_Call) Return(trades []connector.Trade) *TradesStoreExtension_GetAllTrades_Call {
	_c.Call.Return(trades)
	return _c
}

func (_c *TradesStoreExtension_GetAllTrades_Call) RunAndReturn(run func() []connector.Trade) *TradesStoreExtension_GetAllTrades_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalVolume provides a mock function for the type TradesStoreExtension
func (_mock *TradesStoreExtension) GetTotalVolume(pair portfolio.Pair) numerical.Decimal {
	ret := _mock.Called(pair)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalVolume")
	}

	var r0 numerical.Decimal
	if returnFunc, ok := ret.Get(0).(func(portfolio.Pair) numerical.Decimal); ok {
		r0 = returnFunc(pair)
	} else {
		r0 = ret.Get(0).(numerical.Decimal)
	}
	return r0
}

// TradesStoreExtension_GetTotalVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalVolume'
type TradesStoreExtension_GetTotalVolume_Call struct {
	*mock.Call
}

// GetTotalVolume is a helper method to define mock.On call
//   - pair portfolio.Pair
func (_e *TradesStoreExtension_Expecter) GetTotalVolume(pair interface{}) *TradesStoreExtension_GetTotalVolume_Call {
	return &TradesStoreExtension_GetTotalVolume_Call{Call: _e.mock.On("GetTotalVolume", pair)}
}

func (_c *TradesStoreExtension_GetTotalVolume_Call) Run(run func(pair portfolio.Pair)) *TradesStoreExtension_GetTotalVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 portfolio.Pair
		if args[0] != nil {
			arg0 = args[0].(portfolio.Pair)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TradesStoreExtension_GetTotalVolume_Call) Return(decimal numerical.Decimal) *TradesStoreExtension_GetTotalVolume_Call {
	_c.Call.Return(decimal)
	return _c
}

func (_c *TradesStoreExtension_GetTotalVolume_Call) RunAndReturn(run func(pair portfolio.Pair) numerical.Decimal) *TradesStoreExtension_GetTotalVolume_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradeByID provides a mock function for the type TradesStoreExtension
func (_mock *TradesStoreExtension) GetTradeByID(tradeID string) *connector.Trade {
	ret := _mock.Called(tradeID)

	if len(ret) == 0 {
		panic("no return value specified for GetTradeByID")
	}

	var r0 *connector.Trade
	if returnFunc, ok := ret.Get(0).(func(string) *connector.Trade); ok {
		r0 = returnFunc(tradeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.Trade)
		}
	}
	return r0
}

// TradesStoreExtension_GetTradeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradeByID'
type TradesStoreExtension_GetTradeByID_Call struct {
	*mock.Call
}

// GetTradeByID is a helper method to define mock.On call
//   - tradeID string
func (_e *TradesStoreExtension_Expecter) GetTradeByID(tradeID interface{}) *TradesStoreExtension_GetTradeByID_Call {
	return &TradesStoreExtension_GetTradeByID_Call{Call: _e.mock.On("GetTradeByID", tradeID)}
}

func (_c *TradesStoreExtension_GetTradeByID_Call) Run(run func(tradeID string)) *TradesStoreExtension_GetTradeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TradesStoreExtension_GetTradeByID_Call) Return(trade *connector.Trade) *TradesStoreExtension_GetTradeByID_Call {
	_c.Call.Return(trade)
	return _c
}

func (_c *TradesStoreExtension_GetTradeByID_Call) RunAndReturn(run func(tradeID string) *connector.Trade) *TradesStoreExtension_GetTradeByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradeCount provides a mock function for the type TradesStoreExtension
func (_mock *TradesStoreExtension) GetTradeCount() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTradeCount")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// TradesStoreExtension_GetTradeCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradeCount'
type TradesStoreExtension_GetTradeCount_Call struct {
	*mock.Call
}

// GetTradeCount is a helper method to define mock.On call
func (_e *TradesStoreExtension_Expecter) GetTradeCount() *TradesStoreExtension_GetTradeCount_Call {
	return &TradesStoreExtension_GetTradeCount_Call{Call: _e.mock.On("GetTradeCount")}
}

func (_c *TradesStoreExtension_GetTradeCount_Call) Run(run func()) *TradesStoreExtension_GetTradeCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TradesStoreExtension_GetTradeCount_Call) Return(n int) *TradesStoreExtension_GetTradeCount_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *TradesStoreExtension_GetTradeCount_Call) RunAndReturn(run func() int) *TradesStoreExtension_GetTradeCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradesByExchange provides a mock function for the type TradesStoreExtension
func (_mock *TradesStoreExtension) GetTradesByExchange(exchange connector.ExchangeName) []connector.Trade {
	ret := _mock.Called(exchange)

	if len(ret) == 0 {
		panic("no return value specified for GetTradesByExchange")
	}

	var r0 []connector.Trade
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName) []connector.Trade); ok {
		r0 = returnFunc(exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}
	return r0
}

// TradesStoreExtension_GetTradesByExchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradesByExchange'
type TradesStoreExtension_GetTradesByExchange_Call struct {
	*mock.Call
}

// GetTradesByExchange is a helper method to define mock.On call
//   - exchange connector.ExchangeName
func (_e *TradesStoreExtension_Expecter) GetTradesByExchange(exchange interface{}) *TradesStoreExtension_GetTradesByExchange_Call {
	return &TradesStoreExtension_GetTradesByExchange_Call{Call: _e.mock.On("GetTradesByExchange", exchange)}
}

func (_c *TradesStoreExtension_GetTradesByExchange_Call) Run(run func(exchange connector.ExchangeName)) *TradesStoreExtension_GetTradesByExchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TradesStoreExtension_GetTradesByExchange_Call) Return(trades []connector.Trade) *TradesStoreExtension_GetTradesByExchange_Call {
	_c.Call.Return(trades)
	return _c
}

func (_c *TradesStoreExtension_GetTradesByExchange_Call) RunAndReturn(run func(exchange connector.ExchangeName) []connector.Trade) *TradesStoreExtension_GetTradesByExchange_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradesByPair provides a mock function for the type TradesStoreExtension
func (_mock *TradesStoreExtension) GetTradesByPair(pair portfolio.Pair) []connector.Trade {
	ret := _mock.Called(pair)

	if len(ret) == 0 {
		panic("no return value specified for GetTradesByPair")
	}

	var r0 []connector.Trade
	if returnFunc, ok := ret.Get(0).(func(portfolio.Pair) []connector.Trade); ok {
		r0 = returnFunc(pair)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}
	return r0
}

// TradesStoreExtension_GetTradesByPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradesByPair'
type TradesStoreExtension_GetTradesByPair_Call struct {
	*mock.Call
}

// GetTradesByPair is a helper method to define mock.On call
//   - pair portfolio.Pair
func (_e *TradesStoreExtension_Expecter) GetTradesByPair(pair interface{}) *TradesStoreExtension_GetTradesByPair_Call {
	return &TradesStoreExtension_GetTradesByPair_Call{Call: _e.mock.On("GetTradesByPair", pair)}
}

func (_c *TradesStoreExtension_GetTradesByPair_Call) Run(run func(pair portfolio.Pair)) *TradesStoreExtension_GetTradesByPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 portfolio.Pair
		if args[0] != nil {
			arg0 = args[0].(portfolio.Pair)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TradesStoreExtension_GetTradesByPair_Call) Return(trades []connector.Trade) *TradesStoreExtension_GetTradesByPair_Call {
	_c.Call.Return(trades)
	return _c
}

func (_c *TradesStoreExtension_GetTradesByPair_Call) RunAndReturn(run func(pair portfolio.Pair) []connector.Trade) *TradesStoreExtension_GetTradesByPair_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradesSince provides a mock function for the type TradesStoreExtension
func (_mock *TradesStoreExtension) GetTradesSince(since time.Time) []connector.Trade {
	ret := _mock.Called(since)

	if len(ret) == 0 {
		panic("no return value specified for GetTradesSince")
	}

	var r0 []connector.Trade
	if returnFunc, ok := ret.Get(0).(func(time.Time) []connector.Trade); ok {
		r0 = returnFunc(since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}
	return r0
}

// TradesStoreExtension_GetTradesSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradesSince'
type TradesStoreExtension_GetTradesSince_Call struct {
	*mock.Call
}

// GetTradesSince is a helper method to define mock.On call
//   - since time.Time
func (_e *TradesStoreExtension_Expecter) GetTradesSince(since interface{}) *TradesStoreExtension_GetTradesSince_Call {
	return &TradesStoreExtension_GetTradesSince_Call{Call: _e.mock.On("GetTradesSince", since)}
}

func (_c *TradesStoreExtension_GetTradesSince_Call) Run(run func(since time.Time)) *TradesStoreExtension_GetTradesSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TradesStoreExtension_GetTradesSince_Call) Return(trades []connector.Trade) *TradesStoreExtension_GetTradesSince_Call {
	_c.Call.Return(trades)
	return _c
}

func (_c *TradesStoreExtension_GetTradesSince_Call) RunAndReturn(run func(since time.Time) []connector.Trade) *TradesStoreExtension_GetTradesSince_Call {
	_c.Call.Return(run)
	return _c
}

// QueryTrades provides a mock function for the type TradesStoreExtension
func (_mock *TradesStoreExtension) QueryTrades(q market.ActivityQuery) []connector.Trade {
	ret := _mock.Called(q)

	if len(ret) == 0 {
		panic("no return value specified for QueryTrades")
	}

	var r0 []connector.Trade
	if returnFunc, ok := ret.Get(0).(func(market.ActivityQuery) []connector.Trade); ok {
		r0 = returnFunc(q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}
	return r0
}

// TradesStoreExtension_QueryTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryTrades'
type TradesStoreExtension_QueryTrades_Call struct {
	*mock.Call
}

// QueryTrades is a helper method to define mock.On call
//   - q market.ActivityQuery
func (_e *TradesStoreExtension_Expecter) QueryTrades(q interface{}) *TradesStoreExtension_QueryTrades_Call {
	return &TradesStoreExtension_QueryTrades_Call{Call: _e.mock.On("QueryTrades", q)}
}

func (_c *TradesStoreExtension_QueryTrades_Call) Run(run func(q market.ActivityQuery)) *TradesStoreExtension_QueryTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 market.ActivityQuery
		if args[0] != nil {
			arg0 = args[0].(market.ActivityQuery)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TradesStoreExtension_QueryTrades_Call) Return(trades []connector.Trade) *TradesStoreExtension_QueryTrades_Call {
	_c.Call.Return(trades)
	return _c
}

func (_c *TradesStoreExtension_QueryTrades_Call) RunAndReturn(run func(q market.ActivityQuery) []connector.Trade) *TradesStoreExtension_QueryTrades_Call {
	_c.Call.Return(run)
	return _c
}

// TradeExists provides a mock function for the type TradesStoreExtension
func (_mock *TradesStoreExtension) TradeExists(tradeID string) bool {
	ret := _mock.Called(tradeID)

	if len(ret) == 0 {
		panic("no return value specified for TradeExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(tradeID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// TradesStoreExtension_TradeExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TradeExists'
type TradesStoreExtension_TradeExists_Call struct {
	*mock.Call
}

// TradeExists is a helper method to define mock.On call
//   - tradeID string
func (_e *TradesStoreExtension_Expecter) TradeExists(tradeID interface{}) *TradesStoreExtension_TradeExists_Call {
	return &TradesStoreExtension_TradeExists_Call{Call: _e.mock.On("TradeExists", tradeID)}
}

func (_c *TradesStoreExtension_TradeExists_Call) Run(run func(tradeID string)) *TradesStoreExtension_TradeExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TradesStoreExtension_TradeExists_Call) Return(b bool) *TradesStoreExtension_TradeExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *TradesStoreExtension_TradeExists_Call) RunAndReturn(run func(tradeID string) bool) *TradesStoreExtension_TradeExists_Call {
	_c.Call.Return(run)
	return _c
}
