all: false
template: testify
filename: "{{.InterfaceName}}.go"
formatter: goimports
packages:
  github.com/wisp-trading/sdk/pkg/types/connector/options:
    config:
      all: true
      dir: "mocks/github.com/wisp-trading/sdk/pkg/types/connector/options"
