// Code generated by mockery v2.53.5. DO NOT EDIT.

package registry

import (
	mock "github.com/stretchr/testify/mock"
	execution "github.com/wisp-trading/wisp/pkg/types/execution"
)

// Hooks is an autogenerated mock type for the Hooks type
type Hooks struct {
	mock.Mock
}

type Hooks_Expecter struct {
	mock *mock.Mock
}

func (_m *Hooks) EXPECT() *Hooks_Expecter {
	return &Hooks_Expecter{mock: &_m.Mock}
}

// GetHooks provides a mock function with no fields
func (_m *Hooks) GetHooks() []execution.ExecutionHook {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHooks")
	}

	var r0 []execution.ExecutionHook
	if rf, ok := ret.Get(0).(func() []execution.ExecutionHook); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]execution.ExecutionHook)
		}
	}

	return r0
}

// Hooks_GetHooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHooks'
type Hooks_GetHooks_Call struct {
	*mock.Call
}

// GetHooks is a helper method to define mock.On call
func (_e *Hooks_Expecter) GetHooks() *Hooks_GetHooks_Call {
	return &Hooks_GetHooks_Call{Call: _e.mock.On("GetHooks")}
}

func (_c *Hooks_GetHooks_Call) Run(run func()) *Hooks_GetHooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Hooks_GetHooks_Call) Return(_a0 []execution.ExecutionHook) *Hooks_GetHooks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Hooks_GetHooks_Call) RunAndReturn(run func() []execution.ExecutionHook) *Hooks_GetHooks_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterHook provides a mock function with given fields: hook
func (_m *Hooks) RegisterHook(hook execution.ExecutionHook) {
	_m.Called(hook)
}

// Hooks_RegisterHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHook'
type Hooks_RegisterHook_Call struct {
	*mock.Call
}

// RegisterHook is a helper method to define mock.On call
//   - hook execution.ExecutionHook
func (_e *Hooks_Expecter) RegisterHook(hook interface{}) *Hooks_RegisterHook_Call {
	return &Hooks_RegisterHook_Call{Call: _e.mock.On("RegisterHook", hook)}
}

func (_c *Hooks_RegisterHook_Call) Run(run func(hook execution.ExecutionHook)) *Hooks_RegisterHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(execution.ExecutionHook))
	})
	return _c
}

func (_c *Hooks_RegisterHook_Call) Return() *Hooks_RegisterHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *Hooks_RegisterHook_Call) RunAndReturn(run func(execution.ExecutionHook)) *Hooks_RegisterHook_Call {
	_c.Run(run)
	return _c
}

// RegisterHooks provides a mock function with given fields: hooks
func (_m *Hooks) RegisterHooks(hooks []execution.ExecutionHook) {
	_m.Called(hooks)
}

// Hooks_RegisterHooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHooks'
type Hooks_RegisterHooks_Call struct {
	*mock.Call
}

// RegisterHooks is a helper method to define mock.On call
//   - hooks []execution.ExecutionHook
func (_e *Hooks_Expecter) RegisterHooks(hooks interface{}) *Hooks_RegisterHooks_Call {
	return &Hooks_RegisterHooks_Call{Call: _e.mock.On("RegisterHooks", hooks)}
}

func (_c *Hooks_RegisterHooks_Call) Run(run func(hooks []execution.ExecutionHook)) *Hooks_RegisterHooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]execution.ExecutionHook))
	})
	return _c
}

func (_c *Hooks_RegisterHooks_Call) Return() *Hooks_RegisterHooks_Call {
	_c.Call.Return()
	return _c
}

func (_c *Hooks_RegisterHooks_Call) RunAndReturn(run func([]execution.ExecutionHook)) *Hooks_RegisterHooks_Call {
	_c.Run(run)
	return _c
}

// NewHooks creates a new instance of Hooks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHooks(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hooks {
	mock := &Hooks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
