// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package health

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/types/connector"
	"github.com/wisp-trading/sdk/pkg/types/monitoring/health"
)

// NewCoordinatorHealthStore creates a new instance of CoordinatorHealthStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoordinatorHealthStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoordinatorHealthStore {
	mock := &CoordinatorHealthStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CoordinatorHealthStore is an autogenerated mock type for the CoordinatorHealthStore type
type CoordinatorHealthStore struct {
	mock.Mock
}

type CoordinatorHealthStore_Expecter struct {
	mock *mock.Mock
}

func (_m *CoordinatorHealthStore) EXPECT() *CoordinatorHealthStore_Expecter {
	return &CoordinatorHealthStore_Expecter{mock: &_m.Mock}
}

// GetAvailableDataTypes provides a mock function for the type CoordinatorHealthStore
func (_mock *CoordinatorHealthStore) GetAvailableDataTypes(name connector.ExchangeName) []health.DataType {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableDataTypes")
	}

	var r0 []health.DataType
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName) []health.DataType); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]health.DataType)
		}
	}
	return r0
}

// CoordinatorHealthStore_GetAvailableDataTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableDataTypes'
type CoordinatorHealthStore_GetAvailableDataTypes_Call struct {
	*mock.Call
}

// GetAvailableDataTypes is a helper method to define mock.On call
//   - name connector.ExchangeName
func (_e *CoordinatorHealthStore_Expecter) GetAvailableDataTypes(name interface{}) *CoordinatorHealthStore_GetAvailableDataTypes_Call {
	return &CoordinatorHealthStore_GetAvailableDataTypes_Call{Call: _e.mock.On("GetAvailableDataTypes", name)}
}

func (_c *CoordinatorHealthStore_GetAvailableDataTypes_Call) Run(run func(name connector.ExchangeName)) *CoordinatorHealthStore_GetAvailableDataTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CoordinatorHealthStore_GetAvailableDataTypes_Call) Return(dataTypes []health.DataType) *CoordinatorHealthStore_GetAvailableDataTypes_Call {
	_c.Call.Return(dataTypes)
	return _c
}

func (_c *CoordinatorHealthStore_GetAvailableDataTypes_Call) RunAndReturn(run func(name connector.ExchangeName) []health.DataType) *CoordinatorHealthStore_GetAvailableDataTypes_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectorDataHealth provides a mock function for the type CoordinatorHealthStore
func (_mock *CoordinatorHealthStore) GetConnectorDataHealth(name connector.ExchangeName) map[health.DataType]*health.DataTypeHealth {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectorDataHealth")
	}

	var r0 map[health.DataType]*health.DataTypeHealth
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName) map[health.DataType]*health.DataTypeHealth); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[health.DataType]*health.DataTypeHealth)
		}
	}
	return r0
}

// CoordinatorHealthStore_GetConnectorDataHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectorDataHealth'
type CoordinatorHealthStore_GetConnectorDataHealth_Call struct {
	*mock.Call
}

// GetConnectorDataHealth is a helper method to define mock.On call
//   - name connector.ExchangeName
func (_e *CoordinatorHealthStore_Expecter) GetConnectorDataHealth(name interface{}) *CoordinatorHealthStore_GetConnectorDataHealth_Call {
	return &CoordinatorHealthStore_GetConnectorDataHealth_Call{Call: _e.mock.On("GetConnectorDataHealth", name)}
}

func (_c *CoordinatorHealthStore_GetConnectorDataHealth_Call) Run(run func(name connector.ExchangeName)) *CoordinatorHealthStore_GetConnectorDataHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CoordinatorHealthStore_GetConnectorDataHealth_Call) Return(dataTypeToDataTypeHealth map[health.DataType]*health.DataTypeHealth) *CoordinatorHealthStore_GetConnectorDataHealth_Call {
	_c.Call.Return(dataTypeToDataTypeHealth)
	return _c
}

func (_c *CoordinatorHealthStore_GetConnectorDataHealth_Call) RunAndReturn(run func(name connector.ExchangeName) map[health.DataType]*health.DataTypeHealth) *CoordinatorHealthStore_GetConnectorDataHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetDegradedDataTypes provides a mock function for the type CoordinatorHealthStore
func (_mock *CoordinatorHealthStore) GetDegradedDataTypes() map[connector.ExchangeName][]health.DataType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDegradedDataTypes")
	}

	var r0 map[connector.ExchangeName][]health.DataType
	if returnFunc, ok := ret.Get(0).(func() map[connector.ExchangeName][]health.DataType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[connector.ExchangeName][]health.DataType)
		}
	}
	return r0
}

// CoordinatorHealthStore_GetDegradedDataTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDegradedDataTypes'
type CoordinatorHealthStore_GetDegradedDataTypes_Call struct {
	*mock.Call
}

// GetDegradedDataTypes is a helper method to define mock.On call
func (_e *CoordinatorHealthStore_Expecter) GetDegradedDataTypes() *CoordinatorHealthStore_GetDegradedDataTypes_Call {
	return &CoordinatorHealthStore_GetDegradedDataTypes_Call{Call: _e.mock.On("GetDegradedDataTypes")}
}

func (_c *CoordinatorHealthStore_GetDegradedDataTypes_Call) Run(run func()) *CoordinatorHealthStore_GetDegradedDataTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CoordinatorHealthStore_GetDegradedDataTypes_Call) Return(exchangeNameToDataTypes map[connector.ExchangeName][]health.DataType) *CoordinatorHealthStore_GetDegradedDataTypes_Call {
	_c.Call.Return(exchangeNameToDataTypes)
	return _c
}

func (_c *CoordinatorHealthStore_GetDegradedDataTypes_Call) RunAndReturn(run func() map[connector.ExchangeName][]health.DataType) *CoordinatorHealthStore_GetDegradedDataTypes_Call {
	_c.Call.Return(run)
	return _c
}

// GetErrorReport provides a mock function for the type CoordinatorHealthStore
func (_mock *CoordinatorHealthStore) GetErrorReport() *health.DataFlowErrorReport {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetErrorReport")
	}

	var r0 *health.DataFlowErrorReport
	if returnFunc, ok := ret.Get(0).(func() *health.DataFlowErrorReport); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*health.DataFlowErrorReport)
		}
	}
	return r0
}

// CoordinatorHealthStore_GetErrorReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetErrorReport'
type CoordinatorHealthStore_GetErrorReport_Call struct {
	*mock.Call
}

// GetErrorReport is a helper method to define mock.On call
func (_e *CoordinatorHealthStore_Expecter) GetErrorReport() *CoordinatorHealthStore_GetErrorReport_Call {
	return &CoordinatorHealthStore_GetErrorReport_Call{Call: _e.mock.On("GetErrorReport")}
}

func (_c *CoordinatorHealthStore_GetErrorReport_Call) Run(run func()) *CoordinatorHealthStore_GetErrorReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CoordinatorHealthStore_GetErrorReport_Call) Return(dataFlowErrorReport *health.DataFlowErrorReport) *CoordinatorHealthStore_GetErrorReport_Call {
	_c.Call.Return(dataFlowErrorReport)
	return _c
}

func (_c *CoordinatorHealthStore_GetErrorReport_Call) RunAndReturn(run func() *health.DataFlowErrorReport) *CoordinatorHealthStore_GetErrorReport_Call {
	_c.Call.Return(run)
	return _c
}

// HasReceivedData provides a mock function for the type CoordinatorHealthStore
func (_mock *CoordinatorHealthStore) HasReceivedData(name connector.ExchangeName, dataType health.DataType) bool {
	ret := _mock.Called(name, dataType)

	if len(ret) == 0 {
		panic("no return value specified for HasReceivedData")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName, health.DataType) bool); ok {
		r0 = returnFunc(name, dataType)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// CoordinatorHealthStore_HasReceivedData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasReceivedData'
type CoordinatorHealthStore_HasReceivedData_Call struct {
	*mock.Call
}

// HasReceivedData is a helper method to define mock.On call
//   - name connector.ExchangeName
//   - dataType health.DataType
func (_e *CoordinatorHealthStore_Expecter) HasReceivedData(name interface{}, dataType interface{}) *CoordinatorHealthStore_HasReceivedData_Call {
	return &CoordinatorHealthStore_HasReceivedData_Call{Call: _e.mock.On("HasReceivedData", name, dataType)}
}

func (_c *CoordinatorHealthStore_HasReceivedData_Call) Run(run func(name connector.ExchangeName, dataType health.DataType)) *CoordinatorHealthStore_HasReceivedData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 health.DataType
		if args[1] != nil {
			arg1 = args[1].(health.DataType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CoordinatorHealthStore_HasReceivedData_Call) Return(b bool) *CoordinatorHealthStore_HasReceivedData_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *CoordinatorHealthStore_HasReceivedData_Call) RunAndReturn(run func(name connector.ExchangeName, dataType health.DataType) bool) *CoordinatorHealthStore_HasReceivedData_Call {
	_c.Call.Return(run)
	return _c
}

// IsDataTypeHealthy provides a mock function for the type CoordinatorHealthStore
func (_mock *CoordinatorHealthStore) IsDataTypeHealthy(name connector.ExchangeName, dataType health.DataType) bool {
	ret := _mock.Called(name, dataType)

	if len(ret) == 0 {
		panic("no return value specified for IsDataTypeHealthy")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName, health.DataType) bool); ok {
		r0 = returnFunc(name, dataType)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// CoordinatorHealthStore_IsDataTypeHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDataTypeHealthy'
type CoordinatorHealthStore_IsDataTypeHealthy_Call struct {
	*mock.Call
}

// IsDataTypeHealthy is a helper method to define mock.On call
//   - name connector.ExchangeName
//   - dataType health.DataType
func (_e *CoordinatorHealthStore_Expecter) IsDataTypeHealthy(name interface{}, dataType interface{}) *CoordinatorHealthStore_IsDataTypeHealthy_Call {
	return &CoordinatorHealthStore_IsDataTypeHealthy_Call{Call: _e.mock.On("IsDataTypeHealthy", name, dataType)}
}

func (_c *CoordinatorHealthStore_IsDataTypeHealthy_Call) Run(run func(name connector.ExchangeName, dataType health.DataType)) *CoordinatorHealthStore_IsDataTypeHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 health.DataType
		if args[1] != nil {
			arg1 = args[1].(health.DataType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CoordinatorHealthStore_IsDataTypeHealthy_Call) Return(b bool) *CoordinatorHealthStore_IsDataTypeHealthy_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *CoordinatorHealthStore_IsDataTypeHealthy_Call) RunAndReturn(run func(name connector.ExchangeName, dataType health.DataType) bool) *CoordinatorHealthStore_IsDataTypeHealthy_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDataTypeAvailable provides a mock function for the type CoordinatorHealthStore
func (_mock *CoordinatorHealthStore) MarkDataTypeAvailable(name connector.ExchangeName, dataType health.DataType, available bool) {
	_mock.Called(name, dataType, available)
	return
}

// CoordinatorHealthStore_MarkDataTypeAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDataTypeAvailable'
type CoordinatorHealthStore_MarkDataTypeAvailable_Call struct {
	*mock.Call
}

// MarkDataTypeAvailable is a helper method to define mock.On call
//   - name connector.ExchangeName
//   - dataType health.DataType
//   - available bool
func (_e *CoordinatorHealthStore_Expecter) MarkDataTypeAvailable(name interface{}, dataType interface{}, available interface{}) *CoordinatorHealthStore_MarkDataTypeAvailable_Call {
	return &CoordinatorHealthStore_MarkDataTypeAvailable_Call{Call: _e.mock.On("MarkDataTypeAvailable", name, dataType, available)}
}

func (_c *CoordinatorHealthStore_MarkDataTypeAvailable_Call) Run(run func(name connector.ExchangeName, dataType health.DataType, available bool)) *CoordinatorHealthStore_MarkDataTypeAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 health.DataType
		if args[1] != nil {
			arg1 = args[1].(health.DataType)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CoordinatorHealthStore_MarkDataTypeAvailable_Call) Return() *CoordinatorHealthStore_MarkDataTypeAvailable_Call {
	_c.Call.Return()
	return _c
}

func (_c *CoordinatorHealthStore_MarkDataTypeAvailable_Call) RunAndReturn(run func(name connector.ExchangeName, dataType health.DataType, available bool)) *CoordinatorHealthStore_MarkDataTypeAvailable_Call {
	_c.Run(run)
	return _c
}

// RecordDataError provides a mock function for the type CoordinatorHealthStore
func (_mock *CoordinatorHealthStore) RecordDataError(name connector.ExchangeName, dataType health.DataType, err error) {
	_mock.Called(name, dataType, err)
	return
}

// CoordinatorHealthStore_RecordDataError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordDataError'
type CoordinatorHealthStore_RecordDataError_Call struct {
	*mock.Call
}

// RecordDataError is a helper method to define mock.On call
//   - name connector.ExchangeName
//   - dataType health.DataType
//   - err error
func (_e *CoordinatorHealthStore_Expecter) RecordDataError(name interface{}, dataType interface{}, err interface{}) *CoordinatorHealthStore_RecordDataError_Call {
	return &CoordinatorHealthStore_RecordDataError_Call{Call: _e.mock.On("RecordDataError", name, dataType, err)}
}

func (_c *CoordinatorHealthStore_RecordDataError_Call) Run(run func(name connector.ExchangeName, dataType health.DataType, err error)) *CoordinatorHealthStore_RecordDataError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 health.DataType
		if args[1] != nil {
			arg1 = args[1].(health.DataType)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CoordinatorHealthStore_RecordDataError_Call) Return() *CoordinatorHealthStore_RecordDataError_Call {
	_c.Call.Return()
	return _c
}

func (_c *CoordinatorHealthStore_RecordDataError_Call) RunAndReturn(run func(name connector.ExchangeName, dataType health.DataType, err error)) *CoordinatorHealthStore_RecordDataError_Call {
	_c.Run(run)
	return _c
}

// RecordDataReceived provides a mock function for the type CoordinatorHealthStore
func (_mock *CoordinatorHealthStore) RecordDataReceived(name connector.ExchangeName, dataType health.DataType, source health.DataSourceType, latency time.Duration) {
	_mock.Called(name, dataType, source, latency)
	return
}

// CoordinatorHealthStore_RecordDataReceived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordDataReceived'
type CoordinatorHealthStore_RecordDataReceived_Call struct {
	*mock.Call
}

// RecordDataReceived is a helper method to define mock.On call
//   - name connector.ExchangeName
//   - dataType health.DataType
//   - source health.DataSourceType
//   - latency time.Duration
func (_e *CoordinatorHealthStore_Expecter) RecordDataReceived(name interface{}, dataType interface{}, source interface{}, latency interface{}) *CoordinatorHealthStore_RecordDataReceived_Call {
	return &CoordinatorHealthStore_RecordDataReceived_Call{Call: _e.mock.On("RecordDataReceived", name, dataType, source, latency)}
}

func (_c *CoordinatorHealthStore_RecordDataReceived_Call) Run(run func(name connector.ExchangeName, dataType health.DataType, source health.DataSourceType, latency time.Duration)) *CoordinatorHealthStore_RecordDataReceived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 health.DataType
		if args[1] != nil {
			arg1 = args[1].(health.DataType)
		}
		var arg2 health.DataSourceType
		if args[2] != nil {
			arg2 = args[2].(health.DataSourceType)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CoordinatorHealthStore_RecordDataReceived_Call) Return() *CoordinatorHealthStore_RecordDataReceived_Call {
	_c.Call.Return()
	return _c
}

func (_c *CoordinatorHealthStore_RecordDataReceived_Call) RunAndReturn(run func(name connector.ExchangeName, dataType health.DataType, source health.DataSourceType, latency time.Duration)) *CoordinatorHealthStore_RecordDataReceived_Call {
	_c.Run(run)
	return _c
}

// WaitForFirstData provides a mock function for the type CoordinatorHealthStore
func (_mock *CoordinatorHealthStore) WaitForFirstData(name connector.ExchangeName, dataType health.DataType, timeout time.Duration) error {
	ret := _mock.Called(name, dataType, timeout)

	if len(ret) == 0 {
		panic("no return value specified for WaitForFirstData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName, health.DataType, time.Duration) error); ok {
		r0 = returnFunc(name, dataType, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CoordinatorHealthStore_WaitForFirstData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForFirstData'
type CoordinatorHealthStore_WaitForFirstData_Call struct {
	*mock.Call
}

// WaitForFirstData is a helper method to define mock.On call
//   - name connector.ExchangeName
//   - dataType health.DataType
//   - timeout time.Duration
func (_e *CoordinatorHealthStore_Expecter) WaitForFirstData(name interface{}, dataType interface{}, timeout interface{}) *CoordinatorHealthStore_WaitForFirstData_Call {
	return &CoordinatorHealthStore_WaitForFirstData_Call{Call: _e.mock.On("WaitForFirstData", name, dataType, timeout)}
}

func (_c *CoordinatorHealthStore_WaitForFirstData_Call) Run(run func(name connector.ExchangeName, dataType health.DataType, timeout time.Duration)) *CoordinatorHealthStore_WaitForFirstData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 health.DataType
		if args[1] != nil {
			arg1 = args[1].(health.DataType)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CoordinatorHealthStore_WaitForFirstData_Call) Return(err error) *CoordinatorHealthStore_WaitForFirstData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CoordinatorHealthStore_WaitForFirstData_Call) RunAndReturn(run func(name connector.ExchangeName, dataType health.DataType, timeout time.Duration) error) *CoordinatorHealthStore_WaitForFirstData_Call {
	_c.Call.Return(run)
	return _c
}
