// Code generated by mockery v2.53.5. DO NOT EDIT.

package perp

import (
	mock "github.com/stretchr/testify/mock"
	connector "github.com/wisp-trading/sdk/pkg/types/connector"

	numerical "github.com/wisp-trading/sdk/pkg/types/wisp/numerical"

	perp "github.com/wisp-trading/sdk/pkg/types/connector/perp"

	portfolio "github.com/wisp-trading/sdk/pkg/types/portfolio"
)

// Connector is an autogenerated mock type for the Connector type
type Connector struct {
	mock.Mock
}

type Connector_Expecter struct {
	mock *mock.Mock
}

func (_m *Connector) EXPECT() *Connector_Expecter {
	return &Connector_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: symbol, orderID
func (_m *Connector) CancelOrder(symbol string, orderID string) (*connector.CancelResponse, error) {
	ret := _m.Called(symbol, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 *connector.CancelResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*connector.CancelResponse, error)); ok {
		return rf(symbol, orderID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *connector.CancelResponse); ok {
		r0 = rf(symbol, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.CancelResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(symbol, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type Connector_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - symbol string
//   - orderID string
func (_e *Connector_Expecter) CancelOrder(symbol interface{}, orderID interface{}) *Connector_CancelOrder_Call {
	return &Connector_CancelOrder_Call{Call: _e.mock.On("CancelOrder", symbol, orderID)}
}

func (_c *Connector_CancelOrder_Call) Run(run func(symbol string, orderID string)) *Connector_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Connector_CancelOrder_Call) Return(_a0 *connector.CancelResponse, _a1 error) *Connector_CancelOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_CancelOrder_Call) RunAndReturn(run func(string, string) (*connector.CancelResponse, error)) *Connector_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// FetchContracts provides a mock function with no fields
func (_m *Connector) FetchContracts() ([]connector.ContractInfo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchContracts")
	}

	var r0 []connector.ContractInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]connector.ContractInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []connector.ContractInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.ContractInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_FetchContracts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchContracts'
type Connector_FetchContracts_Call struct {
	*mock.Call
}

// FetchContracts is a helper method to define mock.On call
func (_e *Connector_Expecter) FetchContracts() *Connector_FetchContracts_Call {
	return &Connector_FetchContracts_Call{Call: _e.mock.On("FetchContracts")}
}

func (_c *Connector_FetchContracts_Call) Run(run func()) *Connector_FetchContracts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connector_FetchContracts_Call) Return(_a0 []connector.ContractInfo, _a1 error) *Connector_FetchContracts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_FetchContracts_Call) RunAndReturn(run func() ([]connector.ContractInfo, error)) *Connector_FetchContracts_Call {
	_c.Call.Return(run)
	return _c
}

// FetchCurrentFundingRates provides a mock function with no fields
func (_m *Connector) FetchCurrentFundingRates() (map[portfolio.Asset]perp.FundingRate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchCurrentFundingRates")
	}

	var r0 map[portfolio.Asset]perp.FundingRate
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[portfolio.Asset]perp.FundingRate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[portfolio.Asset]perp.FundingRate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[portfolio.Asset]perp.FundingRate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_FetchCurrentFundingRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCurrentFundingRates'
type Connector_FetchCurrentFundingRates_Call struct {
	*mock.Call
}

// FetchCurrentFundingRates is a helper method to define mock.On call
func (_e *Connector_Expecter) FetchCurrentFundingRates() *Connector_FetchCurrentFundingRates_Call {
	return &Connector_FetchCurrentFundingRates_Call{Call: _e.mock.On("FetchCurrentFundingRates")}
}

func (_c *Connector_FetchCurrentFundingRates_Call) Run(run func()) *Connector_FetchCurrentFundingRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connector_FetchCurrentFundingRates_Call) Return(_a0 map[portfolio.Asset]perp.FundingRate, _a1 error) *Connector_FetchCurrentFundingRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_FetchCurrentFundingRates_Call) RunAndReturn(run func() (map[portfolio.Asset]perp.FundingRate, error)) *Connector_FetchCurrentFundingRates_Call {
	_c.Call.Return(run)
	return _c
}

// FetchFundingRate provides a mock function with given fields: asset
func (_m *Connector) FetchFundingRate(asset portfolio.Asset) (*perp.FundingRate, error) {
	ret := _m.Called(asset)

	if len(ret) == 0 {
		panic("no return value specified for FetchFundingRate")
	}

	var r0 *perp.FundingRate
	var r1 error
	if rf, ok := ret.Get(0).(func(portfolio.Asset) (*perp.FundingRate, error)); ok {
		return rf(asset)
	}
	if rf, ok := ret.Get(0).(func(portfolio.Asset) *perp.FundingRate); ok {
		r0 = rf(asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*perp.FundingRate)
		}
	}

	if rf, ok := ret.Get(1).(func(portfolio.Asset) error); ok {
		r1 = rf(asset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_FetchFundingRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchFundingRate'
type Connector_FetchFundingRate_Call struct {
	*mock.Call
}

// FetchFundingRate is a helper method to define mock.On call
//   - asset portfolio.Asset
func (_e *Connector_Expecter) FetchFundingRate(asset interface{}) *Connector_FetchFundingRate_Call {
	return &Connector_FetchFundingRate_Call{Call: _e.mock.On("FetchFundingRate", asset)}
}

func (_c *Connector_FetchFundingRate_Call) Run(run func(asset portfolio.Asset)) *Connector_FetchFundingRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Asset))
	})
	return _c
}

func (_c *Connector_FetchFundingRate_Call) Return(_a0 *perp.FundingRate, _a1 error) *Connector_FetchFundingRate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_FetchFundingRate_Call) RunAndReturn(run func(portfolio.Asset) (*perp.FundingRate, error)) *Connector_FetchFundingRate_Call {
	_c.Call.Return(run)
	return _c
}

// FetchHistoricalFundingRates provides a mock function with given fields: asset, startTime, endTime
func (_m *Connector) FetchHistoricalFundingRates(asset portfolio.Asset, startTime int64, endTime int64) ([]perp.HistoricalFundingRate, error) {
	ret := _m.Called(asset, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for FetchHistoricalFundingRates")
	}

	var r0 []perp.HistoricalFundingRate
	var r1 error
	if rf, ok := ret.Get(0).(func(portfolio.Asset, int64, int64) ([]perp.HistoricalFundingRate, error)); ok {
		return rf(asset, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(portfolio.Asset, int64, int64) []perp.HistoricalFundingRate); ok {
		r0 = rf(asset, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]perp.HistoricalFundingRate)
		}
	}

	if rf, ok := ret.Get(1).(func(portfolio.Asset, int64, int64) error); ok {
		r1 = rf(asset, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_FetchHistoricalFundingRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchHistoricalFundingRates'
type Connector_FetchHistoricalFundingRates_Call struct {
	*mock.Call
}

// FetchHistoricalFundingRates is a helper method to define mock.On call
//   - asset portfolio.Asset
//   - startTime int64
//   - endTime int64
func (_e *Connector_Expecter) FetchHistoricalFundingRates(asset interface{}, startTime interface{}, endTime interface{}) *Connector_FetchHistoricalFundingRates_Call {
	return &Connector_FetchHistoricalFundingRates_Call{Call: _e.mock.On("FetchHistoricalFundingRates", asset, startTime, endTime)}
}

func (_c *Connector_FetchHistoricalFundingRates_Call) Run(run func(asset portfolio.Asset, startTime int64, endTime int64)) *Connector_FetchHistoricalFundingRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Asset), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *Connector_FetchHistoricalFundingRates_Call) Return(_a0 []perp.HistoricalFundingRate, _a1 error) *Connector_FetchHistoricalFundingRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_FetchHistoricalFundingRates_Call) RunAndReturn(run func(portfolio.Asset, int64, int64) ([]perp.HistoricalFundingRate, error)) *Connector_FetchHistoricalFundingRates_Call {
	_c.Call.Return(run)
	return _c
}

// FetchKlines provides a mock function with given fields: symbol, interval, limit
func (_m *Connector) FetchKlines(symbol string, interval string, limit int) ([]connector.Kline, error) {
	ret := _m.Called(symbol, interval, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchKlines")
	}

	var r0 []connector.Kline
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int) ([]connector.Kline, error)); ok {
		return rf(symbol, interval, limit)
	}
	if rf, ok := ret.Get(0).(func(string, string, int) []connector.Kline); ok {
		r0 = rf(symbol, interval, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Kline)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = rf(symbol, interval, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_FetchKlines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchKlines'
type Connector_FetchKlines_Call struct {
	*mock.Call
}

// FetchKlines is a helper method to define mock.On call
//   - symbol string
//   - interval string
//   - limit int
func (_e *Connector_Expecter) FetchKlines(symbol interface{}, interval interface{}, limit interface{}) *Connector_FetchKlines_Call {
	return &Connector_FetchKlines_Call{Call: _e.mock.On("FetchKlines", symbol, interval, limit)}
}

func (_c *Connector_FetchKlines_Call) Run(run func(symbol string, interval string, limit int)) *Connector_FetchKlines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *Connector_FetchKlines_Call) Return(_a0 []connector.Kline, _a1 error) *Connector_FetchKlines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_FetchKlines_Call) RunAndReturn(run func(string, string, int) ([]connector.Kline, error)) *Connector_FetchKlines_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOrderBook provides a mock function with given fields: symbol, depth
func (_m *Connector) FetchOrderBook(symbol portfolio.Asset, depth int) (*connector.OrderBook, error) {
	ret := _m.Called(symbol, depth)

	if len(ret) == 0 {
		panic("no return value specified for FetchOrderBook")
	}

	var r0 *connector.OrderBook
	var r1 error
	if rf, ok := ret.Get(0).(func(portfolio.Asset, int) (*connector.OrderBook, error)); ok {
		return rf(symbol, depth)
	}
	if rf, ok := ret.Get(0).(func(portfolio.Asset, int) *connector.OrderBook); ok {
		r0 = rf(symbol, depth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.OrderBook)
		}
	}

	if rf, ok := ret.Get(1).(func(portfolio.Asset, int) error); ok {
		r1 = rf(symbol, depth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_FetchOrderBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOrderBook'
type Connector_FetchOrderBook_Call struct {
	*mock.Call
}

// FetchOrderBook is a helper method to define mock.On call
//   - symbol portfolio.Asset
//   - depth int
func (_e *Connector_Expecter) FetchOrderBook(symbol interface{}, depth interface{}) *Connector_FetchOrderBook_Call {
	return &Connector_FetchOrderBook_Call{Call: _e.mock.On("FetchOrderBook", symbol, depth)}
}

func (_c *Connector_FetchOrderBook_Call) Run(run func(symbol portfolio.Asset, depth int)) *Connector_FetchOrderBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Asset), args[1].(int))
	})
	return _c
}

func (_c *Connector_FetchOrderBook_Call) Return(_a0 *connector.OrderBook, _a1 error) *Connector_FetchOrderBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_FetchOrderBook_Call) RunAndReturn(run func(portfolio.Asset, int) (*connector.OrderBook, error)) *Connector_FetchOrderBook_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPrice provides a mock function with given fields: symbol
func (_m *Connector) FetchPrice(symbol string) (*connector.Price, error) {
	ret := _m.Called(symbol)

	if len(ret) == 0 {
		panic("no return value specified for FetchPrice")
	}

	var r0 *connector.Price
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*connector.Price, error)); ok {
		return rf(symbol)
	}
	if rf, ok := ret.Get(0).(func(string) *connector.Price); ok {
		r0 = rf(symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.Price)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_FetchPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPrice'
type Connector_FetchPrice_Call struct {
	*mock.Call
}

// FetchPrice is a helper method to define mock.On call
//   - symbol string
func (_e *Connector_Expecter) FetchPrice(symbol interface{}) *Connector_FetchPrice_Call {
	return &Connector_FetchPrice_Call{Call: _e.mock.On("FetchPrice", symbol)}
}

func (_c *Connector_FetchPrice_Call) Run(run func(symbol string)) *Connector_FetchPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Connector_FetchPrice_Call) Return(_a0 *connector.Price, _a1 error) *Connector_FetchPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_FetchPrice_Call) RunAndReturn(run func(string) (*connector.Price, error)) *Connector_FetchPrice_Call {
	_c.Call.Return(run)
	return _c
}

// FetchRecentTrades provides a mock function with given fields: symbol, limit
func (_m *Connector) FetchRecentTrades(symbol string, limit int) ([]connector.Trade, error) {
	ret := _m.Called(symbol, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchRecentTrades")
	}

	var r0 []connector.Trade
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]connector.Trade, error)); ok {
		return rf(symbol, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []connector.Trade); ok {
		r0 = rf(symbol, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(symbol, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_FetchRecentTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRecentTrades'
type Connector_FetchRecentTrades_Call struct {
	*mock.Call
}

// FetchRecentTrades is a helper method to define mock.On call
//   - symbol string
//   - limit int
func (_e *Connector_Expecter) FetchRecentTrades(symbol interface{}, limit interface{}) *Connector_FetchRecentTrades_Call {
	return &Connector_FetchRecentTrades_Call{Call: _e.mock.On("FetchRecentTrades", symbol, limit)}
}

func (_c *Connector_FetchRecentTrades_Call) Run(run func(symbol string, limit int)) *Connector_FetchRecentTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *Connector_FetchRecentTrades_Call) Return(_a0 []connector.Trade, _a1 error) *Connector_FetchRecentTrades_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_FetchRecentTrades_Call) RunAndReturn(run func(string, int) ([]connector.Trade, error)) *Connector_FetchRecentTrades_Call {
	_c.Call.Return(run)
	return _c
}

// FetchRiskFundBalance provides a mock function with given fields: symbol
func (_m *Connector) FetchRiskFundBalance(symbol string) (*connector.RiskFundBalance, error) {
	ret := _m.Called(symbol)

	if len(ret) == 0 {
		panic("no return value specified for FetchRiskFundBalance")
	}

	var r0 *connector.RiskFundBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*connector.RiskFundBalance, error)); ok {
		return rf(symbol)
	}
	if rf, ok := ret.Get(0).(func(string) *connector.RiskFundBalance); ok {
		r0 = rf(symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.RiskFundBalance)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_FetchRiskFundBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRiskFundBalance'
type Connector_FetchRiskFundBalance_Call struct {
	*mock.Call
}

// FetchRiskFundBalance is a helper method to define mock.On call
//   - symbol string
func (_e *Connector_Expecter) FetchRiskFundBalance(symbol interface{}) *Connector_FetchRiskFundBalance_Call {
	return &Connector_FetchRiskFundBalance_Call{Call: _e.mock.On("FetchRiskFundBalance", symbol)}
}

func (_c *Connector_FetchRiskFundBalance_Call) Run(run func(symbol string)) *Connector_FetchRiskFundBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Connector_FetchRiskFundBalance_Call) Return(_a0 *connector.RiskFundBalance, _a1 error) *Connector_FetchRiskFundBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_FetchRiskFundBalance_Call) RunAndReturn(run func(string) (*connector.RiskFundBalance, error)) *Connector_FetchRiskFundBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountBalance provides a mock function with no fields
func (_m *Connector) GetAccountBalance() (*connector.AccountBalance, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAccountBalance")
	}

	var r0 *connector.AccountBalance
	var r1 error
	if rf, ok := ret.Get(0).(func() (*connector.AccountBalance, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *connector.AccountBalance); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.AccountBalance)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_GetAccountBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountBalance'
type Connector_GetAccountBalance_Call struct {
	*mock.Call
}

// GetAccountBalance is a helper method to define mock.On call
func (_e *Connector_Expecter) GetAccountBalance() *Connector_GetAccountBalance_Call {
	return &Connector_GetAccountBalance_Call{Call: _e.mock.On("GetAccountBalance")}
}

func (_c *Connector_GetAccountBalance_Call) Run(run func()) *Connector_GetAccountBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connector_GetAccountBalance_Call) Return(_a0 *connector.AccountBalance, _a1 error) *Connector_GetAccountBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_GetAccountBalance_Call) RunAndReturn(run func() (*connector.AccountBalance, error)) *Connector_GetAccountBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectorInfo provides a mock function with no fields
func (_m *Connector) GetConnectorInfo() *connector.Info {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConnectorInfo")
	}

	var r0 *connector.Info
	if rf, ok := ret.Get(0).(func() *connector.Info); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.Info)
		}
	}

	return r0
}

// Connector_GetConnectorInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectorInfo'
type Connector_GetConnectorInfo_Call struct {
	*mock.Call
}

// GetConnectorInfo is a helper method to define mock.On call
func (_e *Connector_Expecter) GetConnectorInfo() *Connector_GetConnectorInfo_Call {
	return &Connector_GetConnectorInfo_Call{Call: _e.mock.On("GetConnectorInfo")}
}

func (_c *Connector_GetConnectorInfo_Call) Run(run func()) *Connector_GetConnectorInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connector_GetConnectorInfo_Call) Return(_a0 *connector.Info) *Connector_GetConnectorInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connector_GetConnectorInfo_Call) RunAndReturn(run func() *connector.Info) *Connector_GetConnectorInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetOpenOrders provides a mock function with no fields
func (_m *Connector) GetOpenOrders() ([]connector.Order, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOpenOrders")
	}

	var r0 []connector.Order
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]connector.Order, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []connector.Order); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Order)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_GetOpenOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOpenOrders'
type Connector_GetOpenOrders_Call struct {
	*mock.Call
}

// GetOpenOrders is a helper method to define mock.On call
func (_e *Connector_Expecter) GetOpenOrders() *Connector_GetOpenOrders_Call {
	return &Connector_GetOpenOrders_Call{Call: _e.mock.On("GetOpenOrders")}
}

func (_c *Connector_GetOpenOrders_Call) Run(run func()) *Connector_GetOpenOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connector_GetOpenOrders_Call) Return(_a0 []connector.Order, _a1 error) *Connector_GetOpenOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_GetOpenOrders_Call) RunAndReturn(run func() ([]connector.Order, error)) *Connector_GetOpenOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderStatus provides a mock function with given fields: orderID
func (_m *Connector) GetOrderStatus(orderID string) (*connector.Order, error) {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderStatus")
	}

	var r0 *connector.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*connector.Order, error)); ok {
		return rf(orderID)
	}
	if rf, ok := ret.Get(0).(func(string) *connector.Order); ok {
		r0 = rf(orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_GetOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderStatus'
type Connector_GetOrderStatus_Call struct {
	*mock.Call
}

// GetOrderStatus is a helper method to define mock.On call
//   - orderID string
func (_e *Connector_Expecter) GetOrderStatus(orderID interface{}) *Connector_GetOrderStatus_Call {
	return &Connector_GetOrderStatus_Call{Call: _e.mock.On("GetOrderStatus", orderID)}
}

func (_c *Connector_GetOrderStatus_Call) Run(run func(orderID string)) *Connector_GetOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Connector_GetOrderStatus_Call) Return(_a0 *connector.Order, _a1 error) *Connector_GetOrderStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_GetOrderStatus_Call) RunAndReturn(run func(string) (*connector.Order, error)) *Connector_GetOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetPerpSymbol provides a mock function with given fields: symbol
func (_m *Connector) GetPerpSymbol(symbol portfolio.Asset) string {
	ret := _m.Called(symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetPerpSymbol")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(portfolio.Asset) string); ok {
		r0 = rf(symbol)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Connector_GetPerpSymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPerpSymbol'
type Connector_GetPerpSymbol_Call struct {
	*mock.Call
}

// GetPerpSymbol is a helper method to define mock.On call
//   - symbol portfolio.Asset
func (_e *Connector_Expecter) GetPerpSymbol(symbol interface{}) *Connector_GetPerpSymbol_Call {
	return &Connector_GetPerpSymbol_Call{Call: _e.mock.On("GetPerpSymbol", symbol)}
}

func (_c *Connector_GetPerpSymbol_Call) Run(run func(symbol portfolio.Asset)) *Connector_GetPerpSymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Asset))
	})
	return _c
}

func (_c *Connector_GetPerpSymbol_Call) Return(_a0 string) *Connector_GetPerpSymbol_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connector_GetPerpSymbol_Call) RunAndReturn(run func(portfolio.Asset) string) *Connector_GetPerpSymbol_Call {
	_c.Call.Return(run)
	return _c
}

// GetPositions provides a mock function with no fields
func (_m *Connector) GetPositions() ([]connector.Position, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPositions")
	}

	var r0 []connector.Position
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]connector.Position, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []connector.Position); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Position)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_GetPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPositions'
type Connector_GetPositions_Call struct {
	*mock.Call
}

// GetPositions is a helper method to define mock.On call
func (_e *Connector_Expecter) GetPositions() *Connector_GetPositions_Call {
	return &Connector_GetPositions_Call{Call: _e.mock.On("GetPositions")}
}

func (_c *Connector_GetPositions_Call) Run(run func()) *Connector_GetPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connector_GetPositions_Call) Return(_a0 []connector.Position, _a1 error) *Connector_GetPositions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_GetPositions_Call) RunAndReturn(run func() ([]connector.Position, error)) *Connector_GetPositions_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradingHistory provides a mock function with given fields: symbol, limit
func (_m *Connector) GetTradingHistory(symbol string, limit int) ([]connector.Trade, error) {
	ret := _m.Called(symbol, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTradingHistory")
	}

	var r0 []connector.Trade
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]connector.Trade, error)); ok {
		return rf(symbol, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []connector.Trade); ok {
		r0 = rf(symbol, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(symbol, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_GetTradingHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradingHistory'
type Connector_GetTradingHistory_Call struct {
	*mock.Call
}

// GetTradingHistory is a helper method to define mock.On call
//   - symbol string
//   - limit int
func (_e *Connector_Expecter) GetTradingHistory(symbol interface{}, limit interface{}) *Connector_GetTradingHistory_Call {
	return &Connector_GetTradingHistory_Call{Call: _e.mock.On("GetTradingHistory", symbol, limit)}
}

func (_c *Connector_GetTradingHistory_Call) Run(run func(symbol string, limit int)) *Connector_GetTradingHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *Connector_GetTradingHistory_Call) Return(_a0 []connector.Trade, _a1 error) *Connector_GetTradingHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_GetTradingHistory_Call) RunAndReturn(run func(string, int) ([]connector.Trade, error)) *Connector_GetTradingHistory_Call {
	_c.Call.Return(run)
	return _c
}

// Initialize provides a mock function with given fields: config
func (_m *Connector) Initialize(config connector.Config) error {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(connector.Config) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connector_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type Connector_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - config connector.Config
func (_e *Connector_Expecter) Initialize(config interface{}) *Connector_Initialize_Call {
	return &Connector_Initialize_Call{Call: _e.mock.On("Initialize", config)}
}

func (_c *Connector_Initialize_Call) Run(run func(config connector.Config)) *Connector_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.Config))
	})
	return _c
}

func (_c *Connector_Initialize_Call) Return(_a0 error) *Connector_Initialize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connector_Initialize_Call) RunAndReturn(run func(connector.Config) error) *Connector_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// IsInitialized provides a mock function with no fields
func (_m *Connector) IsInitialized() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInitialized")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Connector_IsInitialized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInitialized'
type Connector_IsInitialized_Call struct {
	*mock.Call
}

// IsInitialized is a helper method to define mock.On call
func (_e *Connector_Expecter) IsInitialized() *Connector_IsInitialized_Call {
	return &Connector_IsInitialized_Call{Call: _e.mock.On("IsInitialized")}
}

func (_c *Connector_IsInitialized_Call) Run(run func()) *Connector_IsInitialized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connector_IsInitialized_Call) Return(_a0 bool) *Connector_IsInitialized_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connector_IsInitialized_Call) RunAndReturn(run func() bool) *Connector_IsInitialized_Call {
	_c.Call.Return(run)
	return _c
}

// NewConfig provides a mock function with no fields
func (_m *Connector) NewConfig() connector.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewConfig")
	}

	var r0 connector.Config
	if rf, ok := ret.Get(0).(func() connector.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(connector.Config)
		}
	}

	return r0
}

// Connector_NewConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewConfig'
type Connector_NewConfig_Call struct {
	*mock.Call
}

// NewConfig is a helper method to define mock.On call
func (_e *Connector_Expecter) NewConfig() *Connector_NewConfig_Call {
	return &Connector_NewConfig_Call{Call: _e.mock.On("NewConfig")}
}

func (_c *Connector_NewConfig_Call) Run(run func()) *Connector_NewConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connector_NewConfig_Call) Return(_a0 connector.Config) *Connector_NewConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connector_NewConfig_Call) RunAndReturn(run func() connector.Config) *Connector_NewConfig_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceLimitOrder provides a mock function with given fields: symbol, side, quantity, price
func (_m *Connector) PlaceLimitOrder(symbol string, side connector.OrderSide, quantity numerical.Decimal, price numerical.Decimal) (*connector.OrderResponse, error) {
	ret := _m.Called(symbol, side, quantity, price)

	if len(ret) == 0 {
		panic("no return value specified for PlaceLimitOrder")
	}

	var r0 *connector.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, connector.OrderSide, numerical.Decimal, numerical.Decimal) (*connector.OrderResponse, error)); ok {
		return rf(symbol, side, quantity, price)
	}
	if rf, ok := ret.Get(0).(func(string, connector.OrderSide, numerical.Decimal, numerical.Decimal) *connector.OrderResponse); ok {
		r0 = rf(symbol, side, quantity, price)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, connector.OrderSide, numerical.Decimal, numerical.Decimal) error); ok {
		r1 = rf(symbol, side, quantity, price)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_PlaceLimitOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceLimitOrder'
type Connector_PlaceLimitOrder_Call struct {
	*mock.Call
}

// PlaceLimitOrder is a helper method to define mock.On call
//   - symbol string
//   - side connector.OrderSide
//   - quantity numerical.Decimal
//   - price numerical.Decimal
func (_e *Connector_Expecter) PlaceLimitOrder(symbol interface{}, side interface{}, quantity interface{}, price interface{}) *Connector_PlaceLimitOrder_Call {
	return &Connector_PlaceLimitOrder_Call{Call: _e.mock.On("PlaceLimitOrder", symbol, side, quantity, price)}
}

func (_c *Connector_PlaceLimitOrder_Call) Run(run func(symbol string, side connector.OrderSide, quantity numerical.Decimal, price numerical.Decimal)) *Connector_PlaceLimitOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(connector.OrderSide), args[2].(numerical.Decimal), args[3].(numerical.Decimal))
	})
	return _c
}

func (_c *Connector_PlaceLimitOrder_Call) Return(_a0 *connector.OrderResponse, _a1 error) *Connector_PlaceLimitOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_PlaceLimitOrder_Call) RunAndReturn(run func(string, connector.OrderSide, numerical.Decimal, numerical.Decimal) (*connector.OrderResponse, error)) *Connector_PlaceLimitOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceMarketOrder provides a mock function with given fields: symbol, side, quantity
func (_m *Connector) PlaceMarketOrder(symbol string, side connector.OrderSide, quantity numerical.Decimal) (*connector.OrderResponse, error) {
	ret := _m.Called(symbol, side, quantity)

	if len(ret) == 0 {
		panic("no return value specified for PlaceMarketOrder")
	}

	var r0 *connector.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, connector.OrderSide, numerical.Decimal) (*connector.OrderResponse, error)); ok {
		return rf(symbol, side, quantity)
	}
	if rf, ok := ret.Get(0).(func(string, connector.OrderSide, numerical.Decimal) *connector.OrderResponse); ok {
		r0 = rf(symbol, side, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, connector.OrderSide, numerical.Decimal) error); ok {
		r1 = rf(symbol, side, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_PlaceMarketOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceMarketOrder'
type Connector_PlaceMarketOrder_Call struct {
	*mock.Call
}

// PlaceMarketOrder is a helper method to define mock.On call
//   - symbol string
//   - side connector.OrderSide
//   - quantity numerical.Decimal
func (_e *Connector_Expecter) PlaceMarketOrder(symbol interface{}, side interface{}, quantity interface{}) *Connector_PlaceMarketOrder_Call {
	return &Connector_PlaceMarketOrder_Call{Call: _e.mock.On("PlaceMarketOrder", symbol, side, quantity)}
}

func (_c *Connector_PlaceMarketOrder_Call) Run(run func(symbol string, side connector.OrderSide, quantity numerical.Decimal)) *Connector_PlaceMarketOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(connector.OrderSide), args[2].(numerical.Decimal))
	})
	return _c
}

func (_c *Connector_PlaceMarketOrder_Call) Return(_a0 *connector.OrderResponse, _a1 error) *Connector_PlaceMarketOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_PlaceMarketOrder_Call) RunAndReturn(run func(string, connector.OrderSide, numerical.Decimal) (*connector.OrderResponse, error)) *Connector_PlaceMarketOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsRealTimeData provides a mock function with no fields
func (_m *Connector) SupportsRealTimeData() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsRealTimeData")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Connector_SupportsRealTimeData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsRealTimeData'
type Connector_SupportsRealTimeData_Call struct {
	*mock.Call
}

// SupportsRealTimeData is a helper method to define mock.On call
func (_e *Connector_Expecter) SupportsRealTimeData() *Connector_SupportsRealTimeData_Call {
	return &Connector_SupportsRealTimeData_Call{Call: _e.mock.On("SupportsRealTimeData")}
}

func (_c *Connector_SupportsRealTimeData_Call) Run(run func()) *Connector_SupportsRealTimeData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connector_SupportsRealTimeData_Call) Return(_a0 bool) *Connector_SupportsRealTimeData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connector_SupportsRealTimeData_Call) RunAndReturn(run func() bool) *Connector_SupportsRealTimeData_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsTradingOperations provides a mock function with no fields
func (_m *Connector) SupportsTradingOperations() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsTradingOperations")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Connector_SupportsTradingOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsTradingOperations'
type Connector_SupportsTradingOperations_Call struct {
	*mock.Call
}

// SupportsTradingOperations is a helper method to define mock.On call
func (_e *Connector_Expecter) SupportsTradingOperations() *Connector_SupportsTradingOperations_Call {
	return &Connector_SupportsTradingOperations_Call{Call: _e.mock.On("SupportsTradingOperations")}
}

func (_c *Connector_SupportsTradingOperations_Call) Run(run func()) *Connector_SupportsTradingOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connector_SupportsTradingOperations_Call) Return(_a0 bool) *Connector_SupportsTradingOperations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connector_SupportsTradingOperations_Call) RunAndReturn(run func() bool) *Connector_SupportsTradingOperations_Call {
	_c.Call.Return(run)
	return _c
}

// NewConnector creates a new instance of Connector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Connector {
	mock := &Connector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
