// Code generated by mockery v2.53.5. DO NOT EDIT.

package plugin

import (
	mock "github.com/stretchr/testify/mock"
	plugin "github.com/wisp-trading/wisp/pkg/types/plugin"
)

// ParameterProvider is an autogenerated mock type for the ParameterProvider type
type ParameterProvider struct {
	mock.Mock
}

type ParameterProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ParameterProvider) EXPECT() *ParameterProvider_Expecter {
	return &ParameterProvider_Expecter{mock: &_m.Mock}
}

// GetParameters provides a mock function with no fields
func (_m *ParameterProvider) GetParameters() []plugin.ParameterDef {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetParameters")
	}

	var r0 []plugin.ParameterDef
	if rf, ok := ret.Get(0).(func() []plugin.ParameterDef); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]plugin.ParameterDef)
		}
	}

	return r0
}

// ParameterProvider_GetParameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParameters'
type ParameterProvider_GetParameters_Call struct {
	*mock.Call
}

// GetParameters is a helper method to define mock.On call
func (_e *ParameterProvider_Expecter) GetParameters() *ParameterProvider_GetParameters_Call {
	return &ParameterProvider_GetParameters_Call{Call: _e.mock.On("GetParameters")}
}

func (_c *ParameterProvider_GetParameters_Call) Run(run func()) *ParameterProvider_GetParameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ParameterProvider_GetParameters_Call) Return(_a0 []plugin.ParameterDef) *ParameterProvider_GetParameters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ParameterProvider_GetParameters_Call) RunAndReturn(run func() []plugin.ParameterDef) *ParameterProvider_GetParameters_Call {
	_c.Call.Return(run)
	return _c
}

// NewParameterProvider creates a new instance of ParameterProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParameterProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParameterProvider {
	mock := &ParameterProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
