// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package realtime

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/markets/base/types/ingestors/realtime"
)

// NewRealtimeIngestorFactory creates a new instance of RealtimeIngestorFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRealtimeIngestorFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *RealtimeIngestorFactory {
	mock := &RealtimeIngestorFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RealtimeIngestorFactory is an autogenerated mock type for the RealtimeIngestorFactory type
type RealtimeIngestorFactory struct {
	mock.Mock
}

type RealtimeIngestorFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *RealtimeIngestorFactory) EXPECT() *RealtimeIngestorFactory_Expecter {
	return &RealtimeIngestorFactory_Expecter{mock: &_m.Mock}
}

// CreateIngestors provides a mock function for the type RealtimeIngestorFactory
func (_mock *RealtimeIngestorFactory) CreateIngestors() []realtime.RealtimeIngestor {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateIngestors")
	}

	var r0 []realtime.RealtimeIngestor
	if returnFunc, ok := ret.Get(0).(func() []realtime.RealtimeIngestor); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]realtime.RealtimeIngestor)
		}
	}
	return r0
}

// RealtimeIngestorFactory_CreateIngestors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngestors'
type RealtimeIngestorFactory_CreateIngestors_Call struct {
	*mock.Call
}

// CreateIngestors is a helper method to define mock.On call
func (_e *RealtimeIngestorFactory_Expecter) CreateIngestors() *RealtimeIngestorFactory_CreateIngestors_Call {
	return &RealtimeIngestorFactory_CreateIngestors_Call{Call: _e.mock.On("CreateIngestors")}
}

func (_c *RealtimeIngestorFactory_CreateIngestors_Call) Run(run func()) *RealtimeIngestorFactory_CreateIngestors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RealtimeIngestorFactory_CreateIngestors_Call) Return(realtimeIngestors []realtime.RealtimeIngestor) *RealtimeIngestorFactory_CreateIngestors_Call {
	_c.Call.Return(realtimeIngestors)
	return _c
}

func (_c *RealtimeIngestorFactory_CreateIngestors_Call) RunAndReturn(run func() []realtime.RealtimeIngestor) *RealtimeIngestorFactory_CreateIngestors_Call {
	_c.Call.Return(run)
	return _c
}
