// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package realtime

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/types/connector"
)

// NewRealtimeIngestor creates a new instance of RealtimeIngestor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRealtimeIngestor(t interface {
	mock.TestingT
	Cleanup(func())
}) *RealtimeIngestor {
	mock := &RealtimeIngestor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RealtimeIngestor is an autogenerated mock type for the RealtimeIngestor type
type RealtimeIngestor struct {
	mock.Mock
}

type RealtimeIngestor_Expecter struct {
	mock *mock.Mock
}

func (_m *RealtimeIngestor) EXPECT() *RealtimeIngestor_Expecter {
	return &RealtimeIngestor_Expecter{mock: &_m.Mock}
}

// GetActiveConnections provides a mock function for the type RealtimeIngestor
func (_mock *RealtimeIngestor) GetActiveConnections() map[connector.ExchangeName]interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActiveConnections")
	}

	var r0 map[connector.ExchangeName]interface{}
	if returnFunc, ok := ret.Get(0).(func() map[connector.ExchangeName]interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[connector.ExchangeName]interface{})
		}
	}
	return r0
}

// RealtimeIngestor_GetActiveConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveConnections'
type RealtimeIngestor_GetActiveConnections_Call struct {
	*mock.Call
}

// GetActiveConnections is a helper method to define mock.On call
func (_e *RealtimeIngestor_Expecter) GetActiveConnections() *RealtimeIngestor_GetActiveConnections_Call {
	return &RealtimeIngestor_GetActiveConnections_Call{Call: _e.mock.On("GetActiveConnections")}
}

func (_c *RealtimeIngestor_GetActiveConnections_Call) Run(run func()) *RealtimeIngestor_GetActiveConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RealtimeIngestor_GetActiveConnections_Call) Return(exchangeNameToIfaceVal map[connector.ExchangeName]interface{}) *RealtimeIngestor_GetActiveConnections_Call {
	_c.Call.Return(exchangeNameToIfaceVal)
	return _c
}

func (_c *RealtimeIngestor_GetActiveConnections_Call) RunAndReturn(run func() map[connector.ExchangeName]interface{}) *RealtimeIngestor_GetActiveConnections_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarketType provides a mock function for the type RealtimeIngestor
func (_mock *RealtimeIngestor) GetMarketType() connector.MarketType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMarketType")
	}

	var r0 connector.MarketType
	if returnFunc, ok := ret.Get(0).(func() connector.MarketType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(connector.MarketType)
	}
	return r0
}

// RealtimeIngestor_GetMarketType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarketType'
type RealtimeIngestor_GetMarketType_Call struct {
	*mock.Call
}

// GetMarketType is a helper method to define mock.On call
func (_e *RealtimeIngestor_Expecter) GetMarketType() *RealtimeIngestor_GetMarketType_Call {
	return &RealtimeIngestor_GetMarketType_Call{Call: _e.mock.On("GetMarketType")}
}

func (_c *RealtimeIngestor_GetMarketType_Call) Run(run func()) *RealtimeIngestor_GetMarketType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RealtimeIngestor_GetMarketType_Call) Return(marketType connector.MarketType) *RealtimeIngestor_GetMarketType_Call {
	_c.Call.Return(marketType)
	return _c
}

func (_c *RealtimeIngestor_GetMarketType_Call) RunAndReturn(run func() connector.MarketType) *RealtimeIngestor_GetMarketType_Call {
	_c.Call.Return(run)
	return _c
}

// IsActive provides a mock function for the type RealtimeIngestor
func (_mock *RealtimeIngestor) IsActive() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsActive")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// RealtimeIngestor_IsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsActive'
type RealtimeIngestor_IsActive_Call struct {
	*mock.Call
}

// IsActive is a helper method to define mock.On call
func (_e *RealtimeIngestor_Expecter) IsActive() *RealtimeIngestor_IsActive_Call {
	return &RealtimeIngestor_IsActive_Call{Call: _e.mock.On("IsActive")}
}

func (_c *RealtimeIngestor_IsActive_Call) Run(run func()) *RealtimeIngestor_IsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RealtimeIngestor_IsActive_Call) Return(b bool) *RealtimeIngestor_IsActive_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *RealtimeIngestor_IsActive_Call) RunAndReturn(run func() bool) *RealtimeIngestor_IsActive_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type RealtimeIngestor
func (_mock *RealtimeIngestor) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RealtimeIngestor_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type RealtimeIngestor_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RealtimeIngestor_Expecter) Start(ctx interface{}) *RealtimeIngestor_Start_Call {
	return &RealtimeIngestor_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *RealtimeIngestor_Start_Call) Run(run func(ctx context.Context)) *RealtimeIngestor_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RealtimeIngestor_Start_Call) Return(err error) *RealtimeIngestor_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RealtimeIngestor_Start_Call) RunAndReturn(run func(ctx context.Context) error) *RealtimeIngestor_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type RealtimeIngestor
func (_mock *RealtimeIngestor) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RealtimeIngestor_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type RealtimeIngestor_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *RealtimeIngestor_Expecter) Stop() *RealtimeIngestor_Stop_Call {
	return &RealtimeIngestor_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *RealtimeIngestor_Stop_Call) Run(run func()) *RealtimeIngestor_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RealtimeIngestor_Stop_Call) Return(err error) *RealtimeIngestor_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RealtimeIngestor_Stop_Call) RunAndReturn(run func() error) *RealtimeIngestor_Stop_Call {
	_c.Call.Return(run)
	return _c
}
