// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package realtime

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/types/connector"
	"github.com/wisp-trading/sdk/pkg/types/portfolio"
)

// NewWebSocketExtension creates a new instance of WebSocketExtension. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebSocketExtension(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebSocketExtension {
	mock := &WebSocketExtension{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WebSocketExtension is an autogenerated mock type for the WebSocketExtension type
type WebSocketExtension struct {
	mock.Mock
}

type WebSocketExtension_Expecter struct {
	mock *mock.Mock
}

func (_m *WebSocketExtension) EXPECT() *WebSocketExtension_Expecter {
	return &WebSocketExtension_Expecter{mock: &_m.Mock}
}

// ProcessChannels provides a mock function for the type WebSocketExtension
func (_mock *WebSocketExtension) ProcessChannels(wsConn interface{}, exchangeName connector.ExchangeName, ctx context.Context) {
	_mock.Called(wsConn, exchangeName, ctx)
	return
}

// WebSocketExtension_ProcessChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessChannels'
type WebSocketExtension_ProcessChannels_Call struct {
	*mock.Call
}

// ProcessChannels is a helper method to define mock.On call
//   - wsConn interface{}
//   - exchangeName connector.ExchangeName
//   - ctx context.Context
func (_e *WebSocketExtension_Expecter) ProcessChannels(wsConn interface{}, exchangeName interface{}, ctx interface{}) *WebSocketExtension_ProcessChannels_Call {
	return &WebSocketExtension_ProcessChannels_Call{Call: _e.mock.On("ProcessChannels", wsConn, exchangeName, ctx)}
}

func (_c *WebSocketExtension_ProcessChannels_Call) Run(run func(wsConn interface{}, exchangeName connector.ExchangeName, ctx context.Context)) *WebSocketExtension_ProcessChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 connector.ExchangeName
		if args[1] != nil {
			arg1 = args[1].(connector.ExchangeName)
		}
		var arg2 context.Context
		if args[2] != nil {
			arg2 = args[2].(context.Context)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WebSocketExtension_ProcessChannels_Call) Return() *WebSocketExtension_ProcessChannels_Call {
	_c.Call.Return()
	return _c
}

func (_c *WebSocketExtension_ProcessChannels_Call) RunAndReturn(run func(wsConn interface{}, exchangeName connector.ExchangeName, ctx context.Context)) *WebSocketExtension_ProcessChannels_Call {
	_c.Run(run)
	return _c
}

// Subscribe provides a mock function for the type WebSocketExtension
func (_mock *WebSocketExtension) Subscribe(wsConn interface{}, exchangeName connector.ExchangeName, assets []portfolio.Pair) error {
	ret := _mock.Called(wsConn, exchangeName, assets)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, connector.ExchangeName, []portfolio.Pair) error); ok {
		r0 = returnFunc(wsConn, exchangeName, assets)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WebSocketExtension_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type WebSocketExtension_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - wsConn interface{}
//   - exchangeName connector.ExchangeName
//   - assets []portfolio.Pair
func (_e *WebSocketExtension_Expecter) Subscribe(wsConn interface{}, exchangeName interface{}, assets interface{}) *WebSocketExtension_Subscribe_Call {
	return &WebSocketExtension_Subscribe_Call{Call: _e.mock.On("Subscribe", wsConn, exchangeName, assets)}
}

func (_c *WebSocketExtension_Subscribe_Call) Run(run func(wsConn interface{}, exchangeName connector.ExchangeName, assets []portfolio.Pair)) *WebSocketExtension_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 connector.ExchangeName
		if args[1] != nil {
			arg1 = args[1].(connector.ExchangeName)
		}
		var arg2 []portfolio.Pair
		if args[2] != nil {
			arg2 = args[2].([]portfolio.Pair)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WebSocketExtension_Subscribe_Call) Return(err error) *WebSocketExtension_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WebSocketExtension_Subscribe_Call) RunAndReturn(run func(wsConn interface{}, exchangeName connector.ExchangeName, assets []portfolio.Pair) error) *WebSocketExtension_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type WebSocketExtension
func (_mock *WebSocketExtension) Unsubscribe(wsConn interface{}, exchangeName connector.ExchangeName) error {
	ret := _mock.Called(wsConn, exchangeName)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, connector.ExchangeName) error); ok {
		r0 = returnFunc(wsConn, exchangeName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WebSocketExtension_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type WebSocketExtension_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - wsConn interface{}
//   - exchangeName connector.ExchangeName
func (_e *WebSocketExtension_Expecter) Unsubscribe(wsConn interface{}, exchangeName interface{}) *WebSocketExtension_Unsubscribe_Call {
	return &WebSocketExtension_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", wsConn, exchangeName)}
}

func (_c *WebSocketExtension_Unsubscribe_Call) Run(run func(wsConn interface{}, exchangeName connector.ExchangeName)) *WebSocketExtension_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 connector.ExchangeName
		if args[1] != nil {
			arg1 = args[1].(connector.ExchangeName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WebSocketExtension_Unsubscribe_Call) Return(err error) *WebSocketExtension_Unsubscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WebSocketExtension_Unsubscribe_Call) RunAndReturn(run func(wsConn interface{}, exchangeName connector.ExchangeName) error) *WebSocketExtension_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}
