// Code generated by mockery v2.53.5. DO NOT EDIT.

package types

import (
	mock "github.com/stretchr/testify/mock"
	connector "github.com/wisp-trading/sdk/pkg/types/connector"

	perp "github.com/wisp-trading/sdk/pkg/types/connector/perp"

	portfolio "github.com/wisp-trading/sdk/pkg/types/portfolio"
)

// FundingRateStoreExtension is an autogenerated mock type for the FundingRateStoreExtension type
type FundingRateStoreExtension struct {
	mock.Mock
}

type FundingRateStoreExtension_Expecter struct {
	mock *mock.Mock
}

func (_m *FundingRateStoreExtension) EXPECT() *FundingRateStoreExtension_Expecter {
	return &FundingRateStoreExtension_Expecter{mock: &_m.Mock}
}

// GetAllAssetsWithFundingRates provides a mock function with no fields
func (_m *FundingRateStoreExtension) GetAllAssetsWithFundingRates() []portfolio.Pair {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllAssetsWithFundingRates")
	}

	var r0 []portfolio.Pair
	if rf, ok := ret.Get(0).(func() []portfolio.Pair); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]portfolio.Pair)
		}
	}

	return r0
}

// FundingRateStoreExtension_GetAllAssetsWithFundingRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAssetsWithFundingRates'
type FundingRateStoreExtension_GetAllAssetsWithFundingRates_Call struct {
	*mock.Call
}

// GetAllAssetsWithFundingRates is a helper method to define mock.On call
func (_e *FundingRateStoreExtension_Expecter) GetAllAssetsWithFundingRates() *FundingRateStoreExtension_GetAllAssetsWithFundingRates_Call {
	return &FundingRateStoreExtension_GetAllAssetsWithFundingRates_Call{Call: _e.mock.On("GetAllAssetsWithFundingRates")}
}

func (_c *FundingRateStoreExtension_GetAllAssetsWithFundingRates_Call) Run(run func()) *FundingRateStoreExtension_GetAllAssetsWithFundingRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FundingRateStoreExtension_GetAllAssetsWithFundingRates_Call) Return(_a0 []portfolio.Pair) *FundingRateStoreExtension_GetAllAssetsWithFundingRates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FundingRateStoreExtension_GetAllAssetsWithFundingRates_Call) RunAndReturn(run func() []portfolio.Pair) *FundingRateStoreExtension_GetAllAssetsWithFundingRates_Call {
	_c.Call.Return(run)
	return _c
}

// GetFundingRate provides a mock function with given fields: asset, exchange
func (_m *FundingRateStoreExtension) GetFundingRate(asset portfolio.Pair, exchange connector.ExchangeName) *perp.FundingRate {
	ret := _m.Called(asset, exchange)

	if len(ret) == 0 {
		panic("no return value specified for GetFundingRate")
	}

	var r0 *perp.FundingRate
	if rf, ok := ret.Get(0).(func(portfolio.Pair, connector.ExchangeName) *perp.FundingRate); ok {
		r0 = rf(asset, exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*perp.FundingRate)
		}
	}

	return r0
}

// FundingRateStoreExtension_GetFundingRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFundingRate'
type FundingRateStoreExtension_GetFundingRate_Call struct {
	*mock.Call
}

// GetFundingRate is a helper method to define mock.On call
//   - asset portfolio.Pair
//   - exchange connector.ExchangeName
func (_e *FundingRateStoreExtension_Expecter) GetFundingRate(asset interface{}, exchange interface{}) *FundingRateStoreExtension_GetFundingRate_Call {
	return &FundingRateStoreExtension_GetFundingRate_Call{Call: _e.mock.On("GetFundingRate", asset, exchange)}
}

func (_c *FundingRateStoreExtension_GetFundingRate_Call) Run(run func(asset portfolio.Pair, exchange connector.ExchangeName)) *FundingRateStoreExtension_GetFundingRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Pair), args[1].(connector.ExchangeName))
	})
	return _c
}

func (_c *FundingRateStoreExtension_GetFundingRate_Call) Return(_a0 *perp.FundingRate) *FundingRateStoreExtension_GetFundingRate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FundingRateStoreExtension_GetFundingRate_Call) RunAndReturn(run func(portfolio.Pair, connector.ExchangeName) *perp.FundingRate) *FundingRateStoreExtension_GetFundingRate_Call {
	_c.Call.Return(run)
	return _c
}

// GetFundingRatesForAsset provides a mock function with given fields: asset
func (_m *FundingRateStoreExtension) GetFundingRatesForAsset(asset portfolio.Pair) map[connector.ExchangeName]perp.FundingRate {
	ret := _m.Called(asset)

	if len(ret) == 0 {
		panic("no return value specified for GetFundingRatesForAsset")
	}

	var r0 map[connector.ExchangeName]perp.FundingRate
	if rf, ok := ret.Get(0).(func(portfolio.Pair) map[connector.ExchangeName]perp.FundingRate); ok {
		r0 = rf(asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[connector.ExchangeName]perp.FundingRate)
		}
	}

	return r0
}

// FundingRateStoreExtension_GetFundingRatesForAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFundingRatesForAsset'
type FundingRateStoreExtension_GetFundingRatesForAsset_Call struct {
	*mock.Call
}

// GetFundingRatesForAsset is a helper method to define mock.On call
//   - asset portfolio.Pair
func (_e *FundingRateStoreExtension_Expecter) GetFundingRatesForAsset(asset interface{}) *FundingRateStoreExtension_GetFundingRatesForAsset_Call {
	return &FundingRateStoreExtension_GetFundingRatesForAsset_Call{Call: _e.mock.On("GetFundingRatesForAsset", asset)}
}

func (_c *FundingRateStoreExtension_GetFundingRatesForAsset_Call) Run(run func(asset portfolio.Pair)) *FundingRateStoreExtension_GetFundingRatesForAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Pair))
	})
	return _c
}

func (_c *FundingRateStoreExtension_GetFundingRatesForAsset_Call) Return(_a0 map[connector.ExchangeName]perp.FundingRate) *FundingRateStoreExtension_GetFundingRatesForAsset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FundingRateStoreExtension_GetFundingRatesForAsset_Call) RunAndReturn(run func(portfolio.Pair) map[connector.ExchangeName]perp.FundingRate) *FundingRateStoreExtension_GetFundingRatesForAsset_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistoricalFundingRates provides a mock function with given fields: asset, exchange
func (_m *FundingRateStoreExtension) GetHistoricalFundingRates(asset portfolio.Pair, exchange connector.ExchangeName) []perp.HistoricalFundingRate {
	ret := _m.Called(asset, exchange)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoricalFundingRates")
	}

	var r0 []perp.HistoricalFundingRate
	if rf, ok := ret.Get(0).(func(portfolio.Pair, connector.ExchangeName) []perp.HistoricalFundingRate); ok {
		r0 = rf(asset, exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]perp.HistoricalFundingRate)
		}
	}

	return r0
}

// FundingRateStoreExtension_GetHistoricalFundingRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistoricalFundingRates'
type FundingRateStoreExtension_GetHistoricalFundingRates_Call struct {
	*mock.Call
}

// GetHistoricalFundingRates is a helper method to define mock.On call
//   - asset portfolio.Pair
//   - exchange connector.ExchangeName
func (_e *FundingRateStoreExtension_Expecter) GetHistoricalFundingRates(asset interface{}, exchange interface{}) *FundingRateStoreExtension_GetHistoricalFundingRates_Call {
	return &FundingRateStoreExtension_GetHistoricalFundingRates_Call{Call: _e.mock.On("GetHistoricalFundingRates", asset, exchange)}
}

func (_c *FundingRateStoreExtension_GetHistoricalFundingRates_Call) Run(run func(asset portfolio.Pair, exchange connector.ExchangeName)) *FundingRateStoreExtension_GetHistoricalFundingRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Pair), args[1].(connector.ExchangeName))
	})
	return _c
}

func (_c *FundingRateStoreExtension_GetHistoricalFundingRates_Call) Return(_a0 []perp.HistoricalFundingRate) *FundingRateStoreExtension_GetHistoricalFundingRates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FundingRateStoreExtension_GetHistoricalFundingRates_Call) RunAndReturn(run func(portfolio.Pair, connector.ExchangeName) []perp.HistoricalFundingRate) *FundingRateStoreExtension_GetHistoricalFundingRates_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistoricalFundingRatesForAsset provides a mock function with given fields: asset
func (_m *FundingRateStoreExtension) GetHistoricalFundingRatesForAsset(asset portfolio.Pair) map[connector.ExchangeName][]perp.HistoricalFundingRate {
	ret := _m.Called(asset)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoricalFundingRatesForAsset")
	}

	var r0 map[connector.ExchangeName][]perp.HistoricalFundingRate
	if rf, ok := ret.Get(0).(func(portfolio.Pair) map[connector.ExchangeName][]perp.HistoricalFundingRate); ok {
		r0 = rf(asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[connector.ExchangeName][]perp.HistoricalFundingRate)
		}
	}

	return r0
}

// FundingRateStoreExtension_GetHistoricalFundingRatesForAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistoricalFundingRatesForAsset'
type FundingRateStoreExtension_GetHistoricalFundingRatesForAsset_Call struct {
	*mock.Call
}

// GetHistoricalFundingRatesForAsset is a helper method to define mock.On call
//   - asset portfolio.Pair
func (_e *FundingRateStoreExtension_Expecter) GetHistoricalFundingRatesForAsset(asset interface{}) *FundingRateStoreExtension_GetHistoricalFundingRatesForAsset_Call {
	return &FundingRateStoreExtension_GetHistoricalFundingRatesForAsset_Call{Call: _e.mock.On("GetHistoricalFundingRatesForAsset", asset)}
}

func (_c *FundingRateStoreExtension_GetHistoricalFundingRatesForAsset_Call) Run(run func(asset portfolio.Pair)) *FundingRateStoreExtension_GetHistoricalFundingRatesForAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Pair))
	})
	return _c
}

func (_c *FundingRateStoreExtension_GetHistoricalFundingRatesForAsset_Call) Return(_a0 map[connector.ExchangeName][]perp.HistoricalFundingRate) *FundingRateStoreExtension_GetHistoricalFundingRatesForAsset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FundingRateStoreExtension_GetHistoricalFundingRatesForAsset_Call) RunAndReturn(run func(portfolio.Pair) map[connector.ExchangeName][]perp.HistoricalFundingRate) *FundingRateStoreExtension_GetHistoricalFundingRatesForAsset_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFundingRate provides a mock function with given fields: asset, exchange, rate
func (_m *FundingRateStoreExtension) UpdateFundingRate(asset portfolio.Pair, exchange connector.ExchangeName, rate perp.FundingRate) {
	_m.Called(asset, exchange, rate)
}

// FundingRateStoreExtension_UpdateFundingRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFundingRate'
type FundingRateStoreExtension_UpdateFundingRate_Call struct {
	*mock.Call
}

// UpdateFundingRate is a helper method to define mock.On call
//   - asset portfolio.Pair
//   - exchange connector.ExchangeName
//   - rate perp.FundingRate
func (_e *FundingRateStoreExtension_Expecter) UpdateFundingRate(asset interface{}, exchange interface{}, rate interface{}) *FundingRateStoreExtension_UpdateFundingRate_Call {
	return &FundingRateStoreExtension_UpdateFundingRate_Call{Call: _e.mock.On("UpdateFundingRate", asset, exchange, rate)}
}

func (_c *FundingRateStoreExtension_UpdateFundingRate_Call) Run(run func(asset portfolio.Pair, exchange connector.ExchangeName, rate perp.FundingRate)) *FundingRateStoreExtension_UpdateFundingRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Pair), args[1].(connector.ExchangeName), args[2].(perp.FundingRate))
	})
	return _c
}

func (_c *FundingRateStoreExtension_UpdateFundingRate_Call) Return() *FundingRateStoreExtension_UpdateFundingRate_Call {
	_c.Call.Return()
	return _c
}

func (_c *FundingRateStoreExtension_UpdateFundingRate_Call) RunAndReturn(run func(portfolio.Pair, connector.ExchangeName, perp.FundingRate)) *FundingRateStoreExtension_UpdateFundingRate_Call {
	_c.Run(run)
	return _c
}

// UpdateFundingRates provides a mock function with given fields: exchange, rates
func (_m *FundingRateStoreExtension) UpdateFundingRates(exchange connector.ExchangeName, rates map[portfolio.Pair]perp.FundingRate) {
	_m.Called(exchange, rates)
}

// FundingRateStoreExtension_UpdateFundingRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFundingRates'
type FundingRateStoreExtension_UpdateFundingRates_Call struct {
	*mock.Call
}

// UpdateFundingRates is a helper method to define mock.On call
//   - exchange connector.ExchangeName
//   - rates map[portfolio.Pair]perp.FundingRate
func (_e *FundingRateStoreExtension_Expecter) UpdateFundingRates(exchange interface{}, rates interface{}) *FundingRateStoreExtension_UpdateFundingRates_Call {
	return &FundingRateStoreExtension_UpdateFundingRates_Call{Call: _e.mock.On("UpdateFundingRates", exchange, rates)}
}

func (_c *FundingRateStoreExtension_UpdateFundingRates_Call) Run(run func(exchange connector.ExchangeName, rates map[portfolio.Pair]perp.FundingRate)) *FundingRateStoreExtension_UpdateFundingRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName), args[1].(map[portfolio.Pair]perp.FundingRate))
	})
	return _c
}

func (_c *FundingRateStoreExtension_UpdateFundingRates_Call) Return() *FundingRateStoreExtension_UpdateFundingRates_Call {
	_c.Call.Return()
	return _c
}

func (_c *FundingRateStoreExtension_UpdateFundingRates_Call) RunAndReturn(run func(connector.ExchangeName, map[portfolio.Pair]perp.FundingRate)) *FundingRateStoreExtension_UpdateFundingRates_Call {
	_c.Run(run)
	return _c
}

// UpdateHistoricalFundingRates provides a mock function with given fields: asset, exchange, rates
func (_m *FundingRateStoreExtension) UpdateHistoricalFundingRates(asset portfolio.Pair, exchange connector.ExchangeName, rates []perp.HistoricalFundingRate) {
	_m.Called(asset, exchange, rates)
}

// FundingRateStoreExtension_UpdateHistoricalFundingRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateHistoricalFundingRates'
type FundingRateStoreExtension_UpdateHistoricalFundingRates_Call struct {
	*mock.Call
}

// UpdateHistoricalFundingRates is a helper method to define mock.On call
//   - asset portfolio.Pair
//   - exchange connector.ExchangeName
//   - rates []perp.HistoricalFundingRate
func (_e *FundingRateStoreExtension_Expecter) UpdateHistoricalFundingRates(asset interface{}, exchange interface{}, rates interface{}) *FundingRateStoreExtension_UpdateHistoricalFundingRates_Call {
	return &FundingRateStoreExtension_UpdateHistoricalFundingRates_Call{Call: _e.mock.On("UpdateHistoricalFundingRates", asset, exchange, rates)}
}

func (_c *FundingRateStoreExtension_UpdateHistoricalFundingRates_Call) Run(run func(asset portfolio.Pair, exchange connector.ExchangeName, rates []perp.HistoricalFundingRate)) *FundingRateStoreExtension_UpdateHistoricalFundingRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Pair), args[1].(connector.ExchangeName), args[2].([]perp.HistoricalFundingRate))
	})
	return _c
}

func (_c *FundingRateStoreExtension_UpdateHistoricalFundingRates_Call) Return() *FundingRateStoreExtension_UpdateHistoricalFundingRates_Call {
	_c.Call.Return()
	return _c
}

func (_c *FundingRateStoreExtension_UpdateHistoricalFundingRates_Call) RunAndReturn(run func(portfolio.Pair, connector.ExchangeName, []perp.HistoricalFundingRate)) *FundingRateStoreExtension_UpdateHistoricalFundingRates_Call {
	_c.Run(run)
	return _c
}

// NewFundingRateStoreExtension creates a new instance of FundingRateStoreExtension. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFundingRateStoreExtension(t interface {
	mock.TestingT
	Cleanup(func())
}) *FundingRateStoreExtension {
	mock := &FundingRateStoreExtension{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
