// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/markets/perp/types"
)

// NewMockPerpUniverseProvider creates a new instance of MockPerpUniverseProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPerpUniverseProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPerpUniverseProvider {
	mock := &MockPerpUniverseProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPerpUniverseProvider is an autogenerated mock type for the PerpUniverseProvider type
type MockPerpUniverseProvider struct {
	mock.Mock
}

type MockPerpUniverseProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPerpUniverseProvider) EXPECT() *MockPerpUniverseProvider_Expecter {
	return &MockPerpUniverseProvider_Expecter{mock: &_m.Mock}
}

// Universe provides a mock function for the type MockPerpUniverseProvider
func (_mock *MockPerpUniverseProvider) Universe() types.PerpUniverse {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Universe")
	}

	var r0 types.PerpUniverse
	if returnFunc, ok := ret.Get(0).(func() types.PerpUniverse); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(types.PerpUniverse)
	}
	return r0
}

// MockPerpUniverseProvider_Universe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Universe'
type MockPerpUniverseProvider_Universe_Call struct {
	*mock.Call
}

// Universe is a helper method to define mock.On call
func (_e *MockPerpUniverseProvider_Expecter) Universe() *MockPerpUniverseProvider_Universe_Call {
	return &MockPerpUniverseProvider_Universe_Call{Call: _e.mock.On("Universe")}
}

func (_c *MockPerpUniverseProvider_Universe_Call) Run(run func()) *MockPerpUniverseProvider_Universe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPerpUniverseProvider_Universe_Call) Return(perpUniverse types.PerpUniverse) *MockPerpUniverseProvider_Universe_Call {
	_c.Call.Return(perpUniverse)
	return _c
}

func (_c *MockPerpUniverseProvider_Universe_Call) RunAndReturn(run func() types.PerpUniverse) *MockPerpUniverseProvider_Universe_Call {
	_c.Call.Return(run)
	return _c
}
