// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/types/connector"
	"github.com/wisp-trading/sdk/pkg/types/monitoring"
	"github.com/wisp-trading/sdk/pkg/types/portfolio"
)

// NewMockPerpViews creates a new instance of MockPerpViews. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPerpViews(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPerpViews {
	mock := &MockPerpViews{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPerpViews is an autogenerated mock type for the PerpViews type
type MockPerpViews struct {
	mock.Mock
}

type MockPerpViews_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPerpViews) EXPECT() *MockPerpViews_Expecter {
	return &MockPerpViews_Expecter{mock: &_m.Mock}
}

// GetKlines provides a mock function for the type MockPerpViews
func (_mock *MockPerpViews) GetKlines(exchange connector.ExchangeName, pair portfolio.Pair, interval string, limit int) []connector.Kline {
	ret := _mock.Called(exchange, pair, interval, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetKlines")
	}

	var r0 []connector.Kline
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName, portfolio.Pair, string, int) []connector.Kline); ok {
		r0 = returnFunc(exchange, pair, interval, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Kline)
		}
	}
	return r0
}

// MockPerpViews_GetKlines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKlines'
type MockPerpViews_GetKlines_Call struct {
	*mock.Call
}

// GetKlines is a helper method to define mock.On call
//   - exchange connector.ExchangeName
//   - pair portfolio.Pair
//   - interval string
//   - limit int
func (_e *MockPerpViews_Expecter) GetKlines(exchange interface{}, pair interface{}, interval interface{}, limit interface{}) *MockPerpViews_GetKlines_Call {
	return &MockPerpViews_GetKlines_Call{Call: _e.mock.On("GetKlines", exchange, pair, interval, limit)}
}

func (_c *MockPerpViews_GetKlines_Call) Run(run func(exchange connector.ExchangeName, pair portfolio.Pair, interval string, limit int)) *MockPerpViews_GetKlines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 portfolio.Pair
		if args[1] != nil {
			arg1 = args[1].(portfolio.Pair)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPerpViews_GetKlines_Call) Return(klines []connector.Kline) *MockPerpViews_GetKlines_Call {
	_c.Call.Return(klines)
	return _c
}

func (_c *MockPerpViews_GetKlines_Call) RunAndReturn(run func(exchange connector.ExchangeName, pair portfolio.Pair, interval string, limit int) []connector.Kline) *MockPerpViews_GetKlines_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarketViews provides a mock function for the type MockPerpViews
func (_mock *MockPerpViews) GetMarketViews() []monitoring.PerpMarketView {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMarketViews")
	}

	var r0 []monitoring.PerpMarketView
	if returnFunc, ok := ret.Get(0).(func() []monitoring.PerpMarketView); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]monitoring.PerpMarketView)
		}
	}
	return r0
}

// MockPerpViews_GetMarketViews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarketViews'
type MockPerpViews_GetMarketViews_Call struct {
	*mock.Call
}

// GetMarketViews is a helper method to define mock.On call
func (_e *MockPerpViews_Expecter) GetMarketViews() *MockPerpViews_GetMarketViews_Call {
	return &MockPerpViews_GetMarketViews_Call{Call: _e.mock.On("GetMarketViews")}
}

func (_c *MockPerpViews_GetMarketViews_Call) Run(run func()) *MockPerpViews_GetMarketViews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPerpViews_GetMarketViews_Call) Return(perpMarketViews []monitoring.PerpMarketView) *MockPerpViews_GetMarketViews_Call {
	_c.Call.Return(perpMarketViews)
	return _c
}

func (_c *MockPerpViews_GetMarketViews_Call) RunAndReturn(run func() []monitoring.PerpMarketView) *MockPerpViews_GetMarketViews_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderbook provides a mock function for the type MockPerpViews
func (_mock *MockPerpViews) GetOrderbook(exchange connector.ExchangeName, pair portfolio.Pair) *connector.OrderBook {
	ret := _mock.Called(exchange, pair)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderbook")
	}

	var r0 *connector.OrderBook
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName, portfolio.Pair) *connector.OrderBook); ok {
		r0 = returnFunc(exchange, pair)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.OrderBook)
		}
	}
	return r0
}

// MockPerpViews_GetOrderbook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderbook'
type MockPerpViews_GetOrderbook_Call struct {
	*mock.Call
}

// GetOrderbook is a helper method to define mock.On call
//   - exchange connector.ExchangeName
//   - pair portfolio.Pair
func (_e *MockPerpViews_Expecter) GetOrderbook(exchange interface{}, pair interface{}) *MockPerpViews_GetOrderbook_Call {
	return &MockPerpViews_GetOrderbook_Call{Call: _e.mock.On("GetOrderbook", exchange, pair)}
}

func (_c *MockPerpViews_GetOrderbook_Call) Run(run func(exchange connector.ExchangeName, pair portfolio.Pair)) *MockPerpViews_GetOrderbook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 portfolio.Pair
		if args[1] != nil {
			arg1 = args[1].(portfolio.Pair)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPerpViews_GetOrderbook_Call) Return(orderBook *connector.OrderBook) *MockPerpViews_GetOrderbook_Call {
	_c.Call.Return(orderBook)
	return _c
}

func (_c *MockPerpViews_GetOrderbook_Call) RunAndReturn(run func(exchange connector.ExchangeName, pair portfolio.Pair) *connector.OrderBook) *MockPerpViews_GetOrderbook_Call {
	_c.Call.Return(run)
	return _c
}
