// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/markets/base/types/stores/market"
	"github.com/wisp-trading/sdk/pkg/types/connector"
	"github.com/wisp-trading/sdk/pkg/types/connector/perp"
	"github.com/wisp-trading/sdk/pkg/types/portfolio"
)

// NewMockPerpPositionsStoreExtension creates a new instance of MockPerpPositionsStoreExtension. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPerpPositionsStoreExtension(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPerpPositionsStoreExtension {
	mock := &MockPerpPositionsStoreExtension{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPerpPositionsStoreExtension is an autogenerated mock type for the PerpPositionsStoreExtension type
type MockPerpPositionsStoreExtension struct {
	mock.Mock
}

type MockPerpPositionsStoreExtension_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPerpPositionsStoreExtension) EXPECT() *MockPerpPositionsStoreExtension_Expecter {
	return &MockPerpPositionsStoreExtension_Expecter{mock: &_m.Mock}
}

// GetPosition provides a mock function for the type MockPerpPositionsStoreExtension
func (_mock *MockPerpPositionsStoreExtension) GetPosition(exchange connector.ExchangeName, pair portfolio.Pair) *perp.Position {
	ret := _mock.Called(exchange, pair)

	if len(ret) == 0 {
		panic("no return value specified for GetPosition")
	}

	var r0 *perp.Position
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName, portfolio.Pair) *perp.Position); ok {
		r0 = returnFunc(exchange, pair)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*perp.Position)
		}
	}
	return r0
}

// MockPerpPositionsStoreExtension_GetPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPosition'
type MockPerpPositionsStoreExtension_GetPosition_Call struct {
	*mock.Call
}

// GetPosition is a helper method to define mock.On call
//   - exchange connector.ExchangeName
//   - pair portfolio.Pair
func (_e *MockPerpPositionsStoreExtension_Expecter) GetPosition(exchange interface{}, pair interface{}) *MockPerpPositionsStoreExtension_GetPosition_Call {
	return &MockPerpPositionsStoreExtension_GetPosition_Call{Call: _e.mock.On("GetPosition", exchange, pair)}
}

func (_c *MockPerpPositionsStoreExtension_GetPosition_Call) Run(run func(exchange connector.ExchangeName, pair portfolio.Pair)) *MockPerpPositionsStoreExtension_GetPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 portfolio.Pair
		if args[1] != nil {
			arg1 = args[1].(portfolio.Pair)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPerpPositionsStoreExtension_GetPosition_Call) Return(position *perp.Position) *MockPerpPositionsStoreExtension_GetPosition_Call {
	_c.Call.Return(position)
	return _c
}

func (_c *MockPerpPositionsStoreExtension_GetPosition_Call) RunAndReturn(run func(exchange connector.ExchangeName, pair portfolio.Pair) *perp.Position) *MockPerpPositionsStoreExtension_GetPosition_Call {
	_c.Call.Return(run)
	return _c
}

// GetPositions provides a mock function for the type MockPerpPositionsStoreExtension
func (_mock *MockPerpPositionsStoreExtension) GetPositions() []perp.Position {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPositions")
	}

	var r0 []perp.Position
	if returnFunc, ok := ret.Get(0).(func() []perp.Position); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]perp.Position)
		}
	}
	return r0
}

// MockPerpPositionsStoreExtension_GetPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPositions'
type MockPerpPositionsStoreExtension_GetPositions_Call struct {
	*mock.Call
}

// GetPositions is a helper method to define mock.On call
func (_e *MockPerpPositionsStoreExtension_Expecter) GetPositions() *MockPerpPositionsStoreExtension_GetPositions_Call {
	return &MockPerpPositionsStoreExtension_GetPositions_Call{Call: _e.mock.On("GetPositions")}
}

func (_c *MockPerpPositionsStoreExtension_GetPositions_Call) Run(run func()) *MockPerpPositionsStoreExtension_GetPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPerpPositionsStoreExtension_GetPositions_Call) Return(positions []perp.Position) *MockPerpPositionsStoreExtension_GetPositions_Call {
	_c.Call.Return(positions)
	return _c
}

func (_c *MockPerpPositionsStoreExtension_GetPositions_Call) RunAndReturn(run func() []perp.Position) *MockPerpPositionsStoreExtension_GetPositions_Call {
	_c.Call.Return(run)
	return _c
}

// QueryPositions provides a mock function for the type MockPerpPositionsStoreExtension
func (_mock *MockPerpPositionsStoreExtension) QueryPositions(q market.ActivityQuery) []perp.Position {
	ret := _mock.Called(q)

	if len(ret) == 0 {
		panic("no return value specified for QueryPositions")
	}

	var r0 []perp.Position
	if returnFunc, ok := ret.Get(0).(func(market.ActivityQuery) []perp.Position); ok {
		r0 = returnFunc(q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]perp.Position)
		}
	}
	return r0
}

// MockPerpPositionsStoreExtension_QueryPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryPositions'
type MockPerpPositionsStoreExtension_QueryPositions_Call struct {
	*mock.Call
}

// QueryPositions is a helper method to define mock.On call
//   - q market.ActivityQuery
func (_e *MockPerpPositionsStoreExtension_Expecter) QueryPositions(q interface{}) *MockPerpPositionsStoreExtension_QueryPositions_Call {
	return &MockPerpPositionsStoreExtension_QueryPositions_Call{Call: _e.mock.On("QueryPositions", q)}
}

func (_c *MockPerpPositionsStoreExtension_QueryPositions_Call) Run(run func(q market.ActivityQuery)) *MockPerpPositionsStoreExtension_QueryPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 market.ActivityQuery
		if args[0] != nil {
			arg0 = args[0].(market.ActivityQuery)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPerpPositionsStoreExtension_QueryPositions_Call) Return(positions []perp.Position) *MockPerpPositionsStoreExtension_QueryPositions_Call {
	_c.Call.Return(positions)
	return _c
}

func (_c *MockPerpPositionsStoreExtension_QueryPositions_Call) RunAndReturn(run func(q market.ActivityQuery) []perp.Position) *MockPerpPositionsStoreExtension_QueryPositions_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePosition provides a mock function for the type MockPerpPositionsStoreExtension
func (_mock *MockPerpPositionsStoreExtension) RemovePosition(exchange connector.ExchangeName, pair portfolio.Pair) {
	_mock.Called(exchange, pair)
	return
}

// MockPerpPositionsStoreExtension_RemovePosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePosition'
type MockPerpPositionsStoreExtension_RemovePosition_Call struct {
	*mock.Call
}

// RemovePosition is a helper method to define mock.On call
//   - exchange connector.ExchangeName
//   - pair portfolio.Pair
func (_e *MockPerpPositionsStoreExtension_Expecter) RemovePosition(exchange interface{}, pair interface{}) *MockPerpPositionsStoreExtension_RemovePosition_Call {
	return &MockPerpPositionsStoreExtension_RemovePosition_Call{Call: _e.mock.On("RemovePosition", exchange, pair)}
}

func (_c *MockPerpPositionsStoreExtension_RemovePosition_Call) Run(run func(exchange connector.ExchangeName, pair portfolio.Pair)) *MockPerpPositionsStoreExtension_RemovePosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 portfolio.Pair
		if args[1] != nil {
			arg1 = args[1].(portfolio.Pair)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPerpPositionsStoreExtension_RemovePosition_Call) Return() *MockPerpPositionsStoreExtension_RemovePosition_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPerpPositionsStoreExtension_RemovePosition_Call) RunAndReturn(run func(exchange connector.ExchangeName, pair portfolio.Pair)) *MockPerpPositionsStoreExtension_RemovePosition_Call {
	_c.Run(run)
	return _c
}

// UpsertPosition provides a mock function for the type MockPerpPositionsStoreExtension
func (_mock *MockPerpPositionsStoreExtension) UpsertPosition(position perp.Position) {
	_mock.Called(position)
	return
}

// MockPerpPositionsStoreExtension_UpsertPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPosition'
type MockPerpPositionsStoreExtension_UpsertPosition_Call struct {
	*mock.Call
}

// UpsertPosition is a helper method to define mock.On call
//   - position perp.Position
func (_e *MockPerpPositionsStoreExtension_Expecter) UpsertPosition(position interface{}) *MockPerpPositionsStoreExtension_UpsertPosition_Call {
	return &MockPerpPositionsStoreExtension_UpsertPosition_Call{Call: _e.mock.On("UpsertPosition", position)}
}

func (_c *MockPerpPositionsStoreExtension_UpsertPosition_Call) Run(run func(position perp.Position)) *MockPerpPositionsStoreExtension_UpsertPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 perp.Position
		if args[0] != nil {
			arg0 = args[0].(perp.Position)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPerpPositionsStoreExtension_UpsertPosition_Call) Return() *MockPerpPositionsStoreExtension_UpsertPosition_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPerpPositionsStoreExtension_UpsertPosition_Call) RunAndReturn(run func(position perp.Position)) *MockPerpPositionsStoreExtension_UpsertPosition_Call {
	_c.Run(run)
	return _c
}
