// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/markets/perp/types"
	"github.com/wisp-trading/sdk/pkg/types/wisp/numerical"
)

// NewPerpPNL creates a new instance of PerpPNL. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPerpPNL(t interface {
	mock.TestingT
	Cleanup(func())
}) *PerpPNL {
	mock := &PerpPNL{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PerpPNL is an autogenerated mock type for the PerpPNL type
type PerpPNL struct {
	mock.Mock
}

type PerpPNL_Expecter struct {
	mock *mock.Mock
}

func (_m *PerpPNL) EXPECT() *PerpPNL_Expecter {
	return &PerpPNL_Expecter{mock: &_m.Mock}
}

// Fees provides a mock function for the type PerpPNL
func (_mock *PerpPNL) Fees(ctx context.Context) numerical.Decimal {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Fees")
	}

	var r0 numerical.Decimal
	if returnFunc, ok := ret.Get(0).(func(context.Context) numerical.Decimal); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(numerical.Decimal)
	}
	return r0
}

// PerpPNL_Fees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fees'
type PerpPNL_Fees_Call struct {
	*mock.Call
}

// Fees is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PerpPNL_Expecter) Fees(ctx interface{}) *PerpPNL_Fees_Call {
	return &PerpPNL_Fees_Call{Call: _e.mock.On("Fees", ctx)}
}

func (_c *PerpPNL_Fees_Call) Run(run func(ctx context.Context)) *PerpPNL_Fees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PerpPNL_Fees_Call) Return(decimal numerical.Decimal) *PerpPNL_Fees_Call {
	_c.Call.Return(decimal)
	return _c
}

func (_c *PerpPNL_Fees_Call) RunAndReturn(run func(ctx context.Context) numerical.Decimal) *PerpPNL_Fees_Call {
	_c.Call.Return(run)
	return _c
}

// Positions provides a mock function for the type PerpPNL
func (_mock *PerpPNL) Positions(ctx context.Context) []types.PerpPositionPNL {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Positions")
	}

	var r0 []types.PerpPositionPNL
	if returnFunc, ok := ret.Get(0).(func(context.Context) []types.PerpPositionPNL); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.PerpPositionPNL)
		}
	}
	return r0
}

// PerpPNL_Positions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Positions'
type PerpPNL_Positions_Call struct {
	*mock.Call
}

// Positions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PerpPNL_Expecter) Positions(ctx interface{}) *PerpPNL_Positions_Call {
	return &PerpPNL_Positions_Call{Call: _e.mock.On("Positions", ctx)}
}

func (_c *PerpPNL_Positions_Call) Run(run func(ctx context.Context)) *PerpPNL_Positions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PerpPNL_Positions_Call) Return(perpPositionPNLs []types.PerpPositionPNL) *PerpPNL_Positions_Call {
	_c.Call.Return(perpPositionPNLs)
	return _c
}

func (_c *PerpPNL_Positions_Call) RunAndReturn(run func(ctx context.Context) []types.PerpPositionPNL) *PerpPNL_Positions_Call {
	_c.Call.Return(run)
	return _c
}

// Realized provides a mock function for the type PerpPNL
func (_mock *PerpPNL) Realized(ctx context.Context) numerical.Decimal {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Realized")
	}

	var r0 numerical.Decimal
	if returnFunc, ok := ret.Get(0).(func(context.Context) numerical.Decimal); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(numerical.Decimal)
	}
	return r0
}

// PerpPNL_Realized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Realized'
type PerpPNL_Realized_Call struct {
	*mock.Call
}

// Realized is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PerpPNL_Expecter) Realized(ctx interface{}) *PerpPNL_Realized_Call {
	return &PerpPNL_Realized_Call{Call: _e.mock.On("Realized", ctx)}
}

func (_c *PerpPNL_Realized_Call) Run(run func(ctx context.Context)) *PerpPNL_Realized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PerpPNL_Realized_Call) Return(decimal numerical.Decimal) *PerpPNL_Realized_Call {
	_c.Call.Return(decimal)
	return _c
}

func (_c *PerpPNL_Realized_Call) RunAndReturn(run func(ctx context.Context) numerical.Decimal) *PerpPNL_Realized_Call {
	_c.Call.Return(run)
	return _c
}

// Unrealized provides a mock function for the type PerpPNL
func (_mock *PerpPNL) Unrealized(ctx context.Context) numerical.Decimal {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Unrealized")
	}

	var r0 numerical.Decimal
	if returnFunc, ok := ret.Get(0).(func(context.Context) numerical.Decimal); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(numerical.Decimal)
	}
	return r0
}

// PerpPNL_Unrealized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unrealized'
type PerpPNL_Unrealized_Call struct {
	*mock.Call
}

// Unrealized is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PerpPNL_Expecter) Unrealized(ctx interface{}) *PerpPNL_Unrealized_Call {
	return &PerpPNL_Unrealized_Call{Call: _e.mock.On("Unrealized", ctx)}
}

func (_c *PerpPNL_Unrealized_Call) Run(run func(ctx context.Context)) *PerpPNL_Unrealized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PerpPNL_Unrealized_Call) Return(decimal numerical.Decimal) *PerpPNL_Unrealized_Call {
	_c.Call.Return(decimal)
	return _c
}

func (_c *PerpPNL_Unrealized_Call) RunAndReturn(run func(ctx context.Context) numerical.Decimal) *PerpPNL_Unrealized_Call {
	_c.Call.Return(run)
	return _c
}
