// Code generated by mockery v2.53.5. DO NOT EDIT.

package registry

import (
	mock "github.com/stretchr/testify/mock"
	connector "github.com/wisp-trading/sdk/pkg/types/connector"

	portfolio "github.com/wisp-trading/sdk/pkg/types/portfolio"

	registry "github.com/wisp-trading/sdk/pkg/types/registry"
)

// AssetRegistry is an autogenerated mock type for the AssetRegistry type
type AssetRegistry struct {
	mock.Mock
}

type AssetRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *AssetRegistry) EXPECT() *AssetRegistry_Expecter {
	return &AssetRegistry_Expecter{mock: &_m.Mock}
}

// GetAssetRequirements provides a mock function with no fields
func (_m *AssetRegistry) GetPairRequirements() []registry.PairRequirement {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPairRequirements")
	}

	var r0 []registry.PairRequirement
	if rf, ok := ret.Get(0).(func() []registry.PairRequirement); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]registry.PairRequirement)
		}
	}

	return r0
}

// AssetRegistry_GetAssetRequirements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPairRequirements'
type AssetRegistry_GetAssetRequirements_Call struct {
	*mock.Call
}

// GetAssetRequirements is a helper method to define mock.On call
func (_e *AssetRegistry_Expecter) GetAssetRequirements() *AssetRegistry_GetAssetRequirements_Call {
	return &AssetRegistry_GetAssetRequirements_Call{Call: _e.mock.On("GetPairRequirements")}
}

func (_c *AssetRegistry_GetAssetRequirements_Call) Run(run func()) *AssetRegistry_GetAssetRequirements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AssetRegistry_GetAssetRequirements_Call) Return(_a0 []registry.PairRequirement) *AssetRegistry_GetAssetRequirements_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AssetRegistry_GetAssetRequirements_Call) RunAndReturn(run func() []registry.PairRequirement) *AssetRegistry_GetAssetRequirements_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstrumentTypes provides a mock function with given fields: asset
func (_m *AssetRegistry) GetInstrumentTypes(asset portfolio.Pair) []connector.Instrument {
	ret := _m.Called(asset)

	if len(ret) == 0 {
		panic("no return value specified for GetInstrumentTypes")
	}

	var r0 []connector.Instrument
	if rf, ok := ret.Get(0).(func(portfolio.Pair) []connector.Instrument); ok {
		r0 = rf(asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Instrument)
		}
	}

	return r0
}

// AssetRegistry_GetInstrumentTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstrumentTypes'
type AssetRegistry_GetInstrumentTypes_Call struct {
	*mock.Call
}

// GetInstrumentTypes is a helper method to define mock.On call
//   - asset portfolio.Pair
func (_e *AssetRegistry_Expecter) GetInstrumentTypes(asset interface{}) *AssetRegistry_GetInstrumentTypes_Call {
	return &AssetRegistry_GetInstrumentTypes_Call{Call: _e.mock.On("GetInstrumentTypes", asset)}
}

func (_c *AssetRegistry_GetInstrumentTypes_Call) Run(run func(asset portfolio.Pair)) *AssetRegistry_GetInstrumentTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Pair))
	})
	return _c
}

func (_c *AssetRegistry_GetInstrumentTypes_Call) Return(_a0 []connector.Instrument) *AssetRegistry_GetInstrumentTypes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AssetRegistry_GetInstrumentTypes_Call) RunAndReturn(run func(portfolio.Pair) []connector.Instrument) *AssetRegistry_GetInstrumentTypes_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequiredAssets provides a mock function with no fields
func (_m *AssetRegistry) GetRequiredPairs() []portfolio.Pair {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRequiredPairs")
	}

	var r0 []portfolio.Pair
	if rf, ok := ret.Get(0).(func() []portfolio.Pair); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]portfolio.Pair)
		}
	}

	return r0
}

// AssetRegistry_GetRequiredAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequiredPairs'
type AssetRegistry_GetRequiredAssets_Call struct {
	*mock.Call
}

// GetRequiredAssets is a helper method to define mock.On call
func (_e *AssetRegistry_Expecter) GetRequiredAssets() *AssetRegistry_GetRequiredAssets_Call {
	return &AssetRegistry_GetRequiredAssets_Call{Call: _e.mock.On("GetRequiredPairs")}
}

func (_c *AssetRegistry_GetRequiredAssets_Call) Run(run func()) *AssetRegistry_GetRequiredAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AssetRegistry_GetRequiredAssets_Call) Return(_a0 []portfolio.Pair) *AssetRegistry_GetRequiredAssets_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AssetRegistry_GetRequiredAssets_Call) RunAndReturn(run func() []portfolio.Pair) *AssetRegistry_GetRequiredAssets_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterAsset provides a mock function with given fields: asset, instruments
func (_m *AssetRegistry) RegisterPair(asset portfolio.Pair, instruments ...connector.Instrument) {
	_va := make([]interface{}, len(instruments))
	for _i := range instruments {
		_va[_i] = instruments[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, asset)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// AssetRegistry_RegisterAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPair'
type AssetRegistry_RegisterAsset_Call struct {
	*mock.Call
}

// RegisterAsset is a helper method to define mock.On call
//   - asset portfolio.Pair
//   - instruments ...connector.Instrument
func (_e *AssetRegistry_Expecter) RegisterAsset(asset interface{}, instruments ...interface{}) *AssetRegistry_RegisterAsset_Call {
	return &AssetRegistry_RegisterAsset_Call{Call: _e.mock.On("RegisterPair",
		append([]interface{}{asset}, instruments...)...)}
}

func (_c *AssetRegistry_RegisterAsset_Call) Run(run func(asset portfolio.Pair, instruments ...connector.Instrument)) *AssetRegistry_RegisterAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]connector.Instrument, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(connector.Instrument)
			}
		}
		run(args[0].(portfolio.Pair), variadicArgs...)
	})
	return _c
}

func (_c *AssetRegistry_RegisterAsset_Call) Return() *AssetRegistry_RegisterAsset_Call {
	_c.Call.Return()
	return _c
}

func (_c *AssetRegistry_RegisterAsset_Call) RunAndReturn(run func(portfolio.Pair, ...connector.Instrument)) *AssetRegistry_RegisterAsset_Call {
	_c.Run(run)
	return _c
}

// NewAssetRegistry creates a new instance of AssetRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssetRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssetRegistry {
	mock := &AssetRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
