// Code generated by mockery v2.53.5. DO NOT EDIT.

package registry

import (
	mock "github.com/stretchr/testify/mock"
	connector "github.com/wisp-trading/sdk/pkg/types/connector"

	perp "github.com/wisp-trading/sdk/pkg/types/connector/perp"

	registry "github.com/wisp-trading/sdk/pkg/types/registry"

	spot "github.com/wisp-trading/sdk/pkg/types/connector/spot"

	typesconnector "github.com/wisp-trading/sdk/pkg/markets/prediction/types/connector"
)

// ConnectorRegistry is an autogenerated mock type for the ConnectorRegistry type
type ConnectorRegistry struct {
	mock.Mock
}

type ConnectorRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnectorRegistry) EXPECT() *ConnectorRegistry_Expecter {
	return &ConnectorRegistry_Expecter{mock: &_m.Mock}
}

// Connector provides a mock function with given fields: name
func (_m *ConnectorRegistry) Connector(name connector.ExchangeName) (connector.Connector, bool) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Connector")
	}

	var r0 connector.Connector
	var r1 bool
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) (connector.Connector, bool)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) connector.Connector); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(connector.Connector)
		}
	}

	if rf, ok := ret.Get(1).(func(connector.ExchangeName) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ConnectorRegistry_Connector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connector'
type ConnectorRegistry_Connector_Call struct {
	*mock.Call
}

// Connector is a helper method to define mock.On call
//   - name connector.ExchangeName
func (_e *ConnectorRegistry_Expecter) Connector(name interface{}) *ConnectorRegistry_Connector_Call {
	return &ConnectorRegistry_Connector_Call{Call: _e.mock.On("Connector", name)}
}

func (_c *ConnectorRegistry_Connector_Call) Run(run func(name connector.ExchangeName)) *ConnectorRegistry_Connector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName))
	})
	return _c
}

func (_c *ConnectorRegistry_Connector_Call) Return(_a0 connector.Connector, _a1 bool) *ConnectorRegistry_Connector_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectorRegistry_Connector_Call) RunAndReturn(run func(connector.ExchangeName) (connector.Connector, bool)) *ConnectorRegistry_Connector_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function with given fields: opts
func (_m *ConnectorRegistry) Filter(opts registry.FilterOptions) []connector.Connector {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 []connector.Connector
	if rf, ok := ret.Get(0).(func(registry.FilterOptions) []connector.Connector); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Connector)
		}
	}

	return r0
}

// ConnectorRegistry_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type ConnectorRegistry_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - opts registry.FilterOptions
func (_e *ConnectorRegistry_Expecter) Filter(opts interface{}) *ConnectorRegistry_Filter_Call {
	return &ConnectorRegistry_Filter_Call{Call: _e.mock.On("Filter", opts)}
}

func (_c *ConnectorRegistry_Filter_Call) Run(run func(opts registry.FilterOptions)) *ConnectorRegistry_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(registry.FilterOptions))
	})
	return _c
}

func (_c *ConnectorRegistry_Filter_Call) Return(_a0 []connector.Connector) *ConnectorRegistry_Filter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectorRegistry_Filter_Call) RunAndReturn(run func(registry.FilterOptions) []connector.Connector) *ConnectorRegistry_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FilterPerp provides a mock function with given fields: opts
func (_m *ConnectorRegistry) FilterPerp(opts registry.FilterOptions) []perp.Connector {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for FilterPerp")
	}

	var r0 []perp.Connector
	if rf, ok := ret.Get(0).(func(registry.FilterOptions) []perp.Connector); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]perp.Connector)
		}
	}

	return r0
}

// ConnectorRegistry_FilterPerp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterPerp'
type ConnectorRegistry_FilterPerp_Call struct {
	*mock.Call
}

// FilterPerp is a helper method to define mock.On call
//   - opts registry.FilterOptions
func (_e *ConnectorRegistry_Expecter) FilterPerp(opts interface{}) *ConnectorRegistry_FilterPerp_Call {
	return &ConnectorRegistry_FilterPerp_Call{Call: _e.mock.On("FilterPerp", opts)}
}

func (_c *ConnectorRegistry_FilterPerp_Call) Run(run func(opts registry.FilterOptions)) *ConnectorRegistry_FilterPerp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(registry.FilterOptions))
	})
	return _c
}

func (_c *ConnectorRegistry_FilterPerp_Call) Return(_a0 []perp.Connector) *ConnectorRegistry_FilterPerp_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectorRegistry_FilterPerp_Call) RunAndReturn(run func(registry.FilterOptions) []perp.Connector) *ConnectorRegistry_FilterPerp_Call {
	_c.Call.Return(run)
	return _c
}

// FilterPrediction provides a mock function with given fields: opts
func (_m *ConnectorRegistry) FilterPrediction(opts registry.FilterOptions) []typesconnector.Connector {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for FilterPrediction")
	}

	var r0 []typesconnector.Connector
	if rf, ok := ret.Get(0).(func(registry.FilterOptions) []typesconnector.Connector); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]typesconnector.Connector)
		}
	}

	return r0
}

// ConnectorRegistry_FilterPrediction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterPrediction'
type ConnectorRegistry_FilterPrediction_Call struct {
	*mock.Call
}

// FilterPrediction is a helper method to define mock.On call
//   - opts registry.FilterOptions
func (_e *ConnectorRegistry_Expecter) FilterPrediction(opts interface{}) *ConnectorRegistry_FilterPrediction_Call {
	return &ConnectorRegistry_FilterPrediction_Call{Call: _e.mock.On("FilterPrediction", opts)}
}

func (_c *ConnectorRegistry_FilterPrediction_Call) Run(run func(opts registry.FilterOptions)) *ConnectorRegistry_FilterPrediction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(registry.FilterOptions))
	})
	return _c
}

func (_c *ConnectorRegistry_FilterPrediction_Call) Return(_a0 []typesconnector.Connector) *ConnectorRegistry_FilterPrediction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectorRegistry_FilterPrediction_Call) RunAndReturn(run func(registry.FilterOptions) []typesconnector.Connector) *ConnectorRegistry_FilterPrediction_Call {
	_c.Call.Return(run)
	return _c
}

// FilterSpot provides a mock function with given fields: opts
func (_m *ConnectorRegistry) FilterSpot(opts registry.FilterOptions) []spot.Connector {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for FilterSpot")
	}

	var r0 []spot.Connector
	if rf, ok := ret.Get(0).(func(registry.FilterOptions) []spot.Connector); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]spot.Connector)
		}
	}

	return r0
}

// ConnectorRegistry_FilterSpot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterSpot'
type ConnectorRegistry_FilterSpot_Call struct {
	*mock.Call
}

// FilterSpot is a helper method to define mock.On call
//   - opts registry.FilterOptions
func (_e *ConnectorRegistry_Expecter) FilterSpot(opts interface{}) *ConnectorRegistry_FilterSpot_Call {
	return &ConnectorRegistry_FilterSpot_Call{Call: _e.mock.On("FilterSpot", opts)}
}

func (_c *ConnectorRegistry_FilterSpot_Call) Run(run func(opts registry.FilterOptions)) *ConnectorRegistry_FilterSpot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(registry.FilterOptions))
	})
	return _c
}

func (_c *ConnectorRegistry_FilterSpot_Call) Return(_a0 []spot.Connector) *ConnectorRegistry_FilterSpot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectorRegistry_FilterSpot_Call) RunAndReturn(run func(registry.FilterOptions) []spot.Connector) *ConnectorRegistry_FilterSpot_Call {
	_c.Call.Return(run)
	return _c
}

// IsReady provides a mock function with given fields: name
func (_m *ConnectorRegistry) IsReady(name connector.ExchangeName) bool {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for IsReady")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ConnectorRegistry_IsReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsReady'
type ConnectorRegistry_IsReady_Call struct {
	*mock.Call
}

// IsReady is a helper method to define mock.On call
//   - name connector.ExchangeName
func (_e *ConnectorRegistry_Expecter) IsReady(name interface{}) *ConnectorRegistry_IsReady_Call {
	return &ConnectorRegistry_IsReady_Call{Call: _e.mock.On("IsReady", name)}
}

func (_c *ConnectorRegistry_IsReady_Call) Run(run func(name connector.ExchangeName)) *ConnectorRegistry_IsReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName))
	})
	return _c
}

func (_c *ConnectorRegistry_IsReady_Call) Return(_a0 bool) *ConnectorRegistry_IsReady_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectorRegistry_IsReady_Call) RunAndReturn(run func(connector.ExchangeName) bool) *ConnectorRegistry_IsReady_Call {
	_c.Call.Return(run)
	return _c
}

// MarkReady provides a mock function with given fields: name
func (_m *ConnectorRegistry) MarkReady(name connector.ExchangeName) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for MarkReady")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectorRegistry_MarkReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReady'
type ConnectorRegistry_MarkReady_Call struct {
	*mock.Call
}

// MarkReady is a helper method to define mock.On call
//   - name connector.ExchangeName
func (_e *ConnectorRegistry_Expecter) MarkReady(name interface{}) *ConnectorRegistry_MarkReady_Call {
	return &ConnectorRegistry_MarkReady_Call{Call: _e.mock.On("MarkReady", name)}
}

func (_c *ConnectorRegistry_MarkReady_Call) Run(run func(name connector.ExchangeName)) *ConnectorRegistry_MarkReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName))
	})
	return _c
}

func (_c *ConnectorRegistry_MarkReady_Call) Return(_a0 error) *ConnectorRegistry_MarkReady_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectorRegistry_MarkReady_Call) RunAndReturn(run func(connector.ExchangeName) error) *ConnectorRegistry_MarkReady_Call {
	_c.Call.Return(run)
	return _c
}

// Perp provides a mock function with given fields: name
func (_m *ConnectorRegistry) Perp(name connector.ExchangeName) (perp.Connector, bool) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Perp")
	}

	var r0 perp.Connector
	var r1 bool
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) (perp.Connector, bool)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) perp.Connector); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(perp.Connector)
		}
	}

	if rf, ok := ret.Get(1).(func(connector.ExchangeName) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ConnectorRegistry_Perp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Perp'
type ConnectorRegistry_Perp_Call struct {
	*mock.Call
}

// Perp is a helper method to define mock.On call
//   - name connector.ExchangeName
func (_e *ConnectorRegistry_Expecter) Perp(name interface{}) *ConnectorRegistry_Perp_Call {
	return &ConnectorRegistry_Perp_Call{Call: _e.mock.On("Perp", name)}
}

func (_c *ConnectorRegistry_Perp_Call) Run(run func(name connector.ExchangeName)) *ConnectorRegistry_Perp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName))
	})
	return _c
}

func (_c *ConnectorRegistry_Perp_Call) Return(_a0 perp.Connector, _a1 bool) *ConnectorRegistry_Perp_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectorRegistry_Perp_Call) RunAndReturn(run func(connector.ExchangeName) (perp.Connector, bool)) *ConnectorRegistry_Perp_Call {
	_c.Call.Return(run)
	return _c
}

// PerpWebSocket provides a mock function with given fields: name
func (_m *ConnectorRegistry) PerpWebSocket(name connector.ExchangeName) (perp.WebSocketConnector, bool) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for PerpWebSocket")
	}

	var r0 perp.WebSocketConnector
	var r1 bool
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) (perp.WebSocketConnector, bool)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) perp.WebSocketConnector); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(perp.WebSocketConnector)
		}
	}

	if rf, ok := ret.Get(1).(func(connector.ExchangeName) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ConnectorRegistry_PerpWebSocket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PerpWebSocket'
type ConnectorRegistry_PerpWebSocket_Call struct {
	*mock.Call
}

// PerpWebSocket is a helper method to define mock.On call
//   - name connector.ExchangeName
func (_e *ConnectorRegistry_Expecter) PerpWebSocket(name interface{}) *ConnectorRegistry_PerpWebSocket_Call {
	return &ConnectorRegistry_PerpWebSocket_Call{Call: _e.mock.On("PerpWebSocket", name)}
}

func (_c *ConnectorRegistry_PerpWebSocket_Call) Run(run func(name connector.ExchangeName)) *ConnectorRegistry_PerpWebSocket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName))
	})
	return _c
}

func (_c *ConnectorRegistry_PerpWebSocket_Call) Return(_a0 perp.WebSocketConnector, _a1 bool) *ConnectorRegistry_PerpWebSocket_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectorRegistry_PerpWebSocket_Call) RunAndReturn(run func(connector.ExchangeName) (perp.WebSocketConnector, bool)) *ConnectorRegistry_PerpWebSocket_Call {
	_c.Call.Return(run)
	return _c
}

// Prediction provides a mock function with given fields: name
func (_m *ConnectorRegistry) Prediction(name connector.ExchangeName) (typesconnector.Connector, bool) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Prediction")
	}

	var r0 typesconnector.Connector
	var r1 bool
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) (typesconnector.Connector, bool)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) typesconnector.Connector); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(typesconnector.Connector)
		}
	}

	if rf, ok := ret.Get(1).(func(connector.ExchangeName) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ConnectorRegistry_Prediction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prediction'
type ConnectorRegistry_Prediction_Call struct {
	*mock.Call
}

// Prediction is a helper method to define mock.On call
//   - name connector.ExchangeName
func (_e *ConnectorRegistry_Expecter) Prediction(name interface{}) *ConnectorRegistry_Prediction_Call {
	return &ConnectorRegistry_Prediction_Call{Call: _e.mock.On("Prediction", name)}
}

func (_c *ConnectorRegistry_Prediction_Call) Run(run func(name connector.ExchangeName)) *ConnectorRegistry_Prediction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName))
	})
	return _c
}

func (_c *ConnectorRegistry_Prediction_Call) Return(_a0 typesconnector.Connector, _a1 bool) *ConnectorRegistry_Prediction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectorRegistry_Prediction_Call) RunAndReturn(run func(connector.ExchangeName) (typesconnector.Connector, bool)) *ConnectorRegistry_Prediction_Call {
	_c.Call.Return(run)
	return _c
}

// PredictionWebSocket provides a mock function with given fields: name
func (_m *ConnectorRegistry) PredictionWebSocket(name connector.ExchangeName) (typesconnector.WebSocketConnector, bool) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for PredictionWebSocket")
	}

	var r0 typesconnector.WebSocketConnector
	var r1 bool
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) (typesconnector.WebSocketConnector, bool)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) typesconnector.WebSocketConnector); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(typesconnector.WebSocketConnector)
		}
	}

	if rf, ok := ret.Get(1).(func(connector.ExchangeName) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ConnectorRegistry_PredictionWebSocket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PredictionWebSocket'
type ConnectorRegistry_PredictionWebSocket_Call struct {
	*mock.Call
}

// PredictionWebSocket is a helper method to define mock.On call
//   - name connector.ExchangeName
func (_e *ConnectorRegistry_Expecter) PredictionWebSocket(name interface{}) *ConnectorRegistry_PredictionWebSocket_Call {
	return &ConnectorRegistry_PredictionWebSocket_Call{Call: _e.mock.On("PredictionWebSocket", name)}
}

func (_c *ConnectorRegistry_PredictionWebSocket_Call) Run(run func(name connector.ExchangeName)) *ConnectorRegistry_PredictionWebSocket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName))
	})
	return _c
}

func (_c *ConnectorRegistry_PredictionWebSocket_Call) Return(_a0 typesconnector.WebSocketConnector, _a1 bool) *ConnectorRegistry_PredictionWebSocket_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectorRegistry_PredictionWebSocket_Call) RunAndReturn(run func(connector.ExchangeName) (typesconnector.WebSocketConnector, bool)) *ConnectorRegistry_PredictionWebSocket_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterPerp provides a mock function with given fields: name, conn
func (_m *ConnectorRegistry) RegisterPerp(name connector.ExchangeName, conn perp.Connector) {
	_m.Called(name, conn)
}

// ConnectorRegistry_RegisterPerp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPerp'
type ConnectorRegistry_RegisterPerp_Call struct {
	*mock.Call
}

// RegisterPerp is a helper method to define mock.On call
//   - name connector.ExchangeName
//   - conn perp.Connector
func (_e *ConnectorRegistry_Expecter) RegisterPerp(name interface{}, conn interface{}) *ConnectorRegistry_RegisterPerp_Call {
	return &ConnectorRegistry_RegisterPerp_Call{Call: _e.mock.On("RegisterPerp", name, conn)}
}

func (_c *ConnectorRegistry_RegisterPerp_Call) Run(run func(name connector.ExchangeName, conn perp.Connector)) *ConnectorRegistry_RegisterPerp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName), args[1].(perp.Connector))
	})
	return _c
}

func (_c *ConnectorRegistry_RegisterPerp_Call) Return() *ConnectorRegistry_RegisterPerp_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConnectorRegistry_RegisterPerp_Call) RunAndReturn(run func(connector.ExchangeName, perp.Connector)) *ConnectorRegistry_RegisterPerp_Call {
	_c.Run(run)
	return _c
}

// RegisterPrediction provides a mock function with given fields: name, conn
func (_m *ConnectorRegistry) RegisterPrediction(name connector.ExchangeName, conn typesconnector.Connector) {
	_m.Called(name, conn)
}

// ConnectorRegistry_RegisterPrediction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPrediction'
type ConnectorRegistry_RegisterPrediction_Call struct {
	*mock.Call
}

// RegisterPrediction is a helper method to define mock.On call
//   - name connector.ExchangeName
//   - conn typesconnector.Connector
func (_e *ConnectorRegistry_Expecter) RegisterPrediction(name interface{}, conn interface{}) *ConnectorRegistry_RegisterPrediction_Call {
	return &ConnectorRegistry_RegisterPrediction_Call{Call: _e.mock.On("RegisterPrediction", name, conn)}
}

func (_c *ConnectorRegistry_RegisterPrediction_Call) Run(run func(name connector.ExchangeName, conn typesconnector.Connector)) *ConnectorRegistry_RegisterPrediction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName), args[1].(typesconnector.Connector))
	})
	return _c
}

func (_c *ConnectorRegistry_RegisterPrediction_Call) Return() *ConnectorRegistry_RegisterPrediction_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConnectorRegistry_RegisterPrediction_Call) RunAndReturn(run func(connector.ExchangeName, typesconnector.Connector)) *ConnectorRegistry_RegisterPrediction_Call {
	_c.Run(run)
	return _c
}

// RegisterSpot provides a mock function with given fields: name, conn
func (_m *ConnectorRegistry) RegisterSpot(name connector.ExchangeName, conn spot.Connector) {
	_m.Called(name, conn)
}

// ConnectorRegistry_RegisterSpot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterSpot'
type ConnectorRegistry_RegisterSpot_Call struct {
	*mock.Call
}

// RegisterSpot is a helper method to define mock.On call
//   - name connector.ExchangeName
//   - conn spot.Connector
func (_e *ConnectorRegistry_Expecter) RegisterSpot(name interface{}, conn interface{}) *ConnectorRegistry_RegisterSpot_Call {
	return &ConnectorRegistry_RegisterSpot_Call{Call: _e.mock.On("RegisterSpot", name, conn)}
}

func (_c *ConnectorRegistry_RegisterSpot_Call) Run(run func(name connector.ExchangeName, conn spot.Connector)) *ConnectorRegistry_RegisterSpot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName), args[1].(spot.Connector))
	})
	return _c
}

func (_c *ConnectorRegistry_RegisterSpot_Call) Return() *ConnectorRegistry_RegisterSpot_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConnectorRegistry_RegisterSpot_Call) RunAndReturn(run func(connector.ExchangeName, spot.Connector)) *ConnectorRegistry_RegisterSpot_Call {
	_c.Run(run)
	return _c
}

// Spot provides a mock function with given fields: name
func (_m *ConnectorRegistry) Spot(name connector.ExchangeName) (spot.Connector, bool) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Spot")
	}

	var r0 spot.Connector
	var r1 bool
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) (spot.Connector, bool)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) spot.Connector); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(spot.Connector)
		}
	}

	if rf, ok := ret.Get(1).(func(connector.ExchangeName) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ConnectorRegistry_Spot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spot'
type ConnectorRegistry_Spot_Call struct {
	*mock.Call
}

// Spot is a helper method to define mock.On call
//   - name connector.ExchangeName
func (_e *ConnectorRegistry_Expecter) Spot(name interface{}) *ConnectorRegistry_Spot_Call {
	return &ConnectorRegistry_Spot_Call{Call: _e.mock.On("Spot", name)}
}

func (_c *ConnectorRegistry_Spot_Call) Run(run func(name connector.ExchangeName)) *ConnectorRegistry_Spot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName))
	})
	return _c
}

func (_c *ConnectorRegistry_Spot_Call) Return(_a0 spot.Connector, _a1 bool) *ConnectorRegistry_Spot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectorRegistry_Spot_Call) RunAndReturn(run func(connector.ExchangeName) (spot.Connector, bool)) *ConnectorRegistry_Spot_Call {
	_c.Call.Return(run)
	return _c
}

// SpotWebSocket provides a mock function with given fields: name
func (_m *ConnectorRegistry) SpotWebSocket(name connector.ExchangeName) (spot.WebSocketConnector, bool) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for SpotWebSocket")
	}

	var r0 spot.WebSocketConnector
	var r1 bool
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) (spot.WebSocketConnector, bool)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) spot.WebSocketConnector); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(spot.WebSocketConnector)
		}
	}

	if rf, ok := ret.Get(1).(func(connector.ExchangeName) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ConnectorRegistry_SpotWebSocket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SpotWebSocket'
type ConnectorRegistry_SpotWebSocket_Call struct {
	*mock.Call
}

// SpotWebSocket is a helper method to define mock.On call
//   - name connector.ExchangeName
func (_e *ConnectorRegistry_Expecter) SpotWebSocket(name interface{}) *ConnectorRegistry_SpotWebSocket_Call {
	return &ConnectorRegistry_SpotWebSocket_Call{Call: _e.mock.On("SpotWebSocket", name)}
}

func (_c *ConnectorRegistry_SpotWebSocket_Call) Run(run func(name connector.ExchangeName)) *ConnectorRegistry_SpotWebSocket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName))
	})
	return _c
}

func (_c *ConnectorRegistry_SpotWebSocket_Call) Return(_a0 spot.WebSocketConnector, _a1 bool) *ConnectorRegistry_SpotWebSocket_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectorRegistry_SpotWebSocket_Call) RunAndReturn(run func(connector.ExchangeName) (spot.WebSocketConnector, bool)) *ConnectorRegistry_SpotWebSocket_Call {
	_c.Call.Return(run)
	return _c
}

// NewConnectorRegistry creates a new instance of ConnectorRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectorRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectorRegistry {
	mock := &ConnectorRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
