// Code generated by mockery v2.53.5. DO NOT EDIT.

package profiling

import (
	time "time"

	profiling "github.com/backtesting-org/kronos-sdk/pkg/types/profiling"
	mock "github.com/stretchr/testify/mock"
)

// Context is an autogenerated mock type for the Context type
type Context struct {
	mock.Mock
}

type Context_Expecter struct {
	mock *mock.Mock
}

func (_m *Context) EXPECT() *Context_Expecter {
	return &Context_Expecter{mock: &_m.Mock}
}

// Finalize provides a mock function with given fields: success, err
func (_m *Context) Finalize(success bool, err error) profiling.StrategyMetrics {
	ret := _m.Called(success, err)

	if len(ret) == 0 {
		panic("no return value specified for Finalize")
	}

	var r0 profiling.StrategyMetrics
	if rf, ok := ret.Get(0).(func(bool, error) profiling.StrategyMetrics); ok {
		r0 = rf(success, err)
	} else {
		r0 = ret.Get(0).(profiling.StrategyMetrics)
	}

	return r0
}

// Context_Finalize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finalize'
type Context_Finalize_Call struct {
	*mock.Call
}

// Finalize is a helper method to define mock.On call
//   - success bool
//   - err error
func (_e *Context_Expecter) Finalize(success interface{}, err interface{}) *Context_Finalize_Call {
	return &Context_Finalize_Call{Call: _e.mock.On("Finalize", success, err)}
}

func (_c *Context_Finalize_Call) Run(run func(success bool, err error)) *Context_Finalize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool), args[1].(error))
	})
	return _c
}

func (_c *Context_Finalize_Call) Return(_a0 profiling.StrategyMetrics) *Context_Finalize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Context_Finalize_Call) RunAndReturn(run func(bool, error) profiling.StrategyMetrics) *Context_Finalize_Call {
	_c.Call.Return(run)
	return _c
}

// GetStrategyName provides a mock function with no fields
func (_m *Context) GetStrategyName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStrategyName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Context_GetStrategyName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStrategyName'
type Context_GetStrategyName_Call struct {
	*mock.Call
}

// GetStrategyName is a helper method to define mock.On call
func (_e *Context_Expecter) GetStrategyName() *Context_GetStrategyName_Call {
	return &Context_GetStrategyName_Call{Call: _e.mock.On("GetStrategyName")}
}

func (_c *Context_GetStrategyName_Call) Run(run func()) *Context_GetStrategyName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Context_GetStrategyName_Call) Return(_a0 string) *Context_GetStrategyName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Context_GetStrategyName_Call) RunAndReturn(run func() string) *Context_GetStrategyName_Call {
	_c.Call.Return(run)
	return _c
}

// RecordIndicator provides a mock function with given fields: name, duration
func (_m *Context) RecordIndicator(name string, duration time.Duration) {
	_m.Called(name, duration)
}

// Context_RecordIndicator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordIndicator'
type Context_RecordIndicator_Call struct {
	*mock.Call
}

// RecordIndicator is a helper method to define mock.On call
//   - name string
//   - duration time.Duration
func (_e *Context_Expecter) RecordIndicator(name interface{}, duration interface{}) *Context_RecordIndicator_Call {
	return &Context_RecordIndicator_Call{Call: _e.mock.On("RecordIndicator", name, duration)}
}

func (_c *Context_RecordIndicator_Call) Run(run func(name string, duration time.Duration)) *Context_RecordIndicator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *Context_RecordIndicator_Call) Return() *Context_RecordIndicator_Call {
	_c.Call.Return()
	return _c
}

func (_c *Context_RecordIndicator_Call) RunAndReturn(run func(string, time.Duration)) *Context_RecordIndicator_Call {
	_c.Run(run)
	return _c
}

// RecordSignalGeneration provides a mock function with given fields: duration
func (_m *Context) RecordSignalGeneration(duration time.Duration) {
	_m.Called(duration)
}

// Context_RecordSignalGeneration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordSignalGeneration'
type Context_RecordSignalGeneration_Call struct {
	*mock.Call
}

// RecordSignalGeneration is a helper method to define mock.On call
//   - duration time.Duration
func (_e *Context_Expecter) RecordSignalGeneration(duration interface{}) *Context_RecordSignalGeneration_Call {
	return &Context_RecordSignalGeneration_Call{Call: _e.mock.On("RecordSignalGeneration", duration)}
}

func (_c *Context_RecordSignalGeneration_Call) Run(run func(duration time.Duration)) *Context_RecordSignalGeneration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *Context_RecordSignalGeneration_Call) Return() *Context_RecordSignalGeneration_Call {
	_c.Call.Return()
	return _c
}

func (_c *Context_RecordSignalGeneration_Call) RunAndReturn(run func(time.Duration)) *Context_RecordSignalGeneration_Call {
	_c.Run(run)
	return _c
}

// NewContext creates a new instance of Context. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *Context {
	mock := &Context{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
