// Code generated by mockery v2.53.5. DO NOT EDIT.

package profiling

import (
	time "time"

	profiling "github.com/backtesting-org/kronos-sdk/pkg/types/profiling"
	mock "github.com/stretchr/testify/mock"
)

// ProfilingStore is an autogenerated mock type for the ProfilingStore type
type ProfilingStore struct {
	mock.Mock
}

type ProfilingStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfilingStore) EXPECT() *ProfilingStore_Expecter {
	return &ProfilingStore_Expecter{mock: &_m.Mock}
}

// GetAverageExecutionTime provides a mock function with given fields: strategyName
func (_m *ProfilingStore) GetAverageExecutionTime(strategyName string) time.Duration {
	ret := _m.Called(strategyName)

	if len(ret) == 0 {
		panic("no return value specified for GetAverageExecutionTime")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(string) time.Duration); ok {
		r0 = rf(strategyName)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// ProfilingStore_GetAverageExecutionTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAverageExecutionTime'
type ProfilingStore_GetAverageExecutionTime_Call struct {
	*mock.Call
}

// GetAverageExecutionTime is a helper method to define mock.On call
//   - strategyName string
func (_e *ProfilingStore_Expecter) GetAverageExecutionTime(strategyName interface{}) *ProfilingStore_GetAverageExecutionTime_Call {
	return &ProfilingStore_GetAverageExecutionTime_Call{Call: _e.mock.On("GetAverageExecutionTime", strategyName)}
}

func (_c *ProfilingStore_GetAverageExecutionTime_Call) Run(run func(strategyName string)) *ProfilingStore_GetAverageExecutionTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ProfilingStore_GetAverageExecutionTime_Call) Return(_a0 time.Duration) *ProfilingStore_GetAverageExecutionTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfilingStore_GetAverageExecutionTime_Call) RunAndReturn(run func(string) time.Duration) *ProfilingStore_GetAverageExecutionTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetPercentile provides a mock function with given fields: strategyName, percentile
func (_m *ProfilingStore) GetPercentile(strategyName string, percentile float64) time.Duration {
	ret := _m.Called(strategyName, percentile)

	if len(ret) == 0 {
		panic("no return value specified for GetPercentile")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(string, float64) time.Duration); ok {
		r0 = rf(strategyName, percentile)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// ProfilingStore_GetPercentile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPercentile'
type ProfilingStore_GetPercentile_Call struct {
	*mock.Call
}

// GetPercentile is a helper method to define mock.On call
//   - strategyName string
//   - percentile float64
func (_e *ProfilingStore_Expecter) GetPercentile(strategyName interface{}, percentile interface{}) *ProfilingStore_GetPercentile_Call {
	return &ProfilingStore_GetPercentile_Call{Call: _e.mock.On("GetPercentile", strategyName, percentile)}
}

func (_c *ProfilingStore_GetPercentile_Call) Run(run func(strategyName string, percentile float64)) *ProfilingStore_GetPercentile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64))
	})
	return _c
}

func (_c *ProfilingStore_GetPercentile_Call) Return(_a0 time.Duration) *ProfilingStore_GetPercentile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfilingStore_GetPercentile_Call) RunAndReturn(run func(string, float64) time.Duration) *ProfilingStore_GetPercentile_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentMetrics provides a mock function with given fields: strategyName, limit
func (_m *ProfilingStore) GetRecentMetrics(strategyName string, limit int) []profiling.StrategyMetrics {
	ret := _m.Called(strategyName, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentMetrics")
	}

	var r0 []profiling.StrategyMetrics
	if rf, ok := ret.Get(0).(func(string, int) []profiling.StrategyMetrics); ok {
		r0 = rf(strategyName, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]profiling.StrategyMetrics)
		}
	}

	return r0
}

// ProfilingStore_GetRecentMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentMetrics'
type ProfilingStore_GetRecentMetrics_Call struct {
	*mock.Call
}

// GetRecentMetrics is a helper method to define mock.On call
//   - strategyName string
//   - limit int
func (_e *ProfilingStore_Expecter) GetRecentMetrics(strategyName interface{}, limit interface{}) *ProfilingStore_GetRecentMetrics_Call {
	return &ProfilingStore_GetRecentMetrics_Call{Call: _e.mock.On("GetRecentMetrics", strategyName, limit)}
}

func (_c *ProfilingStore_GetRecentMetrics_Call) Run(run func(strategyName string, limit int)) *ProfilingStore_GetRecentMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *ProfilingStore_GetRecentMetrics_Call) Return(_a0 []profiling.StrategyMetrics) *ProfilingStore_GetRecentMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfilingStore_GetRecentMetrics_Call) RunAndReturn(run func(string, int) []profiling.StrategyMetrics) *ProfilingStore_GetRecentMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: strategyName
func (_m *ProfilingStore) GetStats(strategyName string) profiling.StrategyStats {
	ret := _m.Called(strategyName)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 profiling.StrategyStats
	if rf, ok := ret.Get(0).(func(string) profiling.StrategyStats); ok {
		r0 = rf(strategyName)
	} else {
		r0 = ret.Get(0).(profiling.StrategyStats)
	}

	return r0
}

// ProfilingStore_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type ProfilingStore_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - strategyName string
func (_e *ProfilingStore_Expecter) GetStats(strategyName interface{}) *ProfilingStore_GetStats_Call {
	return &ProfilingStore_GetStats_Call{Call: _e.mock.On("GetStats", strategyName)}
}

func (_c *ProfilingStore_GetStats_Call) Run(run func(strategyName string)) *ProfilingStore_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ProfilingStore_GetStats_Call) Return(_a0 profiling.StrategyStats) *ProfilingStore_GetStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfilingStore_GetStats_Call) RunAndReturn(run func(string) profiling.StrategyStats) *ProfilingStore_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// RecordExecution provides a mock function with given fields: metrics
func (_m *ProfilingStore) RecordExecution(metrics profiling.StrategyMetrics) {
	_m.Called(metrics)
}

// ProfilingStore_RecordExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordExecution'
type ProfilingStore_RecordExecution_Call struct {
	*mock.Call
}

// RecordExecution is a helper method to define mock.On call
//   - metrics profiling.StrategyMetrics
func (_e *ProfilingStore_Expecter) RecordExecution(metrics interface{}) *ProfilingStore_RecordExecution_Call {
	return &ProfilingStore_RecordExecution_Call{Call: _e.mock.On("RecordExecution", metrics)}
}

func (_c *ProfilingStore_RecordExecution_Call) Run(run func(metrics profiling.StrategyMetrics)) *ProfilingStore_RecordExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(profiling.StrategyMetrics))
	})
	return _c
}

func (_c *ProfilingStore_RecordExecution_Call) Return() *ProfilingStore_RecordExecution_Call {
	_c.Call.Return()
	return _c
}

func (_c *ProfilingStore_RecordExecution_Call) RunAndReturn(run func(profiling.StrategyMetrics)) *ProfilingStore_RecordExecution_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *ProfilingStore) Stop() {
	_m.Called()
}

// ProfilingStore_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type ProfilingStore_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *ProfilingStore_Expecter) Stop() *ProfilingStore_Stop_Call {
	return &ProfilingStore_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *ProfilingStore_Stop_Call) Run(run func()) *ProfilingStore_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProfilingStore_Stop_Call) Return() *ProfilingStore_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *ProfilingStore_Stop_Call) RunAndReturn(run func()) *ProfilingStore_Stop_Call {
	_c.Run(run)
	return _c
}

// NewProfilingStore creates a new instance of ProfilingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfilingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfilingStore {
	mock := &ProfilingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
