// Code generated by mockery v2.53.5. DO NOT EDIT.

package activity

import (
	connector "github.com/backtesting-org/kronos-sdk/pkg/types/connector"
	mock "github.com/stretchr/testify/mock"

	strategy "github.com/backtesting-org/kronos-sdk/pkg/types/strategy"
)

// Positions is an autogenerated mock type for the Positions type
type Positions struct {
	mock.Mock
}

type Positions_Expecter struct {
	mock *mock.Mock
}

func (_m *Positions) EXPECT() *Positions_Expecter {
	return &Positions_Expecter{mock: &_m.Mock}
}

// GetAllStrategyExecutions provides a mock function with no fields
func (_m *Positions) GetAllStrategyExecutions() map[strategy.StrategyName]*strategy.StrategyExecution {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllStrategyExecutions")
	}

	var r0 map[strategy.StrategyName]*strategy.StrategyExecution
	if rf, ok := ret.Get(0).(func() map[strategy.StrategyName]*strategy.StrategyExecution); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[strategy.StrategyName]*strategy.StrategyExecution)
		}
	}

	return r0
}

// Positions_GetAllStrategyExecutions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStrategyExecutions'
type Positions_GetAllStrategyExecutions_Call struct {
	*mock.Call
}

// GetAllStrategyExecutions is a helper method to define mock.On call
func (_e *Positions_Expecter) GetAllStrategyExecutions() *Positions_GetAllStrategyExecutions_Call {
	return &Positions_GetAllStrategyExecutions_Call{Call: _e.mock.On("GetAllStrategyExecutions")}
}

func (_c *Positions_GetAllStrategyExecutions_Call) Run(run func()) *Positions_GetAllStrategyExecutions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Positions_GetAllStrategyExecutions_Call) Return(_a0 map[strategy.StrategyName]*strategy.StrategyExecution) *Positions_GetAllStrategyExecutions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Positions_GetAllStrategyExecutions_Call) RunAndReturn(run func() map[strategy.StrategyName]*strategy.StrategyExecution) *Positions_GetAllStrategyExecutions_Call {
	_c.Call.Return(run)
	return _c
}

// GetStrategyExecution provides a mock function with given fields: _a0
func (_m *Positions) GetStrategyExecution(_a0 strategy.StrategyName) *strategy.StrategyExecution {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetStrategyExecution")
	}

	var r0 *strategy.StrategyExecution
	if rf, ok := ret.Get(0).(func(strategy.StrategyName) *strategy.StrategyExecution); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*strategy.StrategyExecution)
		}
	}

	return r0
}

// Positions_GetStrategyExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStrategyExecution'
type Positions_GetStrategyExecution_Call struct {
	*mock.Call
}

// GetStrategyExecution is a helper method to define mock.On call
//   - _a0 strategy.StrategyName
func (_e *Positions_Expecter) GetStrategyExecution(_a0 interface{}) *Positions_GetStrategyExecution_Call {
	return &Positions_GetStrategyExecution_Call{Call: _e.mock.On("GetStrategyExecution", _a0)}
}

func (_c *Positions_GetStrategyExecution_Call) Run(run func(_a0 strategy.StrategyName)) *Positions_GetStrategyExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(strategy.StrategyName))
	})
	return _c
}

func (_c *Positions_GetStrategyExecution_Call) Return(_a0 *strategy.StrategyExecution) *Positions_GetStrategyExecution_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Positions_GetStrategyExecution_Call) RunAndReturn(run func(strategy.StrategyName) *strategy.StrategyExecution) *Positions_GetStrategyExecution_Call {
	_c.Call.Return(run)
	return _c
}

// GetStrategyForOrder provides a mock function with given fields: orderID
func (_m *Positions) GetStrategyForOrder(orderID string) (strategy.StrategyName, bool) {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetStrategyForOrder")
	}

	var r0 strategy.StrategyName
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (strategy.StrategyName, bool)); ok {
		return rf(orderID)
	}
	if rf, ok := ret.Get(0).(func(string) strategy.StrategyName); ok {
		r0 = rf(orderID)
	} else {
		r0 = ret.Get(0).(strategy.StrategyName)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(orderID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Positions_GetStrategyForOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStrategyForOrder'
type Positions_GetStrategyForOrder_Call struct {
	*mock.Call
}

// GetStrategyForOrder is a helper method to define mock.On call
//   - orderID string
func (_e *Positions_Expecter) GetStrategyForOrder(orderID interface{}) *Positions_GetStrategyForOrder_Call {
	return &Positions_GetStrategyForOrder_Call{Call: _e.mock.On("GetStrategyForOrder", orderID)}
}

func (_c *Positions_GetStrategyForOrder_Call) Run(run func(orderID string)) *Positions_GetStrategyForOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Positions_GetStrategyForOrder_Call) Return(_a0 strategy.StrategyName, _a1 bool) *Positions_GetStrategyForOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Positions_GetStrategyForOrder_Call) RunAndReturn(run func(string) (strategy.StrategyName, bool)) *Positions_GetStrategyForOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalOrderCount provides a mock function with no fields
func (_m *Positions) GetTotalOrderCount() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTotalOrderCount")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Positions_GetTotalOrderCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalOrderCount'
type Positions_GetTotalOrderCount_Call struct {
	*mock.Call
}

// GetTotalOrderCount is a helper method to define mock.On call
func (_e *Positions_Expecter) GetTotalOrderCount() *Positions_GetTotalOrderCount_Call {
	return &Positions_GetTotalOrderCount_Call{Call: _e.mock.On("GetTotalOrderCount")}
}

func (_c *Positions_GetTotalOrderCount_Call) Run(run func()) *Positions_GetTotalOrderCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Positions_GetTotalOrderCount_Call) Return(_a0 int64) *Positions_GetTotalOrderCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Positions_GetTotalOrderCount_Call) RunAndReturn(run func() int64) *Positions_GetTotalOrderCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradesForStrategy provides a mock function with given fields: _a0
func (_m *Positions) GetTradesForStrategy(_a0 strategy.StrategyName) []connector.Trade {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetTradesForStrategy")
	}

	var r0 []connector.Trade
	if rf, ok := ret.Get(0).(func(strategy.StrategyName) []connector.Trade); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}

	return r0
}

// Positions_GetTradesForStrategy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradesForStrategy'
type Positions_GetTradesForStrategy_Call struct {
	*mock.Call
}

// GetTradesForStrategy is a helper method to define mock.On call
//   - _a0 strategy.StrategyName
func (_e *Positions_Expecter) GetTradesForStrategy(_a0 interface{}) *Positions_GetTradesForStrategy_Call {
	return &Positions_GetTradesForStrategy_Call{Call: _e.mock.On("GetTradesForStrategy", _a0)}
}

func (_c *Positions_GetTradesForStrategy_Call) Run(run func(_a0 strategy.StrategyName)) *Positions_GetTradesForStrategy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(strategy.StrategyName))
	})
	return _c
}

func (_c *Positions_GetTradesForStrategy_Call) Return(_a0 []connector.Trade) *Positions_GetTradesForStrategy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Positions_GetTradesForStrategy_Call) RunAndReturn(run func(strategy.StrategyName) []connector.Trade) *Positions_GetTradesForStrategy_Call {
	_c.Call.Return(run)
	return _c
}

// NewPositions creates a new instance of Positions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPositions(t interface {
	mock.TestingT
	Cleanup(func())
}) *Positions {
	mock := &Positions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
