// Code generated by mockery v2.53.5. DO NOT EDIT.

package batch

import (
	batch "github.com/backtesting-org/kronos-sdk/pkg/types/data/ingestors/batch"
	mock "github.com/stretchr/testify/mock"
)

// BatchIngestorFactory is an autogenerated mock type for the BatchIngestorFactory type
type BatchIngestorFactory struct {
	mock.Mock
}

type BatchIngestorFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *BatchIngestorFactory) EXPECT() *BatchIngestorFactory_Expecter {
	return &BatchIngestorFactory_Expecter{mock: &_m.Mock}
}

// CreateIngestors provides a mock function with no fields
func (_m *BatchIngestorFactory) CreateIngestors() []batch.BatchIngestor {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateIngestors")
	}

	var r0 []batch.BatchIngestor
	if rf, ok := ret.Get(0).(func() []batch.BatchIngestor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]batch.BatchIngestor)
		}
	}

	return r0
}

// BatchIngestorFactory_CreateIngestors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngestors'
type BatchIngestorFactory_CreateIngestors_Call struct {
	*mock.Call
}

// CreateIngestors is a helper method to define mock.On call
func (_e *BatchIngestorFactory_Expecter) CreateIngestors() *BatchIngestorFactory_CreateIngestors_Call {
	return &BatchIngestorFactory_CreateIngestors_Call{Call: _e.mock.On("CreateIngestors")}
}

func (_c *BatchIngestorFactory_CreateIngestors_Call) Run(run func()) *BatchIngestorFactory_CreateIngestors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BatchIngestorFactory_CreateIngestors_Call) Return(_a0 []batch.BatchIngestor) *BatchIngestorFactory_CreateIngestors_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BatchIngestorFactory_CreateIngestors_Call) RunAndReturn(run func() []batch.BatchIngestor) *BatchIngestorFactory_CreateIngestors_Call {
	_c.Call.Return(run)
	return _c
}

// NewBatchIngestorFactory creates a new instance of BatchIngestorFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBatchIngestorFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *BatchIngestorFactory {
	mock := &BatchIngestorFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
