// Code generated by mockery v2.53.5. DO NOT EDIT.

package activity

import (
	context "context"

	activity "github.com/wisp-trading/sdk/pkg/types/wisp/activity"

	mock "github.com/stretchr/testify/mock"

	numerical "github.com/wisp-trading/sdk/pkg/types/wisp/numerical"
)

// SpotPNL is an autogenerated mock type for the SpotPNL type
type SpotPNL struct {
	mock.Mock
}

type SpotPNL_Expecter struct {
	mock *mock.Mock
}

func (_m *SpotPNL) EXPECT() *SpotPNL_Expecter {
	return &SpotPNL_Expecter{mock: &_m.Mock}
}

// Fees provides a mock function with given fields: ctx
func (_m *SpotPNL) Fees(ctx context.Context) numerical.Decimal {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Fees")
	}

	var r0 numerical.Decimal
	if rf, ok := ret.Get(0).(func(context.Context) numerical.Decimal); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(numerical.Decimal)
	}

	return r0
}

// SpotPNL_Fees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fees'
type SpotPNL_Fees_Call struct {
	*mock.Call
}

// Fees is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SpotPNL_Expecter) Fees(ctx interface{}) *SpotPNL_Fees_Call {
	return &SpotPNL_Fees_Call{Call: _e.mock.On("Fees", ctx)}
}

func (_c *SpotPNL_Fees_Call) Run(run func(ctx context.Context)) *SpotPNL_Fees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SpotPNL_Fees_Call) Return(_a0 numerical.Decimal) *SpotPNL_Fees_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpotPNL_Fees_Call) RunAndReturn(run func(context.Context) numerical.Decimal) *SpotPNL_Fees_Call {
	_c.Call.Return(run)
	return _c
}

// Positions provides a mock function with given fields: ctx
func (_m *SpotPNL) Positions(ctx context.Context) []activity.PositionPNL {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Positions")
	}

	var r0 []activity.PositionPNL
	if rf, ok := ret.Get(0).(func(context.Context) []activity.PositionPNL); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]activity.PositionPNL)
		}
	}

	return r0
}

// SpotPNL_Positions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Positions'
type SpotPNL_Positions_Call struct {
	*mock.Call
}

// Positions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SpotPNL_Expecter) Positions(ctx interface{}) *SpotPNL_Positions_Call {
	return &SpotPNL_Positions_Call{Call: _e.mock.On("Positions", ctx)}
}

func (_c *SpotPNL_Positions_Call) Run(run func(ctx context.Context)) *SpotPNL_Positions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SpotPNL_Positions_Call) Return(_a0 []activity.PositionPNL) *SpotPNL_Positions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpotPNL_Positions_Call) RunAndReturn(run func(context.Context) []activity.PositionPNL) *SpotPNL_Positions_Call {
	_c.Call.Return(run)
	return _c
}

// Realized provides a mock function with given fields: ctx
func (_m *SpotPNL) Realized(ctx context.Context) numerical.Decimal {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Realized")
	}

	var r0 numerical.Decimal
	if rf, ok := ret.Get(0).(func(context.Context) numerical.Decimal); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(numerical.Decimal)
	}

	return r0
}

// SpotPNL_Realized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Realized'
type SpotPNL_Realized_Call struct {
	*mock.Call
}

// Realized is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SpotPNL_Expecter) Realized(ctx interface{}) *SpotPNL_Realized_Call {
	return &SpotPNL_Realized_Call{Call: _e.mock.On("Realized", ctx)}
}

func (_c *SpotPNL_Realized_Call) Run(run func(ctx context.Context)) *SpotPNL_Realized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SpotPNL_Realized_Call) Return(_a0 numerical.Decimal) *SpotPNL_Realized_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpotPNL_Realized_Call) RunAndReturn(run func(context.Context) numerical.Decimal) *SpotPNL_Realized_Call {
	_c.Call.Return(run)
	return _c
}

// Unrealized provides a mock function with given fields: ctx
func (_m *SpotPNL) Unrealized(ctx context.Context) numerical.Decimal {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Unrealized")
	}

	var r0 numerical.Decimal
	if rf, ok := ret.Get(0).(func(context.Context) numerical.Decimal); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(numerical.Decimal)
	}

	return r0
}

// SpotPNL_Unrealized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unrealized'
type SpotPNL_Unrealized_Call struct {
	*mock.Call
}

// Unrealized is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SpotPNL_Expecter) Unrealized(ctx interface{}) *SpotPNL_Unrealized_Call {
	return &SpotPNL_Unrealized_Call{Call: _e.mock.On("Unrealized", ctx)}
}

func (_c *SpotPNL_Unrealized_Call) Run(run func(ctx context.Context)) *SpotPNL_Unrealized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SpotPNL_Unrealized_Call) Return(_a0 numerical.Decimal) *SpotPNL_Unrealized_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpotPNL_Unrealized_Call) RunAndReturn(run func(context.Context) numerical.Decimal) *SpotPNL_Unrealized_Call {
	_c.Call.Return(run)
	return _c
}

// NewSpotPNL creates a new instance of SpotPNL. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpotPNL(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpotPNL {
	mock := &SpotPNL{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
