// Code generated by mockery v2.53.5. DO NOT EDIT.

package connector

import mock "github.com/stretchr/testify/mock"

// WebSocketCapable is an autogenerated mock type for the WebSocketCapable type
type WebSocketCapable struct {
	mock.Mock
}

type WebSocketCapable_Expecter struct {
	mock *mock.Mock
}

func (_m *WebSocketCapable) EXPECT() *WebSocketCapable_Expecter {
	return &WebSocketCapable_Expecter{mock: &_m.Mock}
}

// ErrorChannel provides a mock function with no fields
func (_m *WebSocketCapable) ErrorChannel() <-chan error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ErrorChannel")
	}

	var r0 <-chan error
	if rf, ok := ret.Get(0).(func() <-chan error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}

	return r0
}

// WebSocketCapable_ErrorChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorChannel'
type WebSocketCapable_ErrorChannel_Call struct {
	*mock.Call
}

// ErrorChannel is a helper method to define mock.On call
func (_e *WebSocketCapable_Expecter) ErrorChannel() *WebSocketCapable_ErrorChannel_Call {
	return &WebSocketCapable_ErrorChannel_Call{Call: _e.mock.On("ErrorChannel")}
}

func (_c *WebSocketCapable_ErrorChannel_Call) Run(run func()) *WebSocketCapable_ErrorChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketCapable_ErrorChannel_Call) Return(_a0 <-chan error) *WebSocketCapable_ErrorChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketCapable_ErrorChannel_Call) RunAndReturn(run func() <-chan error) *WebSocketCapable_ErrorChannel_Call {
	_c.Call.Return(run)
	return _c
}

// IsWebSocketConnected provides a mock function with no fields
func (_m *WebSocketCapable) IsWebSocketConnected() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsWebSocketConnected")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// WebSocketCapable_IsWebSocketConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsWebSocketConnected'
type WebSocketCapable_IsWebSocketConnected_Call struct {
	*mock.Call
}

// IsWebSocketConnected is a helper method to define mock.On call
func (_e *WebSocketCapable_Expecter) IsWebSocketConnected() *WebSocketCapable_IsWebSocketConnected_Call {
	return &WebSocketCapable_IsWebSocketConnected_Call{Call: _e.mock.On("IsWebSocketConnected")}
}

func (_c *WebSocketCapable_IsWebSocketConnected_Call) Run(run func()) *WebSocketCapable_IsWebSocketConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketCapable_IsWebSocketConnected_Call) Return(_a0 bool) *WebSocketCapable_IsWebSocketConnected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketCapable_IsWebSocketConnected_Call) RunAndReturn(run func() bool) *WebSocketCapable_IsWebSocketConnected_Call {
	_c.Call.Return(run)
	return _c
}

// StartWebSocket provides a mock function with no fields
func (_m *WebSocketCapable) StartWebSocket() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartWebSocket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebSocketCapable_StartWebSocket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartWebSocket'
type WebSocketCapable_StartWebSocket_Call struct {
	*mock.Call
}

// StartWebSocket is a helper method to define mock.On call
func (_e *WebSocketCapable_Expecter) StartWebSocket() *WebSocketCapable_StartWebSocket_Call {
	return &WebSocketCapable_StartWebSocket_Call{Call: _e.mock.On("StartWebSocket")}
}

func (_c *WebSocketCapable_StartWebSocket_Call) Run(run func()) *WebSocketCapable_StartWebSocket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketCapable_StartWebSocket_Call) Return(_a0 error) *WebSocketCapable_StartWebSocket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketCapable_StartWebSocket_Call) RunAndReturn(run func() error) *WebSocketCapable_StartWebSocket_Call {
	_c.Call.Return(run)
	return _c
}

// StopWebSocket provides a mock function with no fields
func (_m *WebSocketCapable) StopWebSocket() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopWebSocket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebSocketCapable_StopWebSocket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopWebSocket'
type WebSocketCapable_StopWebSocket_Call struct {
	*mock.Call
}

// StopWebSocket is a helper method to define mock.On call
func (_e *WebSocketCapable_Expecter) StopWebSocket() *WebSocketCapable_StopWebSocket_Call {
	return &WebSocketCapable_StopWebSocket_Call{Call: _e.mock.On("StopWebSocket")}
}

func (_c *WebSocketCapable_StopWebSocket_Call) Run(run func()) *WebSocketCapable_StopWebSocket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebSocketCapable_StopWebSocket_Call) Return(_a0 error) *WebSocketCapable_StopWebSocket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebSocketCapable_StopWebSocket_Call) RunAndReturn(run func() error) *WebSocketCapable_StopWebSocket_Call {
	_c.Call.Return(run)
	return _c
}

// NewWebSocketCapable creates a new instance of WebSocketCapable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebSocketCapable(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebSocketCapable {
	mock := &WebSocketCapable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
