// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ingestors

import (
	mock "github.com/stretchr/testify/mock"
)

// NewDataUpdateNotifier creates a new instance of DataUpdateNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataUpdateNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataUpdateNotifier {
	mock := &DataUpdateNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DataUpdateNotifier is an autogenerated mock type for the DataUpdateNotifier type
type DataUpdateNotifier struct {
	mock.Mock
}

type DataUpdateNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *DataUpdateNotifier) EXPECT() *DataUpdateNotifier_Expecter {
	return &DataUpdateNotifier_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function for the type DataUpdateNotifier
func (_mock *DataUpdateNotifier) Notify() {
	_mock.Called()
	return
}

// DataUpdateNotifier_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type DataUpdateNotifier_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
func (_e *DataUpdateNotifier_Expecter) Notify() *DataUpdateNotifier_Notify_Call {
	return &DataUpdateNotifier_Notify_Call{Call: _e.mock.On("Notify")}
}

func (_c *DataUpdateNotifier_Notify_Call) Run(run func()) *DataUpdateNotifier_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DataUpdateNotifier_Notify_Call) Return() *DataUpdateNotifier_Notify_Call {
	_c.Call.Return()
	return _c
}

func (_c *DataUpdateNotifier_Notify_Call) RunAndReturn(run func()) *DataUpdateNotifier_Notify_Call {
	_c.Run(run)
	return _c
}

// Updates provides a mock function for the type DataUpdateNotifier
func (_mock *DataUpdateNotifier) Updates() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Updates")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// DataUpdateNotifier_Updates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Updates'
type DataUpdateNotifier_Updates_Call struct {
	*mock.Call
}

// Updates is a helper method to define mock.On call
func (_e *DataUpdateNotifier_Expecter) Updates() *DataUpdateNotifier_Updates_Call {
	return &DataUpdateNotifier_Updates_Call{Call: _e.mock.On("Updates")}
}

func (_c *DataUpdateNotifier_Updates_Call) Run(run func()) *DataUpdateNotifier_Updates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DataUpdateNotifier_Updates_Call) Return(valCh <-chan struct{}) *DataUpdateNotifier_Updates_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *DataUpdateNotifier_Updates_Call) RunAndReturn(run func() <-chan struct{}) *DataUpdateNotifier_Updates_Call {
	_c.Call.Return(run)
	return _c
}
