// Code generated by mockery v2.53.5. DO NOT EDIT.

package perp

import (
	mock "github.com/stretchr/testify/mock"
	perp "github.com/wisp-trading/wisp/pkg/types/connector/perp"
	portfolio "github.com/wisp-trading/wisp/pkg/types/portfolio"
)

// FundingRateProvider is an autogenerated mock type for the FundingRateProvider type
type FundingRateProvider struct {
	mock.Mock
}

type FundingRateProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *FundingRateProvider) EXPECT() *FundingRateProvider_Expecter {
	return &FundingRateProvider_Expecter{mock: &_m.Mock}
}

// FetchCurrentFundingRates provides a mock function with no fields
func (_m *FundingRateProvider) FetchCurrentFundingRates() (map[portfolio.Asset]perp.FundingRate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchCurrentFundingRates")
	}

	var r0 map[portfolio.Asset]perp.FundingRate
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[portfolio.Asset]perp.FundingRate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[portfolio.Asset]perp.FundingRate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[portfolio.Asset]perp.FundingRate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FundingRateProvider_FetchCurrentFundingRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCurrentFundingRates'
type FundingRateProvider_FetchCurrentFundingRates_Call struct {
	*mock.Call
}

// FetchCurrentFundingRates is a helper method to define mock.On call
func (_e *FundingRateProvider_Expecter) FetchCurrentFundingRates() *FundingRateProvider_FetchCurrentFundingRates_Call {
	return &FundingRateProvider_FetchCurrentFundingRates_Call{Call: _e.mock.On("FetchCurrentFundingRates")}
}

func (_c *FundingRateProvider_FetchCurrentFundingRates_Call) Run(run func()) *FundingRateProvider_FetchCurrentFundingRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FundingRateProvider_FetchCurrentFundingRates_Call) Return(_a0 map[portfolio.Asset]perp.FundingRate, _a1 error) *FundingRateProvider_FetchCurrentFundingRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FundingRateProvider_FetchCurrentFundingRates_Call) RunAndReturn(run func() (map[portfolio.Asset]perp.FundingRate, error)) *FundingRateProvider_FetchCurrentFundingRates_Call {
	_c.Call.Return(run)
	return _c
}

// FetchFundingRate provides a mock function with given fields: asset
func (_m *FundingRateProvider) FetchFundingRate(asset portfolio.Asset) (*perp.FundingRate, error) {
	ret := _m.Called(asset)

	if len(ret) == 0 {
		panic("no return value specified for FetchFundingRate")
	}

	var r0 *perp.FundingRate
	var r1 error
	if rf, ok := ret.Get(0).(func(portfolio.Asset) (*perp.FundingRate, error)); ok {
		return rf(asset)
	}
	if rf, ok := ret.Get(0).(func(portfolio.Asset) *perp.FundingRate); ok {
		r0 = rf(asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*perp.FundingRate)
		}
	}

	if rf, ok := ret.Get(1).(func(portfolio.Asset) error); ok {
		r1 = rf(asset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FundingRateProvider_FetchFundingRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchFundingRate'
type FundingRateProvider_FetchFundingRate_Call struct {
	*mock.Call
}

// FetchFundingRate is a helper method to define mock.On call
//   - asset portfolio.Asset
func (_e *FundingRateProvider_Expecter) FetchFundingRate(asset interface{}) *FundingRateProvider_FetchFundingRate_Call {
	return &FundingRateProvider_FetchFundingRate_Call{Call: _e.mock.On("FetchFundingRate", asset)}
}

func (_c *FundingRateProvider_FetchFundingRate_Call) Run(run func(asset portfolio.Asset)) *FundingRateProvider_FetchFundingRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Asset))
	})
	return _c
}

func (_c *FundingRateProvider_FetchFundingRate_Call) Return(_a0 *perp.FundingRate, _a1 error) *FundingRateProvider_FetchFundingRate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FundingRateProvider_FetchFundingRate_Call) RunAndReturn(run func(portfolio.Asset) (*perp.FundingRate, error)) *FundingRateProvider_FetchFundingRate_Call {
	_c.Call.Return(run)
	return _c
}

// FetchHistoricalFundingRates provides a mock function with given fields: asset, startTime, endTime
func (_m *FundingRateProvider) FetchHistoricalFundingRates(asset portfolio.Asset, startTime int64, endTime int64) ([]perp.HistoricalFundingRate, error) {
	ret := _m.Called(asset, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for FetchHistoricalFundingRates")
	}

	var r0 []perp.HistoricalFundingRate
	var r1 error
	if rf, ok := ret.Get(0).(func(portfolio.Asset, int64, int64) ([]perp.HistoricalFundingRate, error)); ok {
		return rf(asset, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(portfolio.Asset, int64, int64) []perp.HistoricalFundingRate); ok {
		r0 = rf(asset, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]perp.HistoricalFundingRate)
		}
	}

	if rf, ok := ret.Get(1).(func(portfolio.Asset, int64, int64) error); ok {
		r1 = rf(asset, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FundingRateProvider_FetchHistoricalFundingRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchHistoricalFundingRates'
type FundingRateProvider_FetchHistoricalFundingRates_Call struct {
	*mock.Call
}

// FetchHistoricalFundingRates is a helper method to define mock.On call
//   - asset portfolio.Asset
//   - startTime int64
//   - endTime int64
func (_e *FundingRateProvider_Expecter) FetchHistoricalFundingRates(asset interface{}, startTime interface{}, endTime interface{}) *FundingRateProvider_FetchHistoricalFundingRates_Call {
	return &FundingRateProvider_FetchHistoricalFundingRates_Call{Call: _e.mock.On("FetchHistoricalFundingRates", asset, startTime, endTime)}
}

func (_c *FundingRateProvider_FetchHistoricalFundingRates_Call) Run(run func(asset portfolio.Asset, startTime int64, endTime int64)) *FundingRateProvider_FetchHistoricalFundingRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Asset), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FundingRateProvider_FetchHistoricalFundingRates_Call) Return(_a0 []perp.HistoricalFundingRate, _a1 error) *FundingRateProvider_FetchHistoricalFundingRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FundingRateProvider_FetchHistoricalFundingRates_Call) RunAndReturn(run func(portfolio.Asset, int64, int64) ([]perp.HistoricalFundingRate, error)) *FundingRateProvider_FetchHistoricalFundingRates_Call {
	_c.Call.Return(run)
	return _c
}

// NewFundingRateProvider creates a new instance of FundingRateProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFundingRateProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *FundingRateProvider {
	mock := &FundingRateProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
