// Code generated by mockery v2.53.5. DO NOT EDIT.

package config

import (
	mock "github.com/stretchr/testify/mock"
	config "github.com/wisp-trading/sdk/pkg/types/config"
)

// Configuration is an autogenerated mock type for the Configuration type
type Configuration struct {
	mock.Mock
}

type Configuration_Expecter struct {
	mock *mock.Mock
}

func (_m *Configuration) EXPECT() *Configuration_Expecter {
	return &Configuration_Expecter{mock: &_m.Mock}
}

// AddConnector provides a mock function with given fields: connector
func (_m *Configuration) AddConnector(connector config.Connector) error {
	ret := _m.Called(connector)

	if len(ret) == 0 {
		panic("no return value specified for AddConnector")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(config.Connector) error); ok {
		r0 = rf(connector)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Configuration_AddConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddConnector'
type Configuration_AddConnector_Call struct {
	*mock.Call
}

// AddConnector is a helper method to define mock.On call
//   - connector config.Connector
func (_e *Configuration_Expecter) AddConnector(connector interface{}) *Configuration_AddConnector_Call {
	return &Configuration_AddConnector_Call{Call: _e.mock.On("AddConnector", connector)}
}

func (_c *Configuration_AddConnector_Call) Run(run func(connector config.Connector)) *Configuration_AddConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.Connector))
	})
	return _c
}

func (_c *Configuration_AddConnector_Call) Return(_a0 error) *Configuration_AddConnector_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Configuration_AddConnector_Call) RunAndReturn(run func(config.Connector) error) *Configuration_AddConnector_Call {
	_c.Call.Return(run)
	return _c
}

// EnableConnector provides a mock function with given fields: name, enabled
func (_m *Configuration) EnableConnector(name string, enabled bool) error {
	ret := _m.Called(name, enabled)

	if len(ret) == 0 {
		panic("no return value specified for EnableConnector")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(name, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Configuration_EnableConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableConnector'
type Configuration_EnableConnector_Call struct {
	*mock.Call
}

// EnableConnector is a helper method to define mock.On call
//   - name string
//   - enabled bool
func (_e *Configuration_Expecter) EnableConnector(name interface{}, enabled interface{}) *Configuration_EnableConnector_Call {
	return &Configuration_EnableConnector_Call{Call: _e.mock.On("EnableConnector", name, enabled)}
}

func (_c *Configuration_EnableConnector_Call) Run(run func(name string, enabled bool)) *Configuration_EnableConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *Configuration_EnableConnector_Call) Return(_a0 error) *Configuration_EnableConnector_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Configuration_EnableConnector_Call) RunAndReturn(run func(string, bool) error) *Configuration_EnableConnector_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectors provides a mock function with no fields
func (_m *Configuration) GetConnectors() ([]config.Connector, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConnectors")
	}

	var r0 []config.Connector
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]config.Connector, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []config.Connector); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.Connector)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Configuration_GetConnectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectors'
type Configuration_GetConnectors_Call struct {
	*mock.Call
}

// GetConnectors is a helper method to define mock.On call
func (_e *Configuration_Expecter) GetConnectors() *Configuration_GetConnectors_Call {
	return &Configuration_GetConnectors_Call{Call: _e.mock.On("GetConnectors")}
}

func (_c *Configuration_GetConnectors_Call) Run(run func()) *Configuration_GetConnectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Configuration_GetConnectors_Call) Return(_a0 []config.Connector, _a1 error) *Configuration_GetConnectors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Configuration_GetConnectors_Call) RunAndReturn(run func() ([]config.Connector, error)) *Configuration_GetConnectors_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnabledConnectors provides a mock function with no fields
func (_m *Configuration) GetEnabledConnectors() ([]config.Connector, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEnabledConnectors")
	}

	var r0 []config.Connector
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]config.Connector, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []config.Connector); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.Connector)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Configuration_GetEnabledConnectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnabledConnectors'
type Configuration_GetEnabledConnectors_Call struct {
	*mock.Call
}

// GetEnabledConnectors is a helper method to define mock.On call
func (_e *Configuration_Expecter) GetEnabledConnectors() *Configuration_GetEnabledConnectors_Call {
	return &Configuration_GetEnabledConnectors_Call{Call: _e.mock.On("GetEnabledConnectors")}
}

func (_c *Configuration_GetEnabledConnectors_Call) Run(run func()) *Configuration_GetEnabledConnectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Configuration_GetEnabledConnectors_Call) Return(_a0 []config.Connector, _a1 error) *Configuration_GetEnabledConnectors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Configuration_GetEnabledConnectors_Call) RunAndReturn(run func() ([]config.Connector, error)) *Configuration_GetEnabledConnectors_Call {
	_c.Call.Return(run)
	return _c
}

// LoadSettings provides a mock function with given fields: path
func (_m *Configuration) LoadSettings(path string) (*config.Settings, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for LoadSettings")
	}

	var r0 *config.Settings
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*config.Settings, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) *config.Settings); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Settings)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Configuration_LoadSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadSettings'
type Configuration_LoadSettings_Call struct {
	*mock.Call
}

// LoadSettings is a helper method to define mock.On call
//   - path string
func (_e *Configuration_Expecter) LoadSettings(path interface{}) *Configuration_LoadSettings_Call {
	return &Configuration_LoadSettings_Call{Call: _e.mock.On("LoadSettings", path)}
}

func (_c *Configuration_LoadSettings_Call) Run(run func(path string)) *Configuration_LoadSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Configuration_LoadSettings_Call) Return(_a0 *config.Settings, _a1 error) *Configuration_LoadSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Configuration_LoadSettings_Call) RunAndReturn(run func(string) (*config.Settings, error)) *Configuration_LoadSettings_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveConnector provides a mock function with given fields: name
func (_m *Configuration) RemoveConnector(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for RemoveConnector")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Configuration_RemoveConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveConnector'
type Configuration_RemoveConnector_Call struct {
	*mock.Call
}

// RemoveConnector is a helper method to define mock.On call
//   - name string
func (_e *Configuration_Expecter) RemoveConnector(name interface{}) *Configuration_RemoveConnector_Call {
	return &Configuration_RemoveConnector_Call{Call: _e.mock.On("RemoveConnector", name)}
}

func (_c *Configuration_RemoveConnector_Call) Run(run func(name string)) *Configuration_RemoveConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Configuration_RemoveConnector_Call) Return(_a0 error) *Configuration_RemoveConnector_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Configuration_RemoveConnector_Call) RunAndReturn(run func(string) error) *Configuration_RemoveConnector_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSettings provides a mock function with given fields: settings
func (_m *Configuration) SaveSettings(settings *config.Settings) error {
	ret := _m.Called(settings)

	if len(ret) == 0 {
		panic("no return value specified for SaveSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.Settings) error); ok {
		r0 = rf(settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Configuration_SaveSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSettings'
type Configuration_SaveSettings_Call struct {
	*mock.Call
}

// SaveSettings is a helper method to define mock.On call
//   - settings *config.Settings
func (_e *Configuration_Expecter) SaveSettings(settings interface{}) *Configuration_SaveSettings_Call {
	return &Configuration_SaveSettings_Call{Call: _e.mock.On("SaveSettings", settings)}
}

func (_c *Configuration_SaveSettings_Call) Run(run func(settings *config.Settings)) *Configuration_SaveSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.Settings))
	})
	return _c
}

func (_c *Configuration_SaveSettings_Call) Return(_a0 error) *Configuration_SaveSettings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Configuration_SaveSettings_Call) RunAndReturn(run func(*config.Settings) error) *Configuration_SaveSettings_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConnector provides a mock function with given fields: connector
func (_m *Configuration) UpdateConnector(connector config.Connector) error {
	ret := _m.Called(connector)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConnector")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(config.Connector) error); ok {
		r0 = rf(connector)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Configuration_UpdateConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConnector'
type Configuration_UpdateConnector_Call struct {
	*mock.Call
}

// UpdateConnector is a helper method to define mock.On call
//   - connector config.Connector
func (_e *Configuration_Expecter) UpdateConnector(connector interface{}) *Configuration_UpdateConnector_Call {
	return &Configuration_UpdateConnector_Call{Call: _e.mock.On("UpdateConnector", connector)}
}

func (_c *Configuration_UpdateConnector_Call) Run(run func(connector config.Connector)) *Configuration_UpdateConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.Connector))
	})
	return _c
}

func (_c *Configuration_UpdateConnector_Call) Return(_a0 error) *Configuration_UpdateConnector_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Configuration_UpdateConnector_Call) RunAndReturn(run func(config.Connector) error) *Configuration_UpdateConnector_Call {
	_c.Call.Return(run)
	return _c
}

// NewConfiguration creates a new instance of Configuration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfiguration(t interface {
	mock.TestingT
	Cleanup(func())
}) *Configuration {
	mock := &Configuration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
