// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/types/config"
)

// NewStartupConfigLoader creates a new instance of StartupConfigLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStartupConfigLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *StartupConfigLoader {
	mock := &StartupConfigLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StartupConfigLoader is an autogenerated mock type for the StartupConfigLoader type
type StartupConfigLoader struct {
	mock.Mock
}

type StartupConfigLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *StartupConfigLoader) EXPECT() *StartupConfigLoader_Expecter {
	return &StartupConfigLoader_Expecter{mock: &_m.Mock}
}

// LoadForStrategy provides a mock function for the type StartupConfigLoader
func (_mock *StartupConfigLoader) LoadForStrategy(strategyDir string, wispPath string) (*config.StartupConfig, error) {
	ret := _mock.Called(strategyDir, wispPath)

	if len(ret) == 0 {
		panic("no return value specified for LoadForStrategy")
	}

	var r0 *config.StartupConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*config.StartupConfig, error)); ok {
		return returnFunc(strategyDir, wispPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *config.StartupConfig); ok {
		r0 = returnFunc(strategyDir, wispPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.StartupConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(strategyDir, wispPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StartupConfigLoader_LoadForStrategy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadForStrategy'
type StartupConfigLoader_LoadForStrategy_Call struct {
	*mock.Call
}

// LoadForStrategy is a helper method to define mock.On call
//   - strategyDir string
//   - wispPath string
func (_e *StartupConfigLoader_Expecter) LoadForStrategy(strategyDir interface{}, wispPath interface{}) *StartupConfigLoader_LoadForStrategy_Call {
	return &StartupConfigLoader_LoadForStrategy_Call{Call: _e.mock.On("LoadForStrategy", strategyDir, wispPath)}
}

func (_c *StartupConfigLoader_LoadForStrategy_Call) Run(run func(strategyDir string, wispPath string)) *StartupConfigLoader_LoadForStrategy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StartupConfigLoader_LoadForStrategy_Call) Return(startupConfig *config.StartupConfig, err error) *StartupConfigLoader_LoadForStrategy_Call {
	_c.Call.Return(startupConfig, err)
	return _c
}

func (_c *StartupConfigLoader_LoadForStrategy_Call) RunAndReturn(run func(strategyDir string, wispPath string) (*config.StartupConfig, error)) *StartupConfigLoader_LoadForStrategy_Call {
	_c.Call.Return(run)
	return _c
}
