// Code generated by mockery v2.53.5. DO NOT EDIT.

package market

import (
	market "github.com/backtesting-org/kronos-sdk/pkg/types/data/stores/market"
	mock "github.com/stretchr/testify/mock"
)

// MarketRegistry is an autogenerated mock type for the MarketRegistry type
type MarketRegistry struct {
	mock.Mock
}

type MarketRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MarketRegistry) EXPECT() *MarketRegistry_Expecter {
	return &MarketRegistry_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: marketType
func (_m *MarketRegistry) Get(marketType market.MarketType) market.MarketStore {
	ret := _m.Called(marketType)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 market.MarketStore
	if rf, ok := ret.Get(0).(func(market.MarketType) market.MarketStore); ok {
		r0 = rf(marketType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(market.MarketStore)
		}
	}

	return r0
}

// MarketRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MarketRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - marketType market.MarketType
func (_e *MarketRegistry_Expecter) Get(marketType interface{}) *MarketRegistry_Get_Call {
	return &MarketRegistry_Get_Call{Call: _e.mock.On("Get", marketType)}
}

func (_c *MarketRegistry_Get_Call) Run(run func(marketType market.MarketType)) *MarketRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(market.MarketType))
	})
	return _c
}

func (_c *MarketRegistry_Get_Call) Return(_a0 market.MarketStore) *MarketRegistry_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MarketRegistry_Get_Call) RunAndReturn(run func(market.MarketType) market.MarketStore) *MarketRegistry_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MarketRegistry) GetAll() map[market.MarketType]market.MarketStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[market.MarketType]market.MarketStore
	if rf, ok := ret.Get(0).(func() map[market.MarketType]market.MarketStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[market.MarketType]market.MarketStore)
		}
	}

	return r0
}

// MarketRegistry_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MarketRegistry_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MarketRegistry_Expecter) GetAll() *MarketRegistry_GetAll_Call {
	return &MarketRegistry_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MarketRegistry_GetAll_Call) Run(run func()) *MarketRegistry_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketRegistry_GetAll_Call) Return(_a0 map[market.MarketType]market.MarketStore) *MarketRegistry_GetAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MarketRegistry_GetAll_Call) RunAndReturn(run func() map[market.MarketType]market.MarketStore) *MarketRegistry_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: store
func (_m *MarketRegistry) Register(store market.MarketStore) {
	_m.Called(store)
}

// MarketRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MarketRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - store market.MarketStore
func (_e *MarketRegistry_Expecter) Register(store interface{}) *MarketRegistry_Register_Call {
	return &MarketRegistry_Register_Call{Call: _e.mock.On("Register", store)}
}

func (_c *MarketRegistry_Register_Call) Run(run func(store market.MarketStore)) *MarketRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(market.MarketStore))
	})
	return _c
}

func (_c *MarketRegistry_Register_Call) Return() *MarketRegistry_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MarketRegistry_Register_Call) RunAndReturn(run func(market.MarketStore)) *MarketRegistry_Register_Call {
	_c.Run(run)
	return _c
}

// Types provides a mock function with no fields
func (_m *MarketRegistry) Types() []market.MarketType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Types")
	}

	var r0 []market.MarketType
	if rf, ok := ret.Get(0).(func() []market.MarketType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]market.MarketType)
		}
	}

	return r0
}

// MarketRegistry_Types_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Types'
type MarketRegistry_Types_Call struct {
	*mock.Call
}

// Types is a helper method to define mock.On call
func (_e *MarketRegistry_Expecter) Types() *MarketRegistry_Types_Call {
	return &MarketRegistry_Types_Call{Call: _e.mock.On("Types")}
}

func (_c *MarketRegistry_Types_Call) Run(run func()) *MarketRegistry_Types_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketRegistry_Types_Call) Return(_a0 []market.MarketType) *MarketRegistry_Types_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MarketRegistry_Types_Call) RunAndReturn(run func() []market.MarketType) *MarketRegistry_Types_Call {
	_c.Call.Return(run)
	return _c
}

// NewMarketRegistry creates a new instance of MarketRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketRegistry {
	mock := &MarketRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
