// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package execution

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/types/execution"
	"github.com/wisp-trading/sdk/pkg/types/strategy"
)

// NewExecutionRecords creates a new instance of ExecutionRecords. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutionRecords(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutionRecords {
	mock := &ExecutionRecords{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExecutionRecords is an autogenerated mock type for the ExecutionRecords type
type ExecutionRecords struct {
	mock.Mock
}

type ExecutionRecords_Expecter struct {
	mock *mock.Mock
}

func (_m *ExecutionRecords) EXPECT() *ExecutionRecords_Expecter {
	return &ExecutionRecords_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type ExecutionRecords
func (_mock *ExecutionRecords) Add(record execution.ExecutionRecord) {
	_mock.Called(record)
	return
}

// ExecutionRecords_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type ExecutionRecords_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - record execution.ExecutionRecord
func (_e *ExecutionRecords_Expecter) Add(record interface{}) *ExecutionRecords_Add_Call {
	return &ExecutionRecords_Add_Call{Call: _e.mock.On("Add", record)}
}

func (_c *ExecutionRecords_Add_Call) Run(run func(record execution.ExecutionRecord)) *ExecutionRecords_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 execution.ExecutionRecord
		if args[0] != nil {
			arg0 = args[0].(execution.ExecutionRecord)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutionRecords_Add_Call) Return() *ExecutionRecords_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutionRecords_Add_Call) RunAndReturn(run func(record execution.ExecutionRecord)) *ExecutionRecords_Add_Call {
	_c.Run(run)
	return _c
}

// GetAll provides a mock function for the type ExecutionRecords
func (_mock *ExecutionRecords) GetAll() []execution.ExecutionRecord {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []execution.ExecutionRecord
	if returnFunc, ok := ret.Get(0).(func() []execution.ExecutionRecord); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]execution.ExecutionRecord)
		}
	}
	return r0
}

// ExecutionRecords_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type ExecutionRecords_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *ExecutionRecords_Expecter) GetAll() *ExecutionRecords_GetAll_Call {
	return &ExecutionRecords_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *ExecutionRecords_GetAll_Call) Run(run func()) *ExecutionRecords_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutionRecords_GetAll_Call) Return(executionRecords []execution.ExecutionRecord) *ExecutionRecords_GetAll_Call {
	_c.Call.Return(executionRecords)
	return _c
}

func (_c *ExecutionRecords_GetAll_Call) RunAndReturn(run func() []execution.ExecutionRecord) *ExecutionRecords_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySignalID provides a mock function for the type ExecutionRecords
func (_mock *ExecutionRecords) GetBySignalID(id uuid.UUID) *execution.ExecutionRecord {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBySignalID")
	}

	var r0 *execution.ExecutionRecord
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *execution.ExecutionRecord); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*execution.ExecutionRecord)
		}
	}
	return r0
}

// ExecutionRecords_GetBySignalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySignalID'
type ExecutionRecords_GetBySignalID_Call struct {
	*mock.Call
}

// GetBySignalID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *ExecutionRecords_Expecter) GetBySignalID(id interface{}) *ExecutionRecords_GetBySignalID_Call {
	return &ExecutionRecords_GetBySignalID_Call{Call: _e.mock.On("GetBySignalID", id)}
}

func (_c *ExecutionRecords_GetBySignalID_Call) Run(run func(id uuid.UUID)) *ExecutionRecords_GetBySignalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutionRecords_GetBySignalID_Call) Return(executionRecord *execution.ExecutionRecord) *ExecutionRecords_GetBySignalID_Call {
	_c.Call.Return(executionRecord)
	return _c
}

func (_c *ExecutionRecords_GetBySignalID_Call) RunAndReturn(run func(id uuid.UUID) *execution.ExecutionRecord) *ExecutionRecords_GetBySignalID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByStrategy provides a mock function for the type ExecutionRecords
func (_mock *ExecutionRecords) GetByStrategy(name strategy.StrategyName) []execution.ExecutionRecord {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetByStrategy")
	}

	var r0 []execution.ExecutionRecord
	if returnFunc, ok := ret.Get(0).(func(strategy.StrategyName) []execution.ExecutionRecord); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]execution.ExecutionRecord)
		}
	}
	return r0
}

// ExecutionRecords_GetByStrategy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByStrategy'
type ExecutionRecords_GetByStrategy_Call struct {
	*mock.Call
}

// GetByStrategy is a helper method to define mock.On call
//   - name strategy.StrategyName
func (_e *ExecutionRecords_Expecter) GetByStrategy(name interface{}) *ExecutionRecords_GetByStrategy_Call {
	return &ExecutionRecords_GetByStrategy_Call{Call: _e.mock.On("GetByStrategy", name)}
}

func (_c *ExecutionRecords_GetByStrategy_Call) Run(run func(name strategy.StrategyName)) *ExecutionRecords_GetByStrategy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 strategy.StrategyName
		if args[0] != nil {
			arg0 = args[0].(strategy.StrategyName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutionRecords_GetByStrategy_Call) Return(executionRecords []execution.ExecutionRecord) *ExecutionRecords_GetByStrategy_Call {
	_c.Call.Return(executionRecords)
	return _c
}

func (_c *ExecutionRecords_GetByStrategy_Call) RunAndReturn(run func(name strategy.StrategyName) []execution.ExecutionRecord) *ExecutionRecords_GetByStrategy_Call {
	_c.Call.Return(run)
	return _c
}
