// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package execution

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/types/strategy"
)

// NewSignalRouter creates a new instance of SignalRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignalRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignalRouter {
	mock := &SignalRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SignalRouter is an autogenerated mock type for the SignalRouter type
type SignalRouter struct {
	mock.Mock
}

type SignalRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *SignalRouter) EXPECT() *SignalRouter_Expecter {
	return &SignalRouter_Expecter{mock: &_m.Mock}
}

// Route provides a mock function for the type SignalRouter
func (_mock *SignalRouter) Route(signal strategy.Signal) {
	_mock.Called(signal)
	return
}

// SignalRouter_Route_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Route'
type SignalRouter_Route_Call struct {
	*mock.Call
}

// Route is a helper method to define mock.On call
//   - signal strategy.Signal
func (_e *SignalRouter_Expecter) Route(signal interface{}) *SignalRouter_Route_Call {
	return &SignalRouter_Route_Call{Call: _e.mock.On("Route", signal)}
}

func (_c *SignalRouter_Route_Call) Run(run func(signal strategy.Signal)) *SignalRouter_Route_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 strategy.Signal
		if args[0] != nil {
			arg0 = args[0].(strategy.Signal)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SignalRouter_Route_Call) Return() *SignalRouter_Route_Call {
	_c.Call.Return()
	return _c
}

func (_c *SignalRouter_Route_Call) RunAndReturn(run func(signal strategy.Signal)) *SignalRouter_Route_Call {
	_c.Run(run)
	return _c
}
