// Code generated by mockery v2.53.5. DO NOT EDIT.

package plugin

import (
	mock "github.com/stretchr/testify/mock"

	strategy "github.com/backtesting-org/kronos-sdk/pkg/types/strategy"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// LoadHookPlugin provides a mock function with given fields: pluginPath
func (_m *Manager) LoadHookPlugin(pluginPath string) error {
	ret := _m.Called(pluginPath)

	if len(ret) == 0 {
		panic("no return value specified for LoadHookPlugin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(pluginPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Manager_LoadHookPlugin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadHookPlugin'
type Manager_LoadHookPlugin_Call struct {
	*mock.Call
}

// LoadHookPlugin is a helper method to define mock.On call
//   - pluginPath string
func (_e *Manager_Expecter) LoadHookPlugin(pluginPath interface{}) *Manager_LoadHookPlugin_Call {
	return &Manager_LoadHookPlugin_Call{Call: _e.mock.On("LoadHookPlugin", pluginPath)}
}

func (_c *Manager_LoadHookPlugin_Call) Run(run func(pluginPath string)) *Manager_LoadHookPlugin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Manager_LoadHookPlugin_Call) Return(_a0 error) *Manager_LoadHookPlugin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_LoadHookPlugin_Call) RunAndReturn(run func(string) error) *Manager_LoadHookPlugin_Call {
	_c.Call.Return(run)
	return _c
}

// LoadStrategyPlugin provides a mock function with given fields: pluginPath
func (_m *Manager) LoadStrategyPlugin(pluginPath string) (strategy.Strategy, error) {
	ret := _m.Called(pluginPath)

	if len(ret) == 0 {
		panic("no return value specified for LoadStrategyPlugin")
	}

	var r0 strategy.Strategy
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (strategy.Strategy, error)); ok {
		return rf(pluginPath)
	}
	if rf, ok := ret.Get(0).(func(string) strategy.Strategy); ok {
		r0 = rf(pluginPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(strategy.Strategy)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pluginPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Manager_LoadStrategyPlugin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadStrategyPlugin'
type Manager_LoadStrategyPlugin_Call struct {
	*mock.Call
}

// LoadStrategyPlugin is a helper method to define mock.On call
//   - pluginPath string
func (_e *Manager_Expecter) LoadStrategyPlugin(pluginPath interface{}) *Manager_LoadStrategyPlugin_Call {
	return &Manager_LoadStrategyPlugin_Call{Call: _e.mock.On("LoadStrategyPlugin", pluginPath)}
}

func (_c *Manager_LoadStrategyPlugin_Call) Run(run func(pluginPath string)) *Manager_LoadStrategyPlugin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Manager_LoadStrategyPlugin_Call) Return(_a0 strategy.Strategy, _a1 error) *Manager_LoadStrategyPlugin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Manager_LoadStrategyPlugin_Call) RunAndReturn(run func(string) (strategy.Strategy, error)) *Manager_LoadStrategyPlugin_Call {
	_c.Call.Return(run)
	return _c
}

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
