// Code generated by mockery v2.53.5. DO NOT EDIT.

package analytics

import (
	connector "github.com/wisp-trading/wisp/pkg/types/connector"
	analytics "github.com/wisp-trading/wisp/pkg/types/wisp/analytics"

	context "context"

	mock "github.com/stretchr/testify/mock"

	numerical "github.com/wisp-trading/wisp/pkg/types/wisp/numerical"

	perp "github.com/wisp-trading/wisp/pkg/types/connector/perp"

	portfolio "github.com/wisp-trading/wisp/pkg/types/portfolio"
)

// PerpMarket is an autogenerated mock type for the PerpMarket type
type PerpMarket struct {
	mock.Mock
}

type PerpMarket_Expecter struct {
	mock *mock.Mock
}

func (_m *PerpMarket) EXPECT() *PerpMarket_Expecter {
	return &PerpMarket_Expecter{mock: &_m.Mock}
}

// FundingRate provides a mock function with given fields: ctx, asset, exchange
func (_m *PerpMarket) FundingRate(ctx context.Context, asset portfolio.Asset, exchange connector.ExchangeName) (*perp.FundingRate, error) {
	ret := _m.Called(ctx, asset, exchange)

	if len(ret) == 0 {
		panic("no return value specified for FundingRate")
	}

	var r0 *perp.FundingRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, portfolio.Asset, connector.ExchangeName) (*perp.FundingRate, error)); ok {
		return rf(ctx, asset, exchange)
	}
	if rf, ok := ret.Get(0).(func(context.Context, portfolio.Asset, connector.ExchangeName) *perp.FundingRate); ok {
		r0 = rf(ctx, asset, exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*perp.FundingRate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, portfolio.Asset, connector.ExchangeName) error); ok {
		r1 = rf(ctx, asset, exchange)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PerpMarket_FundingRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FundingRate'
type PerpMarket_FundingRate_Call struct {
	*mock.Call
}

// FundingRate is a helper method to define mock.On call
//   - ctx context.Context
//   - asset portfolio.Asset
//   - exchange connector.ExchangeName
func (_e *PerpMarket_Expecter) FundingRate(ctx interface{}, asset interface{}, exchange interface{}) *PerpMarket_FundingRate_Call {
	return &PerpMarket_FundingRate_Call{Call: _e.mock.On("FundingRate", ctx, asset, exchange)}
}

func (_c *PerpMarket_FundingRate_Call) Run(run func(ctx context.Context, asset portfolio.Asset, exchange connector.ExchangeName)) *PerpMarket_FundingRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(portfolio.Asset), args[2].(connector.ExchangeName))
	})
	return _c
}

func (_c *PerpMarket_FundingRate_Call) Return(_a0 *perp.FundingRate, _a1 error) *PerpMarket_FundingRate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PerpMarket_FundingRate_Call) RunAndReturn(run func(context.Context, portfolio.Asset, connector.ExchangeName) (*perp.FundingRate, error)) *PerpMarket_FundingRate_Call {
	_c.Call.Return(run)
	return _c
}

// FundingRates provides a mock function with given fields: ctx, asset
func (_m *PerpMarket) FundingRates(ctx context.Context, asset portfolio.Asset) map[connector.ExchangeName]perp.FundingRate {
	ret := _m.Called(ctx, asset)

	if len(ret) == 0 {
		panic("no return value specified for FundingRates")
	}

	var r0 map[connector.ExchangeName]perp.FundingRate
	if rf, ok := ret.Get(0).(func(context.Context, portfolio.Asset) map[connector.ExchangeName]perp.FundingRate); ok {
		r0 = rf(ctx, asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[connector.ExchangeName]perp.FundingRate)
		}
	}

	return r0
}

// PerpMarket_FundingRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FundingRates'
type PerpMarket_FundingRates_Call struct {
	*mock.Call
}

// FundingRates is a helper method to define mock.On call
//   - ctx context.Context
//   - asset portfolio.Asset
func (_e *PerpMarket_Expecter) FundingRates(ctx interface{}, asset interface{}) *PerpMarket_FundingRates_Call {
	return &PerpMarket_FundingRates_Call{Call: _e.mock.On("FundingRates", ctx, asset)}
}

func (_c *PerpMarket_FundingRates_Call) Run(run func(ctx context.Context, asset portfolio.Asset)) *PerpMarket_FundingRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(portfolio.Asset))
	})
	return _c
}

func (_c *PerpMarket_FundingRates_Call) Return(_a0 map[connector.ExchangeName]perp.FundingRate) *PerpMarket_FundingRates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PerpMarket_FundingRates_Call) RunAndReturn(run func(context.Context, portfolio.Asset) map[connector.ExchangeName]perp.FundingRate) *PerpMarket_FundingRates_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAssetsWithFundingRates provides a mock function with given fields: ctx
func (_m *PerpMarket) GetAllAssetsWithFundingRates(ctx context.Context) []portfolio.Asset {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAssetsWithFundingRates")
	}

	var r0 []portfolio.Asset
	if rf, ok := ret.Get(0).(func(context.Context) []portfolio.Asset); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]portfolio.Asset)
		}
	}

	return r0
}

// PerpMarket_GetAllAssetsWithFundingRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAssetsWithFundingRates'
type PerpMarket_GetAllAssetsWithFundingRates_Call struct {
	*mock.Call
}

// GetAllAssetsWithFundingRates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PerpMarket_Expecter) GetAllAssetsWithFundingRates(ctx interface{}) *PerpMarket_GetAllAssetsWithFundingRates_Call {
	return &PerpMarket_GetAllAssetsWithFundingRates_Call{Call: _e.mock.On("GetAllAssetsWithFundingRates", ctx)}
}

func (_c *PerpMarket_GetAllAssetsWithFundingRates_Call) Run(run func(ctx context.Context)) *PerpMarket_GetAllAssetsWithFundingRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PerpMarket_GetAllAssetsWithFundingRates_Call) Return(_a0 []portfolio.Asset) *PerpMarket_GetAllAssetsWithFundingRates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PerpMarket_GetAllAssetsWithFundingRates_Call) RunAndReturn(run func(context.Context) []portfolio.Asset) *PerpMarket_GetAllAssetsWithFundingRates_Call {
	_c.Call.Return(run)
	return _c
}

// GetKlines provides a mock function with given fields: asset, exchange, interval, limit
func (_m *PerpMarket) GetKlines(asset portfolio.Asset, exchange connector.ExchangeName, interval string, limit int) []connector.Kline {
	ret := _m.Called(asset, exchange, interval, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetKlines")
	}

	var r0 []connector.Kline
	if rf, ok := ret.Get(0).(func(portfolio.Asset, connector.ExchangeName, string, int) []connector.Kline); ok {
		r0 = rf(asset, exchange, interval, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Kline)
		}
	}

	return r0
}

// PerpMarket_GetKlines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKlines'
type PerpMarket_GetKlines_Call struct {
	*mock.Call
}

// GetKlines is a helper method to define mock.On call
//   - asset portfolio.Asset
//   - exchange connector.ExchangeName
//   - interval string
//   - limit int
func (_e *PerpMarket_Expecter) GetKlines(asset interface{}, exchange interface{}, interval interface{}, limit interface{}) *PerpMarket_GetKlines_Call {
	return &PerpMarket_GetKlines_Call{Call: _e.mock.On("GetKlines", asset, exchange, interval, limit)}
}

func (_c *PerpMarket_GetKlines_Call) Run(run func(asset portfolio.Asset, exchange connector.ExchangeName, interval string, limit int)) *PerpMarket_GetKlines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portfolio.Asset), args[1].(connector.ExchangeName), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *PerpMarket_GetKlines_Call) Return(_a0 []connector.Kline) *PerpMarket_GetKlines_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PerpMarket_GetKlines_Call) RunAndReturn(run func(portfolio.Asset, connector.ExchangeName, string, int) []connector.Kline) *PerpMarket_GetKlines_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradableQuantity provides a mock function with given fields: ctx, asset, opts
func (_m *PerpMarket) GetTradableQuantity(ctx context.Context, asset portfolio.Asset, opts ...analytics.LiquidityOptions) numerical.Decimal {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, asset)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTradableQuantity")
	}

	var r0 numerical.Decimal
	if rf, ok := ret.Get(0).(func(context.Context, portfolio.Asset, ...analytics.LiquidityOptions) numerical.Decimal); ok {
		r0 = rf(ctx, asset, opts...)
	} else {
		r0 = ret.Get(0).(numerical.Decimal)
	}

	return r0
}

// PerpMarket_GetTradableQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradableQuantity'
type PerpMarket_GetTradableQuantity_Call struct {
	*mock.Call
}

// GetTradableQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - asset portfolio.Asset
//   - opts ...analytics.LiquidityOptions
func (_e *PerpMarket_Expecter) GetTradableQuantity(ctx interface{}, asset interface{}, opts ...interface{}) *PerpMarket_GetTradableQuantity_Call {
	return &PerpMarket_GetTradableQuantity_Call{Call: _e.mock.On("GetTradableQuantity",
		append([]interface{}{ctx, asset}, opts...)...)}
}

func (_c *PerpMarket_GetTradableQuantity_Call) Run(run func(ctx context.Context, asset portfolio.Asset, opts ...analytics.LiquidityOptions)) *PerpMarket_GetTradableQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]analytics.LiquidityOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(analytics.LiquidityOptions)
			}
		}
		run(args[0].(context.Context), args[1].(portfolio.Asset), variadicArgs...)
	})
	return _c
}

func (_c *PerpMarket_GetTradableQuantity_Call) Return(_a0 numerical.Decimal) *PerpMarket_GetTradableQuantity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PerpMarket_GetTradableQuantity_Call) RunAndReturn(run func(context.Context, portfolio.Asset, ...analytics.LiquidityOptions) numerical.Decimal) *PerpMarket_GetTradableQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// OrderBook provides a mock function with given fields: ctx, asset, exchange
func (_m *PerpMarket) OrderBook(ctx context.Context, asset portfolio.Asset, exchange ...connector.ExchangeName) (*connector.OrderBook, error) {
	_va := make([]interface{}, len(exchange))
	for _i := range exchange {
		_va[_i] = exchange[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, asset)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OrderBook")
	}

	var r0 *connector.OrderBook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, portfolio.Asset, ...connector.ExchangeName) (*connector.OrderBook, error)); ok {
		return rf(ctx, asset, exchange...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, portfolio.Asset, ...connector.ExchangeName) *connector.OrderBook); ok {
		r0 = rf(ctx, asset, exchange...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.OrderBook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, portfolio.Asset, ...connector.ExchangeName) error); ok {
		r1 = rf(ctx, asset, exchange...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PerpMarket_OrderBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderBook'
type PerpMarket_OrderBook_Call struct {
	*mock.Call
}

// OrderBook is a helper method to define mock.On call
//   - ctx context.Context
//   - asset portfolio.Asset
//   - exchange ...connector.ExchangeName
func (_e *PerpMarket_Expecter) OrderBook(ctx interface{}, asset interface{}, exchange ...interface{}) *PerpMarket_OrderBook_Call {
	return &PerpMarket_OrderBook_Call{Call: _e.mock.On("OrderBook",
		append([]interface{}{ctx, asset}, exchange...)...)}
}

func (_c *PerpMarket_OrderBook_Call) Run(run func(ctx context.Context, asset portfolio.Asset, exchange ...connector.ExchangeName)) *PerpMarket_OrderBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]connector.ExchangeName, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(connector.ExchangeName)
			}
		}
		run(args[0].(context.Context), args[1].(portfolio.Asset), variadicArgs...)
	})
	return _c
}

func (_c *PerpMarket_OrderBook_Call) Return(_a0 *connector.OrderBook, _a1 error) *PerpMarket_OrderBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PerpMarket_OrderBook_Call) RunAndReturn(run func(context.Context, portfolio.Asset, ...connector.ExchangeName) (*connector.OrderBook, error)) *PerpMarket_OrderBook_Call {
	_c.Call.Return(run)
	return _c
}

// Price provides a mock function with given fields: ctx, asset, exchange
func (_m *PerpMarket) Price(ctx context.Context, asset portfolio.Asset, exchange ...connector.ExchangeName) (numerical.Decimal, error) {
	_va := make([]interface{}, len(exchange))
	for _i := range exchange {
		_va[_i] = exchange[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, asset)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Price")
	}

	var r0 numerical.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, portfolio.Asset, ...connector.ExchangeName) (numerical.Decimal, error)); ok {
		return rf(ctx, asset, exchange...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, portfolio.Asset, ...connector.ExchangeName) numerical.Decimal); ok {
		r0 = rf(ctx, asset, exchange...)
	} else {
		r0 = ret.Get(0).(numerical.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, portfolio.Asset, ...connector.ExchangeName) error); ok {
		r1 = rf(ctx, asset, exchange...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PerpMarket_Price_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Price'
type PerpMarket_Price_Call struct {
	*mock.Call
}

// Price is a helper method to define mock.On call
//   - ctx context.Context
//   - asset portfolio.Asset
//   - exchange ...connector.ExchangeName
func (_e *PerpMarket_Expecter) Price(ctx interface{}, asset interface{}, exchange ...interface{}) *PerpMarket_Price_Call {
	return &PerpMarket_Price_Call{Call: _e.mock.On("Price",
		append([]interface{}{ctx, asset}, exchange...)...)}
}

func (_c *PerpMarket_Price_Call) Run(run func(ctx context.Context, asset portfolio.Asset, exchange ...connector.ExchangeName)) *PerpMarket_Price_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]connector.ExchangeName, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(connector.ExchangeName)
			}
		}
		run(args[0].(context.Context), args[1].(portfolio.Asset), variadicArgs...)
	})
	return _c
}

func (_c *PerpMarket_Price_Call) Return(_a0 numerical.Decimal, _a1 error) *PerpMarket_Price_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PerpMarket_Price_Call) RunAndReturn(run func(context.Context, portfolio.Asset, ...connector.ExchangeName) (numerical.Decimal, error)) *PerpMarket_Price_Call {
	_c.Call.Return(run)
	return _c
}

// Prices provides a mock function with given fields: ctx, asset
func (_m *PerpMarket) Prices(ctx context.Context, asset portfolio.Asset) map[connector.ExchangeName]numerical.Decimal {
	ret := _m.Called(ctx, asset)

	if len(ret) == 0 {
		panic("no return value specified for Prices")
	}

	var r0 map[connector.ExchangeName]numerical.Decimal
	if rf, ok := ret.Get(0).(func(context.Context, portfolio.Asset) map[connector.ExchangeName]numerical.Decimal); ok {
		r0 = rf(ctx, asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[connector.ExchangeName]numerical.Decimal)
		}
	}

	return r0
}

// PerpMarket_Prices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prices'
type PerpMarket_Prices_Call struct {
	*mock.Call
}

// Prices is a helper method to define mock.On call
//   - ctx context.Context
//   - asset portfolio.Asset
func (_e *PerpMarket_Expecter) Prices(ctx interface{}, asset interface{}) *PerpMarket_Prices_Call {
	return &PerpMarket_Prices_Call{Call: _e.mock.On("Prices", ctx, asset)}
}

func (_c *PerpMarket_Prices_Call) Run(run func(ctx context.Context, asset portfolio.Asset)) *PerpMarket_Prices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(portfolio.Asset))
	})
	return _c
}

func (_c *PerpMarket_Prices_Call) Return(_a0 map[connector.ExchangeName]numerical.Decimal) *PerpMarket_Prices_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PerpMarket_Prices_Call) RunAndReturn(run func(context.Context, portfolio.Asset) map[connector.ExchangeName]numerical.Decimal) *PerpMarket_Prices_Call {
	_c.Call.Return(run)
	return _c
}

// NewPerpMarket creates a new instance of PerpMarket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPerpMarket(t interface {
	mock.TestingT
	Cleanup(func())
}) *PerpMarket {
	mock := &PerpMarket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
