// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package monitoring

import (
	mock "github.com/stretchr/testify/mock"
	connector0 "github.com/wisp-trading/sdk/pkg/markets/prediction/types/connector"
	"github.com/wisp-trading/sdk/pkg/types/connector"
	"github.com/wisp-trading/sdk/pkg/types/monitoring"
	"github.com/wisp-trading/sdk/pkg/types/monitoring/health"
	"github.com/wisp-trading/sdk/pkg/types/portfolio"
	"github.com/wisp-trading/sdk/pkg/types/strategy"
)

// NewViewRegistry creates a new instance of ViewRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewViewRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *ViewRegistry {
	mock := &ViewRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ViewRegistry is an autogenerated mock type for the ViewRegistry type
type ViewRegistry struct {
	mock.Mock
}

type ViewRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *ViewRegistry) EXPECT() *ViewRegistry_Expecter {
	return &ViewRegistry_Expecter{mock: &_m.Mock}
}

// GetHealth provides a mock function for the type ViewRegistry
func (_mock *ViewRegistry) GetHealth() *health.SystemHealthReport {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHealth")
	}

	var r0 *health.SystemHealthReport
	if returnFunc, ok := ret.Get(0).(func() *health.SystemHealthReport); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*health.SystemHealthReport)
		}
	}
	return r0
}

// ViewRegistry_GetHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealth'
type ViewRegistry_GetHealth_Call struct {
	*mock.Call
}

// GetHealth is a helper method to define mock.On call
func (_e *ViewRegistry_Expecter) GetHealth() *ViewRegistry_GetHealth_Call {
	return &ViewRegistry_GetHealth_Call{Call: _e.mock.On("GetHealth")}
}

func (_c *ViewRegistry_GetHealth_Call) Run(run func()) *ViewRegistry_GetHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ViewRegistry_GetHealth_Call) Return(systemHealthReport *health.SystemHealthReport) *ViewRegistry_GetHealth_Call {
	_c.Call.Return(systemHealthReport)
	return _c
}

func (_c *ViewRegistry_GetHealth_Call) RunAndReturn(run func() *health.SystemHealthReport) *ViewRegistry_GetHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetKlines provides a mock function for the type ViewRegistry
func (_mock *ViewRegistry) GetKlines(exchange connector.ExchangeName, pair portfolio.Pair, interval string, limit int) []connector.Kline {
	ret := _mock.Called(exchange, pair, interval, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetKlines")
	}

	var r0 []connector.Kline
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName, portfolio.Pair, string, int) []connector.Kline); ok {
		r0 = returnFunc(exchange, pair, interval, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Kline)
		}
	}
	return r0
}

// ViewRegistry_GetKlines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKlines'
type ViewRegistry_GetKlines_Call struct {
	*mock.Call
}

// GetKlines is a helper method to define mock.On call
//   - exchange connector.ExchangeName
//   - pair portfolio.Pair
//   - interval string
//   - limit int
func (_e *ViewRegistry_Expecter) GetKlines(exchange interface{}, pair interface{}, interval interface{}, limit interface{}) *ViewRegistry_GetKlines_Call {
	return &ViewRegistry_GetKlines_Call{Call: _e.mock.On("GetKlines", exchange, pair, interval, limit)}
}

func (_c *ViewRegistry_GetKlines_Call) Run(run func(exchange connector.ExchangeName, pair portfolio.Pair, interval string, limit int)) *ViewRegistry_GetKlines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 portfolio.Pair
		if args[1] != nil {
			arg1 = args[1].(portfolio.Pair)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ViewRegistry_GetKlines_Call) Return(klines []connector.Kline) *ViewRegistry_GetKlines_Call {
	_c.Call.Return(klines)
	return _c
}

func (_c *ViewRegistry_GetKlines_Call) RunAndReturn(run func(exchange connector.ExchangeName, pair portfolio.Pair, interval string, limit int) []connector.Kline) *ViewRegistry_GetKlines_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarketViews provides a mock function for the type ViewRegistry
func (_mock *ViewRegistry) GetMarketViews() *monitoring.MarketViews {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMarketViews")
	}

	var r0 *monitoring.MarketViews
	if returnFunc, ok := ret.Get(0).(func() *monitoring.MarketViews); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*monitoring.MarketViews)
		}
	}
	return r0
}

// ViewRegistry_GetMarketViews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarketViews'
type ViewRegistry_GetMarketViews_Call struct {
	*mock.Call
}

// GetMarketViews is a helper method to define mock.On call
func (_e *ViewRegistry_Expecter) GetMarketViews() *ViewRegistry_GetMarketViews_Call {
	return &ViewRegistry_GetMarketViews_Call{Call: _e.mock.On("GetMarketViews")}
}

func (_c *ViewRegistry_GetMarketViews_Call) Run(run func()) *ViewRegistry_GetMarketViews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ViewRegistry_GetMarketViews_Call) Return(marketViews *monitoring.MarketViews) *ViewRegistry_GetMarketViews_Call {
	_c.Call.Return(marketViews)
	return _c
}

func (_c *ViewRegistry_GetMarketViews_Call) RunAndReturn(run func() *monitoring.MarketViews) *ViewRegistry_GetMarketViews_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetrics provides a mock function for the type ViewRegistry
func (_mock *ViewRegistry) GetMetrics() *monitoring.StrategyMetrics {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 *monitoring.StrategyMetrics
	if returnFunc, ok := ret.Get(0).(func() *monitoring.StrategyMetrics); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*monitoring.StrategyMetrics)
		}
	}
	return r0
}

// ViewRegistry_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type ViewRegistry_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
func (_e *ViewRegistry_Expecter) GetMetrics() *ViewRegistry_GetMetrics_Call {
	return &ViewRegistry_GetMetrics_Call{Call: _e.mock.On("GetMetrics")}
}

func (_c *ViewRegistry_GetMetrics_Call) Run(run func()) *ViewRegistry_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ViewRegistry_GetMetrics_Call) Return(strategyMetrics *monitoring.StrategyMetrics) *ViewRegistry_GetMetrics_Call {
	_c.Call.Return(strategyMetrics)
	return _c
}

func (_c *ViewRegistry_GetMetrics_Call) RunAndReturn(run func() *monitoring.StrategyMetrics) *ViewRegistry_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderbook provides a mock function for the type ViewRegistry
func (_mock *ViewRegistry) GetOrderbook(exchange connector.ExchangeName, pair portfolio.Pair) *connector.OrderBook {
	ret := _mock.Called(exchange, pair)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderbook")
	}

	var r0 *connector.OrderBook
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName, portfolio.Pair) *connector.OrderBook); ok {
		r0 = returnFunc(exchange, pair)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.OrderBook)
		}
	}
	return r0
}

// ViewRegistry_GetOrderbook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderbook'
type ViewRegistry_GetOrderbook_Call struct {
	*mock.Call
}

// GetOrderbook is a helper method to define mock.On call
//   - exchange connector.ExchangeName
//   - pair portfolio.Pair
func (_e *ViewRegistry_Expecter) GetOrderbook(exchange interface{}, pair interface{}) *ViewRegistry_GetOrderbook_Call {
	return &ViewRegistry_GetOrderbook_Call{Call: _e.mock.On("GetOrderbook", exchange, pair)}
}

func (_c *ViewRegistry_GetOrderbook_Call) Run(run func(exchange connector.ExchangeName, pair portfolio.Pair)) *ViewRegistry_GetOrderbook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 portfolio.Pair
		if args[1] != nil {
			arg1 = args[1].(portfolio.Pair)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ViewRegistry_GetOrderbook_Call) Return(orderBook *connector.OrderBook) *ViewRegistry_GetOrderbook_Call {
	_c.Call.Return(orderBook)
	return _c
}

func (_c *ViewRegistry_GetOrderbook_Call) RunAndReturn(run func(exchange connector.ExchangeName, pair portfolio.Pair) *connector.OrderBook) *ViewRegistry_GetOrderbook_Call {
	_c.Call.Return(run)
	return _c
}

// GetPnLView provides a mock function for the type ViewRegistry
func (_mock *ViewRegistry) GetPnLView() *monitoring.PnLView {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPnLView")
	}

	var r0 *monitoring.PnLView
	if returnFunc, ok := ret.Get(0).(func() *monitoring.PnLView); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*monitoring.PnLView)
		}
	}
	return r0
}

// ViewRegistry_GetPnLView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPnLView'
type ViewRegistry_GetPnLView_Call struct {
	*mock.Call
}

// GetPnLView is a helper method to define mock.On call
func (_e *ViewRegistry_Expecter) GetPnLView() *ViewRegistry_GetPnLView_Call {
	return &ViewRegistry_GetPnLView_Call{Call: _e.mock.On("GetPnLView")}
}

func (_c *ViewRegistry_GetPnLView_Call) Run(run func()) *ViewRegistry_GetPnLView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ViewRegistry_GetPnLView_Call) Return(pnLView *monitoring.PnLView) *ViewRegistry_GetPnLView_Call {
	_c.Call.Return(pnLView)
	return _c
}

func (_c *ViewRegistry_GetPnLView_Call) RunAndReturn(run func() *monitoring.PnLView) *ViewRegistry_GetPnLView_Call {
	_c.Call.Return(run)
	return _c
}

// GetPositionsView provides a mock function for the type ViewRegistry
func (_mock *ViewRegistry) GetPositionsView() *strategy.StrategyExecution {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPositionsView")
	}

	var r0 *strategy.StrategyExecution
	if returnFunc, ok := ret.Get(0).(func() *strategy.StrategyExecution); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*strategy.StrategyExecution)
		}
	}
	return r0
}

// ViewRegistry_GetPositionsView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPositionsView'
type ViewRegistry_GetPositionsView_Call struct {
	*mock.Call
}

// GetPositionsView is a helper method to define mock.On call
func (_e *ViewRegistry_Expecter) GetPositionsView() *ViewRegistry_GetPositionsView_Call {
	return &ViewRegistry_GetPositionsView_Call{Call: _e.mock.On("GetPositionsView")}
}

func (_c *ViewRegistry_GetPositionsView_Call) Run(run func()) *ViewRegistry_GetPositionsView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ViewRegistry_GetPositionsView_Call) Return(strategyExecution *strategy.StrategyExecution) *ViewRegistry_GetPositionsView_Call {
	_c.Call.Return(strategyExecution)
	return _c
}

func (_c *ViewRegistry_GetPositionsView_Call) RunAndReturn(run func() *strategy.StrategyExecution) *ViewRegistry_GetPositionsView_Call {
	_c.Call.Return(run)
	return _c
}

// GetPredictionOrderbookView provides a mock function for the type ViewRegistry
func (_mock *ViewRegistry) GetPredictionOrderbookView(exchange connector.ExchangeName, marketID connector0.MarketID, outcomeID connector0.OutcomeID) *connector.OrderBook {
	ret := _mock.Called(exchange, marketID, outcomeID)

	if len(ret) == 0 {
		panic("no return value specified for GetPredictionOrderbookView")
	}

	var r0 *connector.OrderBook
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName, connector0.MarketID, connector0.OutcomeID) *connector.OrderBook); ok {
		r0 = returnFunc(exchange, marketID, outcomeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.OrderBook)
		}
	}
	return r0
}

// ViewRegistry_GetPredictionOrderbookView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPredictionOrderbookView'
type ViewRegistry_GetPredictionOrderbookView_Call struct {
	*mock.Call
}

// GetPredictionOrderbookView is a helper method to define mock.On call
//   - exchange connector.ExchangeName
//   - marketID connector0.MarketID
//   - outcomeID connector0.OutcomeID
func (_e *ViewRegistry_Expecter) GetPredictionOrderbookView(exchange interface{}, marketID interface{}, outcomeID interface{}) *ViewRegistry_GetPredictionOrderbookView_Call {
	return &ViewRegistry_GetPredictionOrderbookView_Call{Call: _e.mock.On("GetPredictionOrderbookView", exchange, marketID, outcomeID)}
}

func (_c *ViewRegistry_GetPredictionOrderbookView_Call) Run(run func(exchange connector.ExchangeName, marketID connector0.MarketID, outcomeID connector0.OutcomeID)) *ViewRegistry_GetPredictionOrderbookView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 connector0.MarketID
		if args[1] != nil {
			arg1 = args[1].(connector0.MarketID)
		}
		var arg2 connector0.OutcomeID
		if args[2] != nil {
			arg2 = args[2].(connector0.OutcomeID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ViewRegistry_GetPredictionOrderbookView_Call) Return(orderBook *connector.OrderBook) *ViewRegistry_GetPredictionOrderbookView_Call {
	_c.Call.Return(orderBook)
	return _c
}

func (_c *ViewRegistry_GetPredictionOrderbookView_Call) RunAndReturn(run func(exchange connector.ExchangeName, marketID connector0.MarketID, outcomeID connector0.OutcomeID) *connector.OrderBook) *ViewRegistry_GetPredictionOrderbookView_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfilingStats provides a mock function for the type ViewRegistry
func (_mock *ViewRegistry) GetProfilingStats() *monitoring.ProfilingStats {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProfilingStats")
	}

	var r0 *monitoring.ProfilingStats
	if returnFunc, ok := ret.Get(0).(func() *monitoring.ProfilingStats); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*monitoring.ProfilingStats)
		}
	}
	return r0
}

// ViewRegistry_GetProfilingStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfilingStats'
type ViewRegistry_GetProfilingStats_Call struct {
	*mock.Call
}

// GetProfilingStats is a helper method to define mock.On call
func (_e *ViewRegistry_Expecter) GetProfilingStats() *ViewRegistry_GetProfilingStats_Call {
	return &ViewRegistry_GetProfilingStats_Call{Call: _e.mock.On("GetProfilingStats")}
}

func (_c *ViewRegistry_GetProfilingStats_Call) Run(run func()) *ViewRegistry_GetProfilingStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ViewRegistry_GetProfilingStats_Call) Return(v *monitoring.ProfilingStats) *ViewRegistry_GetProfilingStats_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *ViewRegistry_GetProfilingStats_Call) RunAndReturn(run func() *monitoring.ProfilingStats) *ViewRegistry_GetProfilingStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentExecutions provides a mock function for the type ViewRegistry
func (_mock *ViewRegistry) GetRecentExecutions(limit int) []monitoring.ProfilingMetrics {
	ret := _mock.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentExecutions")
	}

	var r0 []monitoring.ProfilingMetrics
	if returnFunc, ok := ret.Get(0).(func(int) []monitoring.ProfilingMetrics); ok {
		r0 = returnFunc(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]monitoring.ProfilingMetrics)
		}
	}
	return r0
}

// ViewRegistry_GetRecentExecutions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentExecutions'
type ViewRegistry_GetRecentExecutions_Call struct {
	*mock.Call
}

// GetRecentExecutions is a helper method to define mock.On call
//   - limit int
func (_e *ViewRegistry_Expecter) GetRecentExecutions(limit interface{}) *ViewRegistry_GetRecentExecutions_Call {
	return &ViewRegistry_GetRecentExecutions_Call{Call: _e.mock.On("GetRecentExecutions", limit)}
}

func (_c *ViewRegistry_GetRecentExecutions_Call) Run(run func(limit int)) *ViewRegistry_GetRecentExecutions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ViewRegistry_GetRecentExecutions_Call) Return(vs []monitoring.ProfilingMetrics) *ViewRegistry_GetRecentExecutions_Call {
	_c.Call.Return(vs)
	return _c
}

func (_c *ViewRegistry_GetRecentExecutions_Call) RunAndReturn(run func(limit int) []monitoring.ProfilingMetrics) *ViewRegistry_GetRecentExecutions_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentTrades provides a mock function for the type ViewRegistry
func (_mock *ViewRegistry) GetRecentTrades(limit int) []connector.Trade {
	ret := _mock.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentTrades")
	}

	var r0 []connector.Trade
	if returnFunc, ok := ret.Get(0).(func(int) []connector.Trade); ok {
		r0 = returnFunc(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}
	return r0
}

// ViewRegistry_GetRecentTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentTrades'
type ViewRegistry_GetRecentTrades_Call struct {
	*mock.Call
}

// GetRecentTrades is a helper method to define mock.On call
//   - limit int
func (_e *ViewRegistry_Expecter) GetRecentTrades(limit interface{}) *ViewRegistry_GetRecentTrades_Call {
	return &ViewRegistry_GetRecentTrades_Call{Call: _e.mock.On("GetRecentTrades", limit)}
}

func (_c *ViewRegistry_GetRecentTrades_Call) Run(run func(limit int)) *ViewRegistry_GetRecentTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ViewRegistry_GetRecentTrades_Call) Return(trades []connector.Trade) *ViewRegistry_GetRecentTrades_Call {
	_c.Call.Return(trades)
	return _c
}

func (_c *ViewRegistry_GetRecentTrades_Call) RunAndReturn(run func(limit int) []connector.Trade) *ViewRegistry_GetRecentTrades_Call {
	_c.Call.Return(run)
	return _c
}

// GetStrategyStatus provides a mock function for the type ViewRegistry
func (_mock *ViewRegistry) GetStrategyStatus() []monitoring.StrategyStatusView {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStrategyStatus")
	}

	var r0 []monitoring.StrategyStatusView
	if returnFunc, ok := ret.Get(0).(func() []monitoring.StrategyStatusView); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]monitoring.StrategyStatusView)
		}
	}
	return r0
}

// ViewRegistry_GetStrategyStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStrategyStatus'
type ViewRegistry_GetStrategyStatus_Call struct {
	*mock.Call
}

// GetStrategyStatus is a helper method to define mock.On call
func (_e *ViewRegistry_Expecter) GetStrategyStatus() *ViewRegistry_GetStrategyStatus_Call {
	return &ViewRegistry_GetStrategyStatus_Call{Call: _e.mock.On("GetStrategyStatus")}
}

func (_c *ViewRegistry_GetStrategyStatus_Call) Run(run func()) *ViewRegistry_GetStrategyStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ViewRegistry_GetStrategyStatus_Call) Return(strategyStatusViews []monitoring.StrategyStatusView) *ViewRegistry_GetStrategyStatus_Call {
	_c.Call.Return(strategyStatusViews)
	return _c
}

func (_c *ViewRegistry_GetStrategyStatus_Call) RunAndReturn(run func() []monitoring.StrategyStatusView) *ViewRegistry_GetStrategyStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetStrategyStatusLog provides a mock function for the type ViewRegistry
func (_mock *ViewRegistry) GetStrategyStatusLog() []monitoring.StrategyStatusView {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStrategyStatusLog")
	}

	var r0 []monitoring.StrategyStatusView
	if returnFunc, ok := ret.Get(0).(func() []monitoring.StrategyStatusView); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]monitoring.StrategyStatusView)
		}
	}
	return r0
}

// ViewRegistry_GetStrategyStatusLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStrategyStatusLog'
type ViewRegistry_GetStrategyStatusLog_Call struct {
	*mock.Call
}

// GetStrategyStatusLog is a helper method to define mock.On call
func (_e *ViewRegistry_Expecter) GetStrategyStatusLog() *ViewRegistry_GetStrategyStatusLog_Call {
	return &ViewRegistry_GetStrategyStatusLog_Call{Call: _e.mock.On("GetStrategyStatusLog")}
}

func (_c *ViewRegistry_GetStrategyStatusLog_Call) Run(run func()) *ViewRegistry_GetStrategyStatusLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ViewRegistry_GetStrategyStatusLog_Call) Return(strategyStatusViews []monitoring.StrategyStatusView) *ViewRegistry_GetStrategyStatusLog_Call {
	_c.Call.Return(strategyStatusViews)
	return _c
}

func (_c *ViewRegistry_GetStrategyStatusLog_Call) RunAndReturn(run func() []monitoring.StrategyStatusView) *ViewRegistry_GetStrategyStatusLog_Call {
	_c.Call.Return(run)
	return _c
}
