// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package activity

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/types/connector"
	"github.com/wisp-trading/sdk/pkg/types/portfolio"
	"github.com/wisp-trading/sdk/pkg/types/wisp/numerical"
)

// NewTrades creates a new instance of Trades. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrades(t interface {
	mock.TestingT
	Cleanup(func())
}) *Trades {
	mock := &Trades{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Trades is an autogenerated mock type for the Trades type
type Trades struct {
	mock.Mock
}

type Trades_Expecter struct {
	mock *mock.Mock
}

func (_m *Trades) EXPECT() *Trades_Expecter {
	return &Trades_Expecter{mock: &_m.Mock}
}

// AddTrade provides a mock function for the type Trades
func (_mock *Trades) AddTrade(trade connector.Trade) {
	_mock.Called(trade)
	return
}

// Trades_AddTrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTrade'
type Trades_AddTrade_Call struct {
	*mock.Call
}

// AddTrade is a helper method to define mock.On call
//   - trade connector.Trade
func (_e *Trades_Expecter) AddTrade(trade interface{}) *Trades_AddTrade_Call {
	return &Trades_AddTrade_Call{Call: _e.mock.On("AddTrade", trade)}
}

func (_c *Trades_AddTrade_Call) Run(run func(trade connector.Trade)) *Trades_AddTrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.Trade
		if args[0] != nil {
			arg0 = args[0].(connector.Trade)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Trades_AddTrade_Call) Return() *Trades_AddTrade_Call {
	_c.Call.Return()
	return _c
}

func (_c *Trades_AddTrade_Call) RunAndReturn(run func(trade connector.Trade)) *Trades_AddTrade_Call {
	_c.Run(run)
	return _c
}

// AddTrades provides a mock function for the type Trades
func (_mock *Trades) AddTrades(trades []connector.Trade) {
	_mock.Called(trades)
	return
}

// Trades_AddTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTrades'
type Trades_AddTrades_Call struct {
	*mock.Call
}

// AddTrades is a helper method to define mock.On call
//   - trades []connector.Trade
func (_e *Trades_Expecter) AddTrades(trades interface{}) *Trades_AddTrades_Call {
	return &Trades_AddTrades_Call{Call: _e.mock.On("AddTrades", trades)}
}

func (_c *Trades_AddTrades_Call) Run(run func(trades []connector.Trade)) *Trades_AddTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []connector.Trade
		if args[0] != nil {
			arg0 = args[0].([]connector.Trade)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Trades_AddTrades_Call) Return() *Trades_AddTrades_Call {
	_c.Call.Return()
	return _c
}

func (_c *Trades_AddTrades_Call) RunAndReturn(run func(trades []connector.Trade)) *Trades_AddTrades_Call {
	_c.Run(run)
	return _c
}

// Clear provides a mock function for the type Trades
func (_mock *Trades) Clear() {
	_mock.Called()
	return
}

// Trades_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type Trades_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *Trades_Expecter) Clear() *Trades_Clear_Call {
	return &Trades_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *Trades_Clear_Call) Run(run func()) *Trades_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Trades_Clear_Call) Return() *Trades_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *Trades_Clear_Call) RunAndReturn(run func()) *Trades_Clear_Call {
	_c.Run(run)
	return _c
}

// GetAllTrades provides a mock function for the type Trades
func (_mock *Trades) GetAllTrades() []connector.Trade {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllTrades")
	}

	var r0 []connector.Trade
	if returnFunc, ok := ret.Get(0).(func() []connector.Trade); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}
	return r0
}

// Trades_GetAllTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTrades'
type Trades_GetAllTrades_Call struct {
	*mock.Call
}

// GetAllTrades is a helper method to define mock.On call
func (_e *Trades_Expecter) GetAllTrades() *Trades_GetAllTrades_Call {
	return &Trades_GetAllTrades_Call{Call: _e.mock.On("GetAllTrades")}
}

func (_c *Trades_GetAllTrades_Call) Run(run func()) *Trades_GetAllTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Trades_GetAllTrades_Call) Return(trades []connector.Trade) *Trades_GetAllTrades_Call {
	_c.Call.Return(trades)
	return _c
}

func (_c *Trades_GetAllTrades_Call) RunAndReturn(run func() []connector.Trade) *Trades_GetAllTrades_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalVolume provides a mock function for the type Trades
func (_mock *Trades) GetTotalVolume(pair portfolio.Pair) numerical.Decimal {
	ret := _mock.Called(pair)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalVolume")
	}

	var r0 numerical.Decimal
	if returnFunc, ok := ret.Get(0).(func(portfolio.Pair) numerical.Decimal); ok {
		r0 = returnFunc(pair)
	} else {
		r0 = ret.Get(0).(numerical.Decimal)
	}
	return r0
}

// Trades_GetTotalVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalVolume'
type Trades_GetTotalVolume_Call struct {
	*mock.Call
}

// GetTotalVolume is a helper method to define mock.On call
//   - pair portfolio.Pair
func (_e *Trades_Expecter) GetTotalVolume(pair interface{}) *Trades_GetTotalVolume_Call {
	return &Trades_GetTotalVolume_Call{Call: _e.mock.On("GetTotalVolume", pair)}
}

func (_c *Trades_GetTotalVolume_Call) Run(run func(pair portfolio.Pair)) *Trades_GetTotalVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 portfolio.Pair
		if args[0] != nil {
			arg0 = args[0].(portfolio.Pair)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Trades_GetTotalVolume_Call) Return(decimal numerical.Decimal) *Trades_GetTotalVolume_Call {
	_c.Call.Return(decimal)
	return _c
}

func (_c *Trades_GetTotalVolume_Call) RunAndReturn(run func(pair portfolio.Pair) numerical.Decimal) *Trades_GetTotalVolume_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradeByID provides a mock function for the type Trades
func (_mock *Trades) GetTradeByID(tradeID string) *connector.Trade {
	ret := _mock.Called(tradeID)

	if len(ret) == 0 {
		panic("no return value specified for GetTradeByID")
	}

	var r0 *connector.Trade
	if returnFunc, ok := ret.Get(0).(func(string) *connector.Trade); ok {
		r0 = returnFunc(tradeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.Trade)
		}
	}
	return r0
}

// Trades_GetTradeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradeByID'
type Trades_GetTradeByID_Call struct {
	*mock.Call
}

// GetTradeByID is a helper method to define mock.On call
//   - tradeID string
func (_e *Trades_Expecter) GetTradeByID(tradeID interface{}) *Trades_GetTradeByID_Call {
	return &Trades_GetTradeByID_Call{Call: _e.mock.On("GetTradeByID", tradeID)}
}

func (_c *Trades_GetTradeByID_Call) Run(run func(tradeID string)) *Trades_GetTradeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Trades_GetTradeByID_Call) Return(trade *connector.Trade) *Trades_GetTradeByID_Call {
	_c.Call.Return(trade)
	return _c
}

func (_c *Trades_GetTradeByID_Call) RunAndReturn(run func(tradeID string) *connector.Trade) *Trades_GetTradeByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradeCount provides a mock function for the type Trades
func (_mock *Trades) GetTradeCount() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTradeCount")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// Trades_GetTradeCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradeCount'
type Trades_GetTradeCount_Call struct {
	*mock.Call
}

// GetTradeCount is a helper method to define mock.On call
func (_e *Trades_Expecter) GetTradeCount() *Trades_GetTradeCount_Call {
	return &Trades_GetTradeCount_Call{Call: _e.mock.On("GetTradeCount")}
}

func (_c *Trades_GetTradeCount_Call) Run(run func()) *Trades_GetTradeCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Trades_GetTradeCount_Call) Return(n int) *Trades_GetTradeCount_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *Trades_GetTradeCount_Call) RunAndReturn(run func() int) *Trades_GetTradeCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradesByExchange provides a mock function for the type Trades
func (_mock *Trades) GetTradesByExchange(exchange connector.ExchangeName) []connector.Trade {
	ret := _mock.Called(exchange)

	if len(ret) == 0 {
		panic("no return value specified for GetTradesByExchange")
	}

	var r0 []connector.Trade
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName) []connector.Trade); ok {
		r0 = returnFunc(exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}
	return r0
}

// Trades_GetTradesByExchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradesByExchange'
type Trades_GetTradesByExchange_Call struct {
	*mock.Call
}

// GetTradesByExchange is a helper method to define mock.On call
//   - exchange connector.ExchangeName
func (_e *Trades_Expecter) GetTradesByExchange(exchange interface{}) *Trades_GetTradesByExchange_Call {
	return &Trades_GetTradesByExchange_Call{Call: _e.mock.On("GetTradesByExchange", exchange)}
}

func (_c *Trades_GetTradesByExchange_Call) Run(run func(exchange connector.ExchangeName)) *Trades_GetTradesByExchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Trades_GetTradesByExchange_Call) Return(trades []connector.Trade) *Trades_GetTradesByExchange_Call {
	_c.Call.Return(trades)
	return _c
}

func (_c *Trades_GetTradesByExchange_Call) RunAndReturn(run func(exchange connector.ExchangeName) []connector.Trade) *Trades_GetTradesByExchange_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradesByExchangeAndPair provides a mock function for the type Trades
func (_mock *Trades) GetTradesByExchangeAndPair(exchange connector.ExchangeName, pair portfolio.Pair) []connector.Trade {
	ret := _mock.Called(exchange, pair)

	if len(ret) == 0 {
		panic("no return value specified for GetTradesByExchangeAndPair")
	}

	var r0 []connector.Trade
	if returnFunc, ok := ret.Get(0).(func(connector.ExchangeName, portfolio.Pair) []connector.Trade); ok {
		r0 = returnFunc(exchange, pair)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}
	return r0
}

// Trades_GetTradesByExchangeAndPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradesByExchangeAndPair'
type Trades_GetTradesByExchangeAndPair_Call struct {
	*mock.Call
}

// GetTradesByExchangeAndPair is a helper method to define mock.On call
//   - exchange connector.ExchangeName
//   - pair portfolio.Pair
func (_e *Trades_Expecter) GetTradesByExchangeAndPair(exchange interface{}, pair interface{}) *Trades_GetTradesByExchangeAndPair_Call {
	return &Trades_GetTradesByExchangeAndPair_Call{Call: _e.mock.On("GetTradesByExchangeAndPair", exchange, pair)}
}

func (_c *Trades_GetTradesByExchangeAndPair_Call) Run(run func(exchange connector.ExchangeName, pair portfolio.Pair)) *Trades_GetTradesByExchangeAndPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector.ExchangeName
		if args[0] != nil {
			arg0 = args[0].(connector.ExchangeName)
		}
		var arg1 portfolio.Pair
		if args[1] != nil {
			arg1 = args[1].(portfolio.Pair)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Trades_GetTradesByExchangeAndPair_Call) Return(trades []connector.Trade) *Trades_GetTradesByExchangeAndPair_Call {
	_c.Call.Return(trades)
	return _c
}

func (_c *Trades_GetTradesByExchangeAndPair_Call) RunAndReturn(run func(exchange connector.ExchangeName, pair portfolio.Pair) []connector.Trade) *Trades_GetTradesByExchangeAndPair_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradesByPair provides a mock function for the type Trades
func (_mock *Trades) GetTradesByPair(pair portfolio.Pair) []connector.Trade {
	ret := _mock.Called(pair)

	if len(ret) == 0 {
		panic("no return value specified for GetTradesByPair")
	}

	var r0 []connector.Trade
	if returnFunc, ok := ret.Get(0).(func(portfolio.Pair) []connector.Trade); ok {
		r0 = returnFunc(pair)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}
	return r0
}

// Trades_GetTradesByPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradesByPair'
type Trades_GetTradesByPair_Call struct {
	*mock.Call
}

// GetTradesByPair is a helper method to define mock.On call
//   - pair portfolio.Pair
func (_e *Trades_Expecter) GetTradesByPair(pair interface{}) *Trades_GetTradesByPair_Call {
	return &Trades_GetTradesByPair_Call{Call: _e.mock.On("GetTradesByPair", pair)}
}

func (_c *Trades_GetTradesByPair_Call) Run(run func(pair portfolio.Pair)) *Trades_GetTradesByPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 portfolio.Pair
		if args[0] != nil {
			arg0 = args[0].(portfolio.Pair)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Trades_GetTradesByPair_Call) Return(trades []connector.Trade) *Trades_GetTradesByPair_Call {
	_c.Call.Return(trades)
	return _c
}

func (_c *Trades_GetTradesByPair_Call) RunAndReturn(run func(pair portfolio.Pair) []connector.Trade) *Trades_GetTradesByPair_Call {
	_c.Call.Return(run)
	return _c
}

// GetTradesSince provides a mock function for the type Trades
func (_mock *Trades) GetTradesSince(since time.Time) []connector.Trade {
	ret := _mock.Called(since)

	if len(ret) == 0 {
		panic("no return value specified for GetTradesSince")
	}

	var r0 []connector.Trade
	if returnFunc, ok := ret.Get(0).(func(time.Time) []connector.Trade); ok {
		r0 = returnFunc(since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.Trade)
		}
	}
	return r0
}

// Trades_GetTradesSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTradesSince'
type Trades_GetTradesSince_Call struct {
	*mock.Call
}

// GetTradesSince is a helper method to define mock.On call
//   - since time.Time
func (_e *Trades_Expecter) GetTradesSince(since interface{}) *Trades_GetTradesSince_Call {
	return &Trades_GetTradesSince_Call{Call: _e.mock.On("GetTradesSince", since)}
}

func (_c *Trades_GetTradesSince_Call) Run(run func(since time.Time)) *Trades_GetTradesSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Trades_GetTradesSince_Call) Return(trades []connector.Trade) *Trades_GetTradesSince_Call {
	_c.Call.Return(trades)
	return _c
}

func (_c *Trades_GetTradesSince_Call) RunAndReturn(run func(since time.Time) []connector.Trade) *Trades_GetTradesSince_Call {
	_c.Call.Return(run)
	return _c
}

// TradeExists provides a mock function for the type Trades
func (_mock *Trades) TradeExists(tradeID string) bool {
	ret := _mock.Called(tradeID)

	if len(ret) == 0 {
		panic("no return value specified for TradeExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(tradeID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Trades_TradeExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TradeExists'
type Trades_TradeExists_Call struct {
	*mock.Call
}

// TradeExists is a helper method to define mock.On call
//   - tradeID string
func (_e *Trades_Expecter) TradeExists(tradeID interface{}) *Trades_TradeExists_Call {
	return &Trades_TradeExists_Call{Call: _e.mock.On("TradeExists", tradeID)}
}

func (_c *Trades_TradeExists_Call) Run(run func(tradeID string)) *Trades_TradeExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Trades_TradeExists_Call) Return(b bool) *Trades_TradeExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Trades_TradeExists_Call) RunAndReturn(run func(tradeID string) bool) *Trades_TradeExists_Call {
	_c.Call.Return(run)
	return _c
}
