// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/markets/options/types"
)

// NewOptionsAnalytics creates a new instance of OptionsAnalytics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOptionsAnalytics(t interface {
	mock.TestingT
	Cleanup(func())
}) *OptionsAnalytics {
	mock := &OptionsAnalytics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OptionsAnalytics is an autogenerated mock type for the OptionsAnalytics type
type OptionsAnalytics struct {
	mock.Mock
}

type OptionsAnalytics_Expecter struct {
	mock *mock.Mock
}

func (_m *OptionsAnalytics) EXPECT() *OptionsAnalytics_Expecter {
	return &OptionsAnalytics_Expecter{mock: &_m.Mock}
}

// GetDailyThetaDecay provides a mock function for the type OptionsAnalytics
func (_mock *OptionsAnalytics) GetDailyThetaDecay() float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDailyThetaDecay")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// OptionsAnalytics_GetDailyThetaDecay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDailyThetaDecay'
type OptionsAnalytics_GetDailyThetaDecay_Call struct {
	*mock.Call
}

// GetDailyThetaDecay is a helper method to define mock.On call
func (_e *OptionsAnalytics_Expecter) GetDailyThetaDecay() *OptionsAnalytics_GetDailyThetaDecay_Call {
	return &OptionsAnalytics_GetDailyThetaDecay_Call{Call: _e.mock.On("GetDailyThetaDecay")}
}

func (_c *OptionsAnalytics_GetDailyThetaDecay_Call) Run(run func()) *OptionsAnalytics_GetDailyThetaDecay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OptionsAnalytics_GetDailyThetaDecay_Call) Return(f float64) *OptionsAnalytics_GetDailyThetaDecay_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *OptionsAnalytics_GetDailyThetaDecay_Call) RunAndReturn(run func() float64) *OptionsAnalytics_GetDailyThetaDecay_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeltaExposure provides a mock function for the type OptionsAnalytics
func (_mock *OptionsAnalytics) GetDeltaExposure() float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDeltaExposure")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// OptionsAnalytics_GetDeltaExposure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeltaExposure'
type OptionsAnalytics_GetDeltaExposure_Call struct {
	*mock.Call
}

// GetDeltaExposure is a helper method to define mock.On call
func (_e *OptionsAnalytics_Expecter) GetDeltaExposure() *OptionsAnalytics_GetDeltaExposure_Call {
	return &OptionsAnalytics_GetDeltaExposure_Call{Call: _e.mock.On("GetDeltaExposure")}
}

func (_c *OptionsAnalytics_GetDeltaExposure_Call) Run(run func()) *OptionsAnalytics_GetDeltaExposure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OptionsAnalytics_GetDeltaExposure_Call) Return(f float64) *OptionsAnalytics_GetDeltaExposure_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *OptionsAnalytics_GetDeltaExposure_Call) RunAndReturn(run func() float64) *OptionsAnalytics_GetDeltaExposure_Call {
	_c.Call.Return(run)
	return _c
}

// GetGammaExposure provides a mock function for the type OptionsAnalytics
func (_mock *OptionsAnalytics) GetGammaExposure() float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGammaExposure")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// OptionsAnalytics_GetGammaExposure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGammaExposure'
type OptionsAnalytics_GetGammaExposure_Call struct {
	*mock.Call
}

// GetGammaExposure is a helper method to define mock.On call
func (_e *OptionsAnalytics_Expecter) GetGammaExposure() *OptionsAnalytics_GetGammaExposure_Call {
	return &OptionsAnalytics_GetGammaExposure_Call{Call: _e.mock.On("GetGammaExposure")}
}

func (_c *OptionsAnalytics_GetGammaExposure_Call) Run(run func()) *OptionsAnalytics_GetGammaExposure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OptionsAnalytics_GetGammaExposure_Call) Return(f float64) *OptionsAnalytics_GetGammaExposure_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *OptionsAnalytics_GetGammaExposure_Call) RunAndReturn(run func() float64) *OptionsAnalytics_GetGammaExposure_Call {
	_c.Call.Return(run)
	return _c
}

// GetIVSensitivity provides a mock function for the type OptionsAnalytics
func (_mock *OptionsAnalytics) GetIVSensitivity() float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIVSensitivity")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// OptionsAnalytics_GetIVSensitivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIVSensitivity'
type OptionsAnalytics_GetIVSensitivity_Call struct {
	*mock.Call
}

// GetIVSensitivity is a helper method to define mock.On call
func (_e *OptionsAnalytics_Expecter) GetIVSensitivity() *OptionsAnalytics_GetIVSensitivity_Call {
	return &OptionsAnalytics_GetIVSensitivity_Call{Call: _e.mock.On("GetIVSensitivity")}
}

func (_c *OptionsAnalytics_GetIVSensitivity_Call) Run(run func()) *OptionsAnalytics_GetIVSensitivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OptionsAnalytics_GetIVSensitivity_Call) Return(f float64) *OptionsAnalytics_GetIVSensitivity_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *OptionsAnalytics_GetIVSensitivity_Call) RunAndReturn(run func() float64) *OptionsAnalytics_GetIVSensitivity_Call {
	_c.Call.Return(run)
	return _c
}

// GetPortfolioGreeks provides a mock function for the type OptionsAnalytics
func (_mock *OptionsAnalytics) GetPortfolioGreeks() types.Greeks {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPortfolioGreeks")
	}

	var r0 types.Greeks
	if returnFunc, ok := ret.Get(0).(func() types.Greeks); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(types.Greeks)
	}
	return r0
}

// OptionsAnalytics_GetPortfolioGreeks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPortfolioGreeks'
type OptionsAnalytics_GetPortfolioGreeks_Call struct {
	*mock.Call
}

// GetPortfolioGreeks is a helper method to define mock.On call
func (_e *OptionsAnalytics_Expecter) GetPortfolioGreeks() *OptionsAnalytics_GetPortfolioGreeks_Call {
	return &OptionsAnalytics_GetPortfolioGreeks_Call{Call: _e.mock.On("GetPortfolioGreeks")}
}

func (_c *OptionsAnalytics_GetPortfolioGreeks_Call) Run(run func()) *OptionsAnalytics_GetPortfolioGreeks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OptionsAnalytics_GetPortfolioGreeks_Call) Return(v types.Greeks) *OptionsAnalytics_GetPortfolioGreeks_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *OptionsAnalytics_GetPortfolioGreeks_Call) RunAndReturn(run func() types.Greeks) *OptionsAnalytics_GetPortfolioGreeks_Call {
	_c.Call.Return(run)
	return _c
}

// GetThetaExposure provides a mock function for the type OptionsAnalytics
func (_mock *OptionsAnalytics) GetThetaExposure() float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetThetaExposure")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// OptionsAnalytics_GetThetaExposure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetThetaExposure'
type OptionsAnalytics_GetThetaExposure_Call struct {
	*mock.Call
}

// GetThetaExposure is a helper method to define mock.On call
func (_e *OptionsAnalytics_Expecter) GetThetaExposure() *OptionsAnalytics_GetThetaExposure_Call {
	return &OptionsAnalytics_GetThetaExposure_Call{Call: _e.mock.On("GetThetaExposure")}
}

func (_c *OptionsAnalytics_GetThetaExposure_Call) Run(run func()) *OptionsAnalytics_GetThetaExposure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OptionsAnalytics_GetThetaExposure_Call) Return(f float64) *OptionsAnalytics_GetThetaExposure_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *OptionsAnalytics_GetThetaExposure_Call) RunAndReturn(run func() float64) *OptionsAnalytics_GetThetaExposure_Call {
	_c.Call.Return(run)
	return _c
}

// GetVegaExposure provides a mock function for the type OptionsAnalytics
func (_mock *OptionsAnalytics) GetVegaExposure() float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVegaExposure")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// OptionsAnalytics_GetVegaExposure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVegaExposure'
type OptionsAnalytics_GetVegaExposure_Call struct {
	*mock.Call
}

// GetVegaExposure is a helper method to define mock.On call
func (_e *OptionsAnalytics_Expecter) GetVegaExposure() *OptionsAnalytics_GetVegaExposure_Call {
	return &OptionsAnalytics_GetVegaExposure_Call{Call: _e.mock.On("GetVegaExposure")}
}

func (_c *OptionsAnalytics_GetVegaExposure_Call) Run(run func()) *OptionsAnalytics_GetVegaExposure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OptionsAnalytics_GetVegaExposure_Call) Return(f float64) *OptionsAnalytics_GetVegaExposure_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *OptionsAnalytics_GetVegaExposure_Call) RunAndReturn(run func() float64) *OptionsAnalytics_GetVegaExposure_Call {
	_c.Call.Return(run)
	return _c
}
