// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wisp-trading/sdk/pkg/types/config"
)

// NewOptionsAssetLoader creates a new instance of OptionsAssetLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOptionsAssetLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *OptionsAssetLoader {
	mock := &OptionsAssetLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OptionsAssetLoader is an autogenerated mock type for the OptionsAssetLoader type
type OptionsAssetLoader struct {
	mock.Mock
}

type OptionsAssetLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *OptionsAssetLoader) EXPECT() *OptionsAssetLoader_Expecter {
	return &OptionsAssetLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type OptionsAssetLoader
func (_mock *OptionsAssetLoader) Load(cfg *config.StartupConfig) error {
	ret := _mock.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*config.StartupConfig) error); ok {
		r0 = returnFunc(cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OptionsAssetLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type OptionsAssetLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - cfg *config.StartupConfig
func (_e *OptionsAssetLoader_Expecter) Load(cfg interface{}) *OptionsAssetLoader_Load_Call {
	return &OptionsAssetLoader_Load_Call{Call: _e.mock.On("Load", cfg)}
}

func (_c *OptionsAssetLoader_Load_Call) Run(run func(cfg *config.StartupConfig)) *OptionsAssetLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *config.StartupConfig
		if args[0] != nil {
			arg0 = args[0].(*config.StartupConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OptionsAssetLoader_Load_Call) Return(err error) *OptionsAssetLoader_Load_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OptionsAssetLoader_Load_Call) RunAndReturn(run func(cfg *config.StartupConfig) error) *OptionsAssetLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}
