// Code generated by mockery v2.53.5. DO NOT EDIT.

package health

import (
	connector "github.com/backtesting-org/kronos-sdk/pkg/types/connector"
	health "github.com/backtesting-org/kronos-sdk/pkg/types/health"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// HealthStore is an autogenerated mock type for the HealthStore type
type HealthStore struct {
	mock.Mock
}

type HealthStore_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthStore) EXPECT() *HealthStore_Expecter {
	return &HealthStore_Expecter{mock: &_m.Mock}
}

// GetAvailableDataTypes provides a mock function with given fields: name
func (_m *HealthStore) GetAvailableDataTypes(name connector.ExchangeName) []health.DataType {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableDataTypes")
	}

	var r0 []health.DataType
	if rf, ok := ret.Get(0).(func(connector.ExchangeName) []health.DataType); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]health.DataType)
		}
	}

	return r0
}

// HealthStore_GetAvailableDataTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableDataTypes'
type HealthStore_GetAvailableDataTypes_Call struct {
	*mock.Call
}

// GetAvailableDataTypes is a helper method to define mock.On call
//   - name connector.ExchangeName
func (_e *HealthStore_Expecter) GetAvailableDataTypes(name interface{}) *HealthStore_GetAvailableDataTypes_Call {
	return &HealthStore_GetAvailableDataTypes_Call{Call: _e.mock.On("GetAvailableDataTypes", name)}
}

func (_c *HealthStore_GetAvailableDataTypes_Call) Run(run func(name connector.ExchangeName)) *HealthStore_GetAvailableDataTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName))
	})
	return _c
}

func (_c *HealthStore_GetAvailableDataTypes_Call) Return(_a0 []health.DataType) *HealthStore_GetAvailableDataTypes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HealthStore_GetAvailableDataTypes_Call) RunAndReturn(run func(connector.ExchangeName) []health.DataType) *HealthStore_GetAvailableDataTypes_Call {
	_c.Call.Return(run)
	return _c
}

// GetDegradedDataTypes provides a mock function with no fields
func (_m *HealthStore) GetDegradedDataTypes() map[connector.ExchangeName][]health.DataType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDegradedDataTypes")
	}

	var r0 map[connector.ExchangeName][]health.DataType
	if rf, ok := ret.Get(0).(func() map[connector.ExchangeName][]health.DataType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[connector.ExchangeName][]health.DataType)
		}
	}

	return r0
}

// HealthStore_GetDegradedDataTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDegradedDataTypes'
type HealthStore_GetDegradedDataTypes_Call struct {
	*mock.Call
}

// GetDegradedDataTypes is a helper method to define mock.On call
func (_e *HealthStore_Expecter) GetDegradedDataTypes() *HealthStore_GetDegradedDataTypes_Call {
	return &HealthStore_GetDegradedDataTypes_Call{Call: _e.mock.On("GetDegradedDataTypes")}
}

func (_c *HealthStore_GetDegradedDataTypes_Call) Run(run func()) *HealthStore_GetDegradedDataTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HealthStore_GetDegradedDataTypes_Call) Return(_a0 map[connector.ExchangeName][]health.DataType) *HealthStore_GetDegradedDataTypes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HealthStore_GetDegradedDataTypes_Call) RunAndReturn(run func() map[connector.ExchangeName][]health.DataType) *HealthStore_GetDegradedDataTypes_Call {
	_c.Call.Return(run)
	return _c
}

// GetSystemHealth provides a mock function with no fields
func (_m *HealthStore) GetSystemHealth() *health.SystemHealth {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSystemHealth")
	}

	var r0 *health.SystemHealth
	if rf, ok := ret.Get(0).(func() *health.SystemHealth); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*health.SystemHealth)
		}
	}

	return r0
}

// HealthStore_GetSystemHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSystemHealth'
type HealthStore_GetSystemHealth_Call struct {
	*mock.Call
}

// GetSystemHealth is a helper method to define mock.On call
func (_e *HealthStore_Expecter) GetSystemHealth() *HealthStore_GetSystemHealth_Call {
	return &HealthStore_GetSystemHealth_Call{Call: _e.mock.On("GetSystemHealth")}
}

func (_c *HealthStore_GetSystemHealth_Call) Run(run func()) *HealthStore_GetSystemHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HealthStore_GetSystemHealth_Call) Return(_a0 *health.SystemHealth) *HealthStore_GetSystemHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HealthStore_GetSystemHealth_Call) RunAndReturn(run func() *health.SystemHealth) *HealthStore_GetSystemHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnhealthyConnectors provides a mock function with no fields
func (_m *HealthStore) GetUnhealthyConnectors() []connector.ExchangeName {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUnhealthyConnectors")
	}

	var r0 []connector.ExchangeName
	if rf, ok := ret.Get(0).(func() []connector.ExchangeName); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]connector.ExchangeName)
		}
	}

	return r0
}

// HealthStore_GetUnhealthyConnectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnhealthyConnectors'
type HealthStore_GetUnhealthyConnectors_Call struct {
	*mock.Call
}

// GetUnhealthyConnectors is a helper method to define mock.On call
func (_e *HealthStore_Expecter) GetUnhealthyConnectors() *HealthStore_GetUnhealthyConnectors_Call {
	return &HealthStore_GetUnhealthyConnectors_Call{Call: _e.mock.On("GetUnhealthyConnectors")}
}

func (_c *HealthStore_GetUnhealthyConnectors_Call) Run(run func()) *HealthStore_GetUnhealthyConnectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HealthStore_GetUnhealthyConnectors_Call) Return(_a0 []connector.ExchangeName) *HealthStore_GetUnhealthyConnectors_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HealthStore_GetUnhealthyConnectors_Call) RunAndReturn(run func() []connector.ExchangeName) *HealthStore_GetUnhealthyConnectors_Call {
	_c.Call.Return(run)
	return _c
}

// HasReceivedData provides a mock function with given fields: name, dataType
func (_m *HealthStore) HasReceivedData(name connector.ExchangeName, dataType health.DataType) bool {
	ret := _m.Called(name, dataType)

	if len(ret) == 0 {
		panic("no return value specified for HasReceivedData")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(connector.ExchangeName, health.DataType) bool); ok {
		r0 = rf(name, dataType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// HealthStore_HasReceivedData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasReceivedData'
type HealthStore_HasReceivedData_Call struct {
	*mock.Call
}

// HasReceivedData is a helper method to define mock.On call
//   - name connector.ExchangeName
//   - dataType health.DataType
func (_e *HealthStore_Expecter) HasReceivedData(name interface{}, dataType interface{}) *HealthStore_HasReceivedData_Call {
	return &HealthStore_HasReceivedData_Call{Call: _e.mock.On("HasReceivedData", name, dataType)}
}

func (_c *HealthStore_HasReceivedData_Call) Run(run func(name connector.ExchangeName, dataType health.DataType)) *HealthStore_HasReceivedData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName), args[1].(health.DataType))
	})
	return _c
}

func (_c *HealthStore_HasReceivedData_Call) Return(_a0 bool) *HealthStore_HasReceivedData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HealthStore_HasReceivedData_Call) RunAndReturn(run func(connector.ExchangeName, health.DataType) bool) *HealthStore_HasReceivedData_Call {
	_c.Call.Return(run)
	return _c
}

// IsDataTypeHealthy provides a mock function with given fields: name, dataType
func (_m *HealthStore) IsDataTypeHealthy(name connector.ExchangeName, dataType health.DataType) bool {
	ret := _m.Called(name, dataType)

	if len(ret) == 0 {
		panic("no return value specified for IsDataTypeHealthy")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(connector.ExchangeName, health.DataType) bool); ok {
		r0 = rf(name, dataType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// HealthStore_IsDataTypeHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDataTypeHealthy'
type HealthStore_IsDataTypeHealthy_Call struct {
	*mock.Call
}

// IsDataTypeHealthy is a helper method to define mock.On call
//   - name connector.ExchangeName
//   - dataType health.DataType
func (_e *HealthStore_Expecter) IsDataTypeHealthy(name interface{}, dataType interface{}) *HealthStore_IsDataTypeHealthy_Call {
	return &HealthStore_IsDataTypeHealthy_Call{Call: _e.mock.On("IsDataTypeHealthy", name, dataType)}
}

func (_c *HealthStore_IsDataTypeHealthy_Call) Run(run func(name connector.ExchangeName, dataType health.DataType)) *HealthStore_IsDataTypeHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName), args[1].(health.DataType))
	})
	return _c
}

func (_c *HealthStore_IsDataTypeHealthy_Call) Return(_a0 bool) *HealthStore_IsDataTypeHealthy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HealthStore_IsDataTypeHealthy_Call) RunAndReturn(run func(connector.ExchangeName, health.DataType) bool) *HealthStore_IsDataTypeHealthy_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForFirstData provides a mock function with given fields: name, dataType, timeout
func (_m *HealthStore) WaitForFirstData(name connector.ExchangeName, dataType health.DataType, timeout time.Duration) error {
	ret := _m.Called(name, dataType, timeout)

	if len(ret) == 0 {
		panic("no return value specified for WaitForFirstData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(connector.ExchangeName, health.DataType, time.Duration) error); ok {
		r0 = rf(name, dataType, timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HealthStore_WaitForFirstData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForFirstData'
type HealthStore_WaitForFirstData_Call struct {
	*mock.Call
}

// WaitForFirstData is a helper method to define mock.On call
//   - name connector.ExchangeName
//   - dataType health.DataType
//   - timeout time.Duration
func (_e *HealthStore_Expecter) WaitForFirstData(name interface{}, dataType interface{}, timeout interface{}) *HealthStore_WaitForFirstData_Call {
	return &HealthStore_WaitForFirstData_Call{Call: _e.mock.On("WaitForFirstData", name, dataType, timeout)}
}

func (_c *HealthStore_WaitForFirstData_Call) Run(run func(name connector.ExchangeName, dataType health.DataType, timeout time.Duration)) *HealthStore_WaitForFirstData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connector.ExchangeName), args[1].(health.DataType), args[2].(time.Duration))
	})
	return _c
}

func (_c *HealthStore_WaitForFirstData_Call) Return(_a0 error) *HealthStore_WaitForFirstData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HealthStore_WaitForFirstData_Call) RunAndReturn(run func(connector.ExchangeName, health.DataType, time.Duration) error) *HealthStore_WaitForFirstData_Call {
	_c.Call.Return(run)
	return _c
}

// NewHealthStore creates a new instance of HealthStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthStore {
	mock := &HealthStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
