// Code generated by mockery v2.53.5. DO NOT EDIT.

package strategy

import (
	mock "github.com/stretchr/testify/mock"
	strategy "github.com/wisp-trading/sdk/pkg/types/strategy"
)

// SignalFactory is an autogenerated mock type for the SignalFactory type
type SignalFactory struct {
	mock.Mock
}

type SignalFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *SignalFactory) EXPECT() *SignalFactory_Expecter {
	return &SignalFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function with given fields: strategyName
func (_m *SignalFactory) New(strategyName strategy.StrategyName) strategy.SignalBuilder {
	ret := _m.Called(strategyName)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 strategy.SignalBuilder
	if rf, ok := ret.Get(0).(func(strategy.StrategyName) strategy.SignalBuilder); ok {
		r0 = rf(strategyName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(strategy.SignalBuilder)
		}
	}

	return r0
}

// SignalFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type SignalFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - strategyName strategy.StrategyName
func (_e *SignalFactory_Expecter) New(strategyName interface{}) *SignalFactory_New_Call {
	return &SignalFactory_New_Call{Call: _e.mock.On("New", strategyName)}
}

func (_c *SignalFactory_New_Call) Run(run func(strategyName strategy.StrategyName)) *SignalFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(strategy.StrategyName))
	})
	return _c
}

func (_c *SignalFactory_New_Call) Return(_a0 strategy.SignalBuilder) *SignalFactory_New_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SignalFactory_New_Call) RunAndReturn(run func(strategy.StrategyName) strategy.SignalBuilder) *SignalFactory_New_Call {
	_c.Call.Return(run)
	return _c
}

// NewSignalFactory creates a new instance of SignalFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignalFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignalFactory {
	mock := &SignalFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
