package version

// Code generated by scripts/generate_version.go; DO NOT EDIT.
// This file is generated from version.yaml

// SDKVersion is the current Kronos SDK version
// Update version.yaml and run 'make generate' to change this value
const SDKVersion = "v0.0.2"
